### ISSUE TITLE
Remove modules extracted from other libraries

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#100]
There are several modules that were extracted from various libraries over a decade ago:

  * `cgi.ml`
  * `netencoding.ml`

Code in these modules has warnings that will turn into errors with newer versions of OCaml (most notably, in-situ string modification). Probably the right thing to do would be to depend on the external libraries for this functionality.

**Comment by slindley** [comment]
I've removed these particular modules and we now depend on the external libraries. Some other libraries remain, `unionfind.ml`, `getopt.ml` and `PP.ml`. We should be able to get rid of `getopl.ml` as it's maintained on OPAM. We might want to keep the other two, though.

**Comment by jamescheney** [comment]
I think this is closable, as the original suggestion has been implemented.  @slindley please create an issue if you think we should replace the other files with library dependencies.
