### ISSUE TITLE
resolveServerValue fix seems to break MVU Commands

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#1018]
See my comment here: https://github.com/links-lang/links/pull/1009#issuecomment-880716251

It seems that that PR has broken MVU commands. I've had a look at it for a little while now and can't seem to understand why it's happening. The problem seems to be a result of some functions remaining unresolved, whereas they would be resolved before. Perhaps the traversal isn't going deep enough.

In any case, I'm drawing a blank so it could use a fresh pair of eyes if anyone has any bandwidth.

**Comment by ChefYeum** [comment]
Hi Simon, seems like this will be fixed in #1015

**Comment by SimonJF** [comment]
Fab, thank you!
