### ISSUE TITLE
Error locations in other modules not reported correctly

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#106]
Currently the chaser is using dummy_position when inserting modules from other files, which loses error location information. Instead, we (I) should generalise "position" to include a file name.

**Comment by SimonJF** [comment]
Just a reminder to myself that this should be fixed ASAP.

**Comment by jamescheney** [comment]
Is this still unresolved?  If so, is it resolveable for Dalry?

**Comment by SimonJF** [comment]
Still unresolved, alas. Getting it done for Dalry is probably optimistic.

**Comment by SimonJF** [comment]
Actually, given Dalry is May / June? It might well be, thinking about it (I was mistakenly thinking it would be April). It's certainly something that needs doing, so aiming for Dalry is probably a worthy goal.

**Comment by SimonJF** [comment]
The fix was a *lot* easier than expected (I'd expected a major refactoring). This should be addressed now, so if someone would like to test and merge, this should make it into Dalry.
