### ISSUE TITLE
replicate with negative argument bug

### ISSUE THREAD

**Issue by vcgalpin** [links-lang/links#1068]
the `replicate` function defined in `prelude.links` doesn't terminate if given a negative argument.
```
fun replicate(n, item) {
  if (n == 0) []
  else item :: replicate(n-1, item)
}
```

**Comment by dhil** [comment]
I suppose there are three possible solutions:
1. Return `[]` if `n` is less than or equal to `0`, i.e. change the condition to `n <= 0`
2. Raise an exception, or fail, if `n` is less than 0
3. Keep the current nonterminating semantics
