### ISSUE TITLE
space required when using < before a variable

### ISSUE THREAD

**Issue by vcgalpin** [links-lang/links#1071]
links> var x=5;
x = 5 : Int
links> 1<x;
***: Parse error: <stdin>:1

  1<x;
     ^ 
links> 1< x;
true : Bool

**Comment by dhil** [comment]
I think this is intended per the lexical syntax. `<x` is parsed as the opening of a XML tag.

**Comment by jamescheney** [comment]
Yes, this seems inevitable since XML can be freely used as an expression, without some kind of disambiguating quasiquote introducer like `xml {<x>foo</x>}`  (that might make sense to have anyway but would be a big breaking change)
