### ISSUE TITLE
Bump OCaml compiler version on Travis

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#108]
Currently, Travis is working with compiler 4.2.x.

On the silence-warnings2 branch, CI is failing because we are using String.(un)capitalize_ascii instead of String.(un)capitalize, since String.(un)capitalize is deprecated in 4.3.x upwards. 

Unfortunately, 4.2.x doesn't contain the String.(un)capitalize_ascii functions, so we get a compile error on the CI at the moment.

**Comment by SimonJF** [comment]
Fixed in 844c9b174176271abae9d47c0ce69fcdf4e2e80d.

**Comment by slindley** [comment]
See here http://www.ocaml.org/docs/install.html#Ubuntu for instructions on one way to get more up-to-date binaries.

**Comment by jamescheney** [comment]
The PPAs at https://launchpad.net/~avsm (fromAnil Madhavapeddy) only go up to OCaml 4.02.3.  Perhaps we could ask him to host an OCaml 4.04 + OPAM binary package, or we could host one there ourselves?  I'm not sure that's particularly worthwhile though to save 6 minutes per test run until Ubuntu's default ocaml catches up...

**Comment by SimonJF** [comment]
I agree; I thought the builds would take a lot longer than they're taking now. 

We can remove the explicit opam switch when the binaries catch up, but I'm happy closing this now.
