### ISSUE TITLE
Scale back distributed delegation?

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#1103]
Distributed delegation (sending channel endpoints over channel endpoints in a distributed setting) is currently implemented using a distributed algorithm loosely based on https://www.doc.ic.ac.uk/~rhu/sessionj/hyh08session-based.pdf. (The issue is that sending a receive endpoint requires care to ensure that messages are relocated, and that messages aren't lost during migration.)
This is only a problem when migrating a client endpoint to the server, and a client endpoint to another client.

The code for this is a mess and massively complicates `proc.ml` in particular. To be quite honest, I did some limited testing during my PhD but the testing was nowhere near exhaustive. In practice, the only time I've ever used distributed delegation is sending an endpoint from the server to a client, which does not require any special treatment.

I don't think the currently-unused expressive power is worth the complexity in `proc.ml` and `jslib.js`. I propose the following:

  * Default behaviour: remove the client-to-client and client-to-server delegation code, and have these cause a runtime error
 
  * To support the rare case that such functionality is needed, add a setting which keeps all buffers associated with the server; this will be less performant since each client buffer read will require a call to the server, but then the problem is eliminated since we only need to think about name passing

Feedback appreciated; thanks!

**Comment by dhil** [comment]
@SimonJF has this issue been fully or partially resolved by #1172?

**Comment by SimonJF** [comment]
Thanks @dhil , completely addressed
