### ISSUE TITLE
Record extension in the context of temporal tables

### ISSUE THREAD

**Issue by vcgalpin** [links-lang/links#1124]
The following works for non-temporal tables:
```
var test_table = table "test_table" with (
                   id: Int,
                   integer: Int)
                 where id readonly from db;
query { for (x <-- test_table)  [( a=x.id | ( b=x.integer | x ))]};
```
but trying this on temporal tables when using the functions that extract the information from the temporal tables gives an error:
```
links> query nested {  for (x <-t- reference2ligand_temporal) [(tt_from=ttFrom(x) | ttData(x) ) ]};)
***: Error: Links_core.QueryLang.DbEvaluationError("Error adding fields: non-record") 
```

**Comment by SimonJF** [comment]
I had a look at this and realised that the issue goes deeper than the temporal stuff (see #1130).

What I'll do, though, is do the minimal thing necessary to get this to work and have the tests pass. It might not be perfect until the proper fix for #1130 is worked out, but it should hopefully work for your purposes (and therefore save you a lot of in-memory computation for your case studies).
