### ISSUE TITLE
REPL prompt disappears

### ISSUE THREAD

**Issue by dhil** [links-lang/links#1174]
I have noticed a regression in the REPL. The prompt (default `links>`) disappears after a complete `enter` keystroke.

For example:

```
links> 42; # enter keystroke here
```

Renders as 
```
42;
42 : Int
```

The expected rendering is

```
links> 42;
42 : Int
```

**Comment by dhil** [comment]
I cannot rule out that it may be a problem with the particular terminal on my machine (bash 5.1.16(1)-release on Ubuntu 22.04.1). I can try on another machine later.

**Comment by jamescheney** [comment]
I'm not sure I understand the issue: it sounds like you are experiencing that the `links>` prompt is being shown initially, then you type `42;<Enter>`, and after that the prompt that had already appeared disappears leaving just the `42;`.  Is that right?  Or is it that subsequent `links>` prompts are not printed?

Using b04d184 on Mac OS 12.5.1, ocaml 4.13.1, I don't see this, after entering `42;<Enter>` a few times I see:

```
links> 42;
42 : Int
links> 42;
42 : Int
links> 42;
42 : Int
links> 
```

**Comment by dhil** [comment]
Yeah, I am being shown `links>` initially, and then it disappears after the the an `enter` keystroke.

Interesting, so it may be a problem on this specific machine then. I am able to reproduce with both OCaml 4.14.1 and 5.0.0.

**Comment by jamescheney** [comment]
Hmm - what happens if you disable the fancy command line support?  (native_readline=false)

**Comment by dhil** [comment]
It works as expected on my machine at home (same shell, same OS, same compilers). So it must be some problem with my other machine.
