### ISSUE TITLE
Rename links-mysql8 driver to links-mysql?

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#1182]
I thought we decided at the meeting last week to, in effect, discard the current `links-mysql` driver and rename `links-mysql8` to `links-mysql` (while still using `ocaml-mysql8` under the hood), but just-merged #1178 just removes `links-mysql` without renaming the `links-mysql8` driver.

I think we should do this rename, thus ensuring that the `links-mysql` package continues to be the right thing to use to connect to MySQL independent of what links version one is using.

**Comment by jamescheney** [comment]
@frank-emrich ahs there been any further discussion of this?  I think if we do this it should be done before the next release so that we don't wind up with the extra OPAM package.

**Comment by frank-emrich** [comment]
Yes, I'm planning to implement what we discussed regarding this for the upcoming release: Making the `links-mysql` package rely on the `mysql8` package instead of `mysql`. This way, running opam upgrade should seamlessly upgrade existing installations.



________________________________
