### ISSUE TITLE
Links
https://linktr.ee/enlightined1?utm_source=linktree_profile_share&ltsid=1ecc4bd3-7c5c-48e4-8ca1-7e2a12d6cd29

### ISSUE THREAD

**Issue by Papadopoulos73** [links-lang/links#1203]
https://linktr.ee/enlightined1?utm_source=linktree_profile_share&ltsid=1ecc4bd3-7c5c-48e4-8ca1-7e2a12d6cd29https://citizenwallet.notion.site/9031a31e02e84cf4899f6c22b5f5d818?v=085118bfae8d4a00832dc93e55307a91&pvs=4

**Comment by dhil** [comment]
I banned the user.
