### ISSUE TITLE
Update the website and the installation of Links on frege

### ISSUE THREAD

**Issue by slindley** [links-lang/links#127]

**Comment by jamescheney** [comment]
I believe we decided to defer this until a future release, and also investigate remote hosting / restarting the appserver (#196)

**Comment by slindley** [comment]
This is now partially done. The website now links to the Dalry release and the latest examples are running on frege. However, the current setup relies on changing all of the URLs in examples/index.html on frege pending a fix to #287.

Also, the actual text on the website should really be updated to more accurately reflect the current state of links. (Correspondingly, the descriptive text in OPAM should be updated.)

**Comment by elordin** [comment]
On a sidenote: Part of my redesign was also to make the the ["out-of-date doc"](https://github.com/links-lang/links/blob/master/doc/quick-help.pod) page prettier. It is work in progress but it also updates the content, i.e. creates up-to-date doc. (Though I'm not using the [`*.pod`](https://github.com/links-lang/links/blob/master/doc/quick-help.pod))

**Comment by jamescheney** [comment]
What needs to be done to resolve this?  Is it something that would make sense to do as part of getting TryLinks hosted?

**Comment by jamescheney** [comment]
Waiting for @slindley to set up subdomain for examples - I've sent IP address.

**Comment by jamescheney** [comment]
The subdomain is setup and I've modified the links-lang.org homepage to point to the new examples.  There are now no links to frege on the homepage.  Closing.

It would be good to reorganize the example server so that the examples are at :80 instead of :8080 though (TryLinks is at :80).
