### ISSUE TITLE
Update the current stable release

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#129]
* [x] Install executable as `linx`
  * [x] install examples from `examples` and its subdirectories: `dictionary`, `games`, `sessions`, `webserver`
  * [x] install JS libraries in `lib/links/js`
  * [x] install a config file in `etc/links/config`
    * [x] modify links to search for the config file (cf. `basicsettings.ml` and `links.ml`)
    * [x] figure out how to modify the config file to contain the actual absolute path to js library files
  * [x] update installation instructions

**Comment by jgbm** [comment]
Can I suggest that #130 be included as close to the critical path here as possible?  I suspect that any attempt to use the app server in anger will encounter it.

**Comment by jstolarek** [comment]
@slindley, I think I implemented everything we spoke about. Can you pull branch `js-T129-fix-installation` and test whether everything works as expected? I still have documentation to update, which I'll do next week.

@jgbm, sure. Added #130 to the TODO list. Once it's fixed we'll release.

**Comment by slindley** [comment]
Certainly heading in the right direction. Once we have updated documentation it'll be more obvious what's missing. One additional thing that we might want to consider including is the tests directory along with the run-tests script.

**Comment by jstolarek** [comment]
@slindley - I updated the installation instructions. If there are no objections I will release sometime next week.

@jgbm - @slindley said he wants to do a release ASAP, so I'll release without waiting for #130. Once #130 is fixed we will make a second update release.

**Comment by SimonJF** [comment]
Sam suggested that this might happen next week; I'm hoping to have #130 done by then (unless it proves to be trickier).

**Comment by slindley** [comment]
@jstolarek, I tweaked the installation instructions in your branch - mainly to add some missing articles :)

It looks like Simon will have #130 fixed before next week. I'd like to aim for a release on Monday if possible.

**Comment by jstolarek** [comment]
Thanks for fixing the articles - I have problems with those :-/

Would release on Tuesday morning work?

**Comment by slindley** [comment]
Not many articles in Polish :) Tuesday morning should be fine.
