### ISSUE TITLE
Inner functions cannot have type signatures

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#149]
For example, we get a parse error with the following:

```
fun foo() {
  sig bar : () -> String
  fun bar() {
    "Hello!"
  }
  bar()
}
foo()
```

**Comment by dhil** [comment]
Indeed. I doubt there is any well motivated reason behind this. Anyways, you can resort to using type annotations if you want to control the inferred type, e.g.
```
fun foo() {
  fun bar() {
    "Hello!" : String
  }
  bar()
}
foo()
```
Obviously, this approach does not scale very well if you have several formal parameters.

**Comment by SimonJF** [comment]
It might just be a parser thing with the fix falling out naturally if we make a small change there -- I'll have a play around.

**Comment by slindley** [comment]
This is a vestige of the original Links implementation where top-level definitions were distinct from local bindings in the AST and a known issue. It certainly makes sense to support type signatures on local bindings. Location annotations on local bindings didn't make sense before we introduced closure conversion. Perhaps they do now.

**Comment by dhil** [comment]
@simonjf status?

**Comment by SimonJF** [comment]
Interrupted by PLDI deadline. I'll have a go.
