### ISSUE TITLE
Links Fatal Error: Cannot yet jsonize non-client proceses

### ISSUE THREAD

**Issue by elordin** [links-lang/links#159]
```
Links-version: 0.6.1
```

```
[ ] Proposal
[x] Bug
[ ] Feature Request
[ ] Other
```

Running the draggable-list example via `servePages` results in an error page

> ## Links Fatal Error
> Cannot yet jsonize non-client proceses 

and console-output

> `Cannot yet jsonize non-client proceses`

`main.links`
```
open Draggable

fun main () {
  addRoute("/draggable", fun (_) { Draggable.mainPage() });

  servePages()
}

main()
```

`draggable.links`
Identical to the [example file](http://groups.inf.ed.ac.uk/links/examplessrc/draggable.links) with the `page` statement at the end wrapped in the `mainPage` function
```
fun mainPage () {
  page
  <html>
    <body>
      <h2 style="font: 42px/30px Georgia, serif; color: #7E9E50;">Great Bears</h2>
      {draggableList("bears",["Pooh", "Paddington", "Rupert", "Edward"])}
       ...
    </body>
  </html>
}
```

**Comment by jgbm** [comment]
This is curious to me for several reasons.

First, the current (i.e., from `master`) version of `addRoute` has type `(String, (String, Location ~> Page)) ~> ()`, so your example code shouldn't even type, let alone produce errors.

Second, if you fix that, what you've described is _exactly_ the way that the draggable lists example is included in examples/webserver/examples.links, which definitely works for me.

**Comment by elordin** [comment]
Note that when I said
```
Links-version: 0.6.1
```
i meant the `0.6.1` release (i.e. a880c68)

**Comment by elordin** [comment]
Using `master` @ 568ff46 (and changing the `addRoute`) does indeed resolve the `Cannot yet jsonize non-client proceses`

**Comment by jstolarek** [comment]
Thomas, there's no need to tag tickets with:

```
[ ] Proposal
[x] Bug
[ ] Feature Request
[ ] Other
```

We use GitHub labels for that.

**Comment by elordin** [comment]
Sorry, habit

**Comment by SimonJF** [comment]
Hi Thomas, you should be able to add labels now.

**Comment by elordin** [comment]
Thanks

**Comment by jgbm** [comment]
Also, note that `draggable.links` had already been updated for the webserver in the 0.6.1 release, and did not generate errors about Jsonizing things.

**Comment by elordin** [comment]
I also couldn't find the error message I got in the source which is somewhat odd.

Either way, all's well that ends well, and if it pops up again it is at least partially documented here.
