### ISSUE TITLE
Cannot compose a page when using formlets

### ISSUE THREAD

**Issue by elordin** [links-lang/links#160]
```
Links-version: 0.6.1
```

Consider the following example
```
var nameFormlet = 
  formlet 
    <#>
      { input -> name }
    </#>
    yields name;
  
fun nameHandler (name) {
  page
    <div> { stringToXml(name) } </div>
}
```

Creating a page that shows the formlet is trivial
```
page <html><body> { nameFormlet => nameHandler } </body></html>
```

So far, so good.

Should the page that displays the formlet become more complicated though, it 
will at some point be necessary to split/modularize a bit. E.g.

```
page
  <html>
    <body>
      { pageHeader() }
      <section>
        { pageMainContent() }
      </section>
      <aside>
        { pageSidebar() }
      </aside>
      { pageFooter() }
    </body>
  </html>
```

But since formlets cannot be in XML-quasiquotes, unless part of a page, none of the components above can contain the formlet.

Thus all formlets must always be included at the top-most level.

Another example: (the above example "imports" XML into the page, below we "extend" an XML skeleton)
```
# Extendable Skeleton to reduce redundancy/boilerplate 
fun pageSkeleton (title, body) {
  <html>
    <head>
      <meta charset="utf-8" />
      <title>{ stringToXml(title) }</title>
      <!-- other head stuff -->
    </head>
    <body>
      <header><!-- header stuff --></header>
      <main>
        { body }
      </main>
      <footer><!-- footer stuff --></footer>
    </body>
  </html>
}
```

Now `body` as an `Xml` value cannot contain formlets.

Either "including" or "extending" of partial pages is essential for reusable, modular markup.

Since formlets cannot be used in this context, they are only viable for very small pages.

**Comment by jamescheney** [comment]
I think I ran into/complained about this problem a while ago, there is a discussion of how to workaround this in this ancient thread:

http://lists.inf.ed.ac.uk/pipermail/links-users/2010-February/000227.html

It would be nice to have a better way to do this.  Probably it would be good to document page splicing somewhere also.

**Comment by elordin** [comment]
Turns out there is an undocumented way to embed pages in pages with `{| p |}`

So the above is possible via

```
var nameFormlet = 
  formlet 
    <#>
      { input -> name }
    </#>
    yields name;

fun nameHandler (name) { page <div> { stringToXml(name) } </div> }

fun pageHeader () { page <header> { nameFormlet => nameHandler } </header> }

page
  <html>
    <body>
      {| pageHeader() |}
    </body>
  </html>
```
