### ISSUE TITLE
Parser regression: rules never reduce

### ISSUE THREAD

**Issue by dhil** [links-lang/links#170]
We have introduced a regression in the parser as there are two rules which never reduce
```
$ ocamlyacc -v parser.mly && cat parser.out
2 rules never reduced
[ ... ]
Rules never reduced:
	perhaps_exp :  (97)
	perhaps_exp : exp  (98)
[ ... ]
```
I believe this regression was introduced by @simonjf in PR #147 (which I approved!) specifically it was introduced in the commit 4c358dc1c7c18644a39e51fd1a77ed50a08eb886.

**Comment by dhil** [comment]
I suppose the fix is easy: simply remove the nonterminal `perhaps_exp` from `parser.mly`. However, before I submit this fix I would like @SimonJF to confirm that `perhaps_exp` is no longer intended to be used.

**Comment by SimonJF** [comment]
Yes; I recall putting `perhaps_exp` back, then not needing it. I think it was when I was doing first-class Locations. It can go, as you do in b72239e.

**Comment by dhil** [comment]
Right. I should cherry pick my fix.
