### ISSUE TITLE
Internal Server Error on RPC

### ISSUE THREAD

**Issue by elordin** [links-lang/links#175]
[Code](https://gist.github.com/elordin/108df5bd33499a8c1095cc9e0bb9398c)

When clicking the _"Add"_ Button an `AddItem` message is sent to the `apiService` Process, where the [message handler](https://gist.github.com/elordin/108df5bd33499a8c1095cc9e0bb9398c#file-uselet_db1-links-L340) calls [insertItem](https://gist.github.com/elordin/108df5bd33499a8c1095cc9e0bb9398c#file-uselet_db1-links-L326). 

An AJAX request is then created for the database operation on the server. 

This requests fails with a `500 Internal Server Error`

```
Error handling ((headers
  ((accept */*) (accept-encoding "gzip, deflate, br")
   (accept-language "de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4")
   (connection keep-alive) (content-length 724)
   (content-type application/x-www-form-urlencoded) (dnt 1)
   (host localhost:8080) (origin http://localhost:8080)
   (referer http://localhost:8080/)
   (user-agent
    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36 OPR/45.0.2552.812")))
 (meth POST) (resource /) (version HTTP_1_1) (encoding (Fixed 724))): (Failure "jsonparse: first argument to a table must be a database")
```

Database connection works, as the page displays the list items already in the DB when first loading. (Loaded at [422](https://gist.github.com/elordin/108df5bd33499a8c1095cc9e0bb9398c#file-uselet_db1-links-L422)).

**Comment by jamescheney** [comment]
Special case of #525

**Comment by dhil** [comment]
Closing since #525 has been closed.
