### ISSUE TITLE
use websocket 2.8 for now

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#179]
For some reason (possibly related to https://github.com/ocaml/opam-repository/issues/3000, or to recent changes in the build setup for websocket, or both), websocket.cohttp 2.9 won't install correctly for me on mac os X.  

I suggest that for the Dalry release we peg the version of websocket used to be <= 2.8, unless there is 2.9 is strictly better in some way, in which case we should raise an issue on websocket pointing out the dependence on currently non-portable conf-gmp and zarith libraries.

**Comment by SimonJF** [comment]
2.8 should be fine for the time being, assuming it installs correctly. It's a pain that this is the case though :(

2.7 and before is problematic, due to a frame corruption issue.

**Comment by jamescheney** [comment]
OK, I will raise an issue against websocket 2.9 - though I'm still not sure what the problem is.  Using the opam pin / opam install --dep-only commands from travis.yml means that OPAM tries to install zarith and conf-gmp (which fail) and I also get a weird (compilation) error when compiling websocket 2.9 itself. 

Assinging to myself as a reminder to fix the OPAM file for next release and raise issue on the webockets  package.

**Comment by slindley** [comment]
You should run `opam install depext` and then `opam depext conf-gmp.1` which should tell you what OS dependencies you need to install in order to support conf-gmp.

**Comment by saradecova** [comment]
Thank you. Though, I've already run those so it is not complaining about
missing anything now.

**Comment by saradecova** [comment]
oops, sorry.

**Comment by jamescheney** [comment]
I haven't done that, but that is irrelevant to the problem reported above.

I already worked out that conf-gmp depends on gmp which I had already installed.  The problem is that the conf-gmp opam package does not install on Mac OS if gmp is installed somewhere other than /usr/local.  zarith has a similar problem.  (I found a workaround for conf-gmp, so now have that installed, but not for zarith - though symlinks would presumably work.)

See the issue I referenced, https://github.com/ocaml/opam-repository/issues/3000

The thing I'm not sure about is why opam pin / opam install --dep-only want to install conf-gmp/zarith in the first place, as they don't appear to be needed and everything works if I install websocket 2.8 manually.  The travis log doesn't show what packages actually get installed on ubuntu when we do this.

**Comment by fehrenbach** [comment]
I think the reason we don't see what's installed on travis is that nothing gets installed, because everything is installed already. We enabled caching of ~/.opam at some point.

That is not to say that the pin/install --deps-only stuff isn't horribly broken. It may well be. I've only dry-run this locally.

You could remove the cache line https://github.com/links-lang/links/blob/master/.travis.yml#L8 and push to a branch to see what happens.

**Comment by jamescheney** [comment]
I've added a constraint to force websocket <= 2.8, and apparently this doesn't break anything (as usual, I created a branch and meant to make a pull request but committed / pushed to master.  Maybe we should turn off commits directly to master to make it harder to accidenally do this.)  Closing.

**Comment by slindley** [comment]
This is not a sustainable fix - it is bad form to indefinitely require an out-of-date version of a library. Now that websocket 2.10 is out, do you still have the issue?

**Comment by slindley** [comment]
I had to remove this constraint in order for other recent packages to even install.
