### ISSUE TITLE
Fun with polymorphic effect types

### ISSUE THREAD

**Issue by elordin** [links-lang/links#181]
Compiling [this code](https://gist.github.com/elordin/d9d5768ad995232b3dd81ccf2371b36e) gives 

```
Type error: The function
    `view(send)(model)'
has type
    `Uselet (Services)'
while the arguments passed to it have types
    `AddressSource'
and
    `Services'
and
    `Dispatcher'
and the currently allowed effects are
    `|wild'
In expression: view(send)(model)(childGen, services, dispatcher).
```
Looks again very much like effect polymorphism (s. #173).
The [effect in the `Uselet` type](https://gist.github.com/elordin/d9d5768ad995232b3dd81ccf2371b36e#file-fun_with_effects-links-L29) needs to be either `|wild` or `wild|hear:d|e`

I'd appreciate any suggestions on how to make that happen.

**Comment by jamescheney** [comment]
I'm not sure what the right syntax is but it should be possible to quantify over "any effect row containing wild along with possibly other stuff" rather than "any effect".

**Comment by jamescheney** [comment]
Perhaps `{wild|y}~>` instead of `{ | y}~>` ?

**Comment by elordin** [comment]
> The squiggly function arrow is syntactic sugar for denoting that the computation has the wild effect

from _[Compilation of Effect Handlers and their Applications in Concurrency](http://homepages.inf.ed.ac.uk/s1467124/papers/thesis2016.pdf)_

so `wild` should already be in there

**Comment by jamescheney** [comment]
D'oh, sorry, jet lag.  So why isn't the problem that on line 27,  `services` is uncapitalized (hence, treated as a free type variable), when it should be `Services`?

**Comment by jamescheney** [comment]
Nope, never mind, line 25 binds `services` as a parameter that later gets instantiated to `Services`, jet lag strikes again.  I'm stumped, will try again when I've had more than 3 hours sleep.

**Comment by dhil** [comment]
With a few type modification you can make the program type check:
```links
typename Address = [Int];
typename AddressSource(e::Row) = () { |e}~> Address;

sig makeAddr : (AddressSource({ |e})) { |e}~> (Address, AddressSource({ |e}))
fun makeAddr (source) {
  var address = source();
  (address, fun () { var h :: t = address; (h + 1) :: t })
}

sig makeSource : (Address) { |e}~> AddressSource({ |e})
fun makeSource (address) { fun () { 0 :: address } }

fun addrToString (addr) {
  switch (addr) {
    case [ ] -> error("Empty address")
    case (h :: t) -> fold_left(fun (prev, curr) { intToString(curr) ^^ "-" ^^ prev }, intToString(h), t)
  }
}

typename DispatcherMessage = forall a, b. [| Deregister: Address | Ignore | Send: (a, Address) | Broadcast: a | Register: (Address, b) |];
typename Dispatcher = Process ({ hear:DispatcherMessage,wild });

typename Services = forall a :: Row. ( |a);

typename Uselet(services) = forall y::Row. (
  AddressSource({ |y}),
  services,
  Dispatcher
) { |y}~> (
  Xml,
  AddressSource({ |y})
);


var nodeAddrPrefix = "_render_node_";

sig uselet : (
  String,
  model,
  (Services) { hear:msg |r}~> (model, msg) { hear:msg|r}~> model,
  forall z :: Row. ((e) ~> ()) { |z}~> (model) { |z}~> Uselet(Services)
) -> Uselet(Services)
fun uselet(name, model, updt, view) {
  fun (addressSource, services, dispatcher: Dispatcher) {

    var (addr, gen) = makeAddr(addressSource);
    var childGen = makeSource(addr);
    var id = nodeAddrPrefix ^^ addrToString(addr);

    fun send (msg) { dispatcher ! Send(msg, addr) }
    fun emit (msg) { dispatcher ! Broadcast(msg) }

    var updateWithServices = updt(services);

    fun hndlr (oldState) {
      receive {
        case msg -> {
          var newState = updateWithServices(oldState, msg);
          var (xml, _) = view(send)(newState)(childGen, services, dispatcher);
          # Do stuff with xml
          hndlr(newState)
        }
      }
    }

    var hndlr = spawnClient { hndlr(model) };
    dispatcher ! Register(addr, fun (msg) { hndlr ! msg });

    var (xml, _) = view(send)(model)(childGen, services, dispatcher);

    (xml, gen)
  }
}
```
I have opened up some effect contexts which were closed in your program. For example you use `makeAddr` whose effect row is `{wild}` in a larger context `{wild,hear:msg|_}` which gives rise to the unification equation `{wild} ~ {wild,hear:msg}` which has no solution. Similarly for the third parameter in the signature of `uselet`.

I usually parameterise type aliases over function types by their effects. However, in this particular program I think you can get away with universal quantification, i.e. 
```links
typename AddressSource = forall e :: Row . () { |e}~> Address
```

**Remark**: I have deliberately changed the variable name `handler` to `hndlr` because `handler` becomes a reserved keyword in the next release of Links.

**Comment by slindley** [comment]
Thanks Daniel. But all of this higher-rank polymorphism is bogus and probably makes the implementation useless, e.g., I doubt that a useful implementation of a dispatcher exists at this type.

**Guideline**: don't use `forall` at the top level of a type alias unless you really know what you're doing. Normally what you should do is to parameterise type aliases as Daniel suggests.

Here's an updated version of the code that doesn't use `forall` at all, and which might even admit useful instances!

    typename Address = [Int];
    typename AddressSource(e::Row) = () { |e}~> Address;

    sig makeAddr : (AddressSource({ |e})) { |e}~> (Address, AddressSource({ |e}))
    fun makeAddr (source) {
      var address = source();
      (address, fun () { var h :: t = address; (h + 1) :: t })
    }

    sig makeSource : (Address) { |e}~> AddressSource({ |e})
    fun makeSource (address) { fun () { 0 :: address } }

    fun addrToString (addr) {
      switch (addr) {
        case [ ] -> error("Empty address")
        case (h :: t) -> fold_left(fun (prev, curr) { intToString(curr) ^^ "-" ^^ prev }, intToString(h), t)
      }
    }

    typename DispatcherMessage(i, o) = [| Deregister: Address | Ignore | Send: (o, Address) | Broadcast: o | Register: (Address, i) |];
    typename Dispatcher(i, o) = Process ({ hear:DispatcherMessage(i, o), wild });

    typename Uselet(services, i, o, e::Row) = (
      AddressSource({ |e}),
      services,
      Dispatcher((i) { |e}~> (), o)
    ) { |e}~> (
      Xml,
      AddressSource({ |e})
    );

    var nodeAddrPrefix = "_render_node_";

    sig uselet : (
      String,
      model,
      (services) { hear:i|e}~> (model, i) { hear:i|e}~> model,
      ((o) ~> ()) {:i|e}~> (model) {:i|e}~> Uselet(services, i, o, {hear:i|e})
    ) -> Uselet(services, i, o, {hear:i|e})
    fun uselet(name, model, updt, view) {
      fun (addressSource, services, dispatcher) {

        var (addr, gen) = makeAddr(addressSource);
        var childGen = makeSource(addr);
        var id = nodeAddrPrefix ^^ addrToString(addr);

        fun send (msg) { dispatcher ! Send(msg, addr) }
        fun emit (msg) { dispatcher ! Broadcast(msg) }

        var updateWithServices = updt(services);

        fun hndlr (oldState) {
          receive {
            case msg -> {
              var newState = updateWithServices(oldState, msg);
              var (xml, _) = view(send)(newState)(childGen, services, dispatcher);
              # Do stuff with xml
              hndlr(newState)
            }
          }
        }

        var hndlr = spawnClient { hndlr(model) };
        dispatcher ! Register(addr, fun (msg) { hndlr ! msg });

        var (xml, _) = view(send)(model)(childGen, services, dispatcher);

        (xml, gen)
      }
    }

I've also changed the type variables to have more sensible names.
