### ISSUE TITLE
Document page splicing

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#182]
See #160.

**Comment by elordin** [comment]
@jamescheney Since the referenced #160 is closed with a description of `page` composition, is this still current?

**Comment by jamescheney** [comment]
"Document" means there should be documentation.  I don't consider issue discussions documentation since you have to know they're there (and guess the right thing to search for) to learn anything from them.  For now, a short wiki page (a) admitting that page splicing exists and (b) how / why to use it would suffice, since the Links team seems to be collectively allergic to doing anything to links/doc/quick-help.pod.

**Comment by elordin** [comment]
I see. I read "document" not as the verb but the noun.

**Comment by elordin** [comment]
Added a [wiki page](https://github.com/links-lang/links/wiki/Page-splicing). Someone should probably check it before closing this issue.

**Comment by jamescheney** [comment]
Thanks, I added a sentence to explain why one might want/need to use page splicing instead of plain XML splicing - for example to allow splitting up a page that uses formlets.
