### ISSUE TITLE
Pattern matching failure in miskinded type application

### ISSUE THREAD

**Issue by yallop** [links-lang/links#19]
Here's a buggy program that causes a pattern matching failure in instantiate.ml:

```
links> typename T(r::Row) = [|r|];
T = a::Row.[||a|]
links> typename X = T(Int);
*** Error: File "instantiate.ml", line 396, characters 15-20: Pattern matching failed
```

**Comment by dhil** [comment]
Arguably this "issue" has been resolved, but the error message could be much improved with little effort. Actually, looking in `instantiate.ml` all those failwiths and assertions should probably be replaced by exceptions instead.
