### ISSUE TITLE
Remote hosting and automatic appserver restart

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#196]
Investigate setting up a remotely hosted server for Links example, with some infrastructure to restart the Links appserver process if it becomes unresponsive / crashes.  (for example http://supervisord.org/)

**Comment by dhil** [comment]
On my own installation I use systemd to manage the Links appserver. My configuration is available at https://gist.github.com/dhil/70e08d82f1f49cb94b987a9c4f799cea

**Comment by jamescheney** [comment]
This (kind of thing) is basically done, and does not require changes to Links, so closing.
