### ISSUE TITLE
addRoute API

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#199]
In Links 0.6, addRoute had this type:

```
sig addRoute : (String, (String) ~> Page) ~> () 
```

but recently (4c358dc) it changed:

```
sig addRoute : (String, (String, Location) ~> Page) ~> ()
```

Since the shortcuts such as `serveThis` and `serveThese` haven't been introduced to a numbered Links version yet, this means that any code that we write for 0.6 has to change for 0.7 and vice versa.  This complicates various things such as the tutorial.

Proposed solution 1: Revert `addRoute` to the previous type, introduce a new function `addRouteWithLocation` with the new type.

Proposed solution 2: keep addRoute as is, add a new function `addSimpleRoute` with the new type

Proposed solution 3: define a RequestHandler type that is (for now) a variant with cases for simple handlers:
```
type RouteHandler = [|SimpleHandler: (String) ~> Page| Handler : (String,Location) ~> Page|]
sig addRoute : (String,RouteHandler) ~> ()
```

Proposed solution 4: something something row polymorphism
```
sig addRoute : (String,(path:String,location:Location) ~> ()
```

I lean toward solution 3, even though it is a breaking change w.r.t 0.6, since it seems more future-proof if we decide we want to change anything else about route handlers.

(in that case `serveThis` and `serveThese` should be modified so as to use the `RouteHandler` type...)

**Comment by SimonJF** [comment]
I'd probably vote for changing it back and adding `addRouteWithLocation`, since this is what I really should have done in the first place.

I think 3 and 4 add extra complexity. Since the users of Links are localised to here, it's probably not worth it in the long run to fix a mistake I made early on.

**Comment by elordin** [comment]
I agree with Simon that that would add complexity.

As a user it is much simpler to just add a wildcard for an argument I don't care about and thus don't need to understand vs. having to know that there are different kinds of RoutHandlers.

Of course the even better solution is to offer a simple interface (`addRoute`) for most usecases and provide an additional interface (`addRouteWithLocation`) for more experienced users.

I do find the name `addRouteWithLocation` a bit unfortunate though, as it suggests that I add a route _with/and_ a location.

**Comment by jamescheney** [comment]
OK, I'm happy with the reverting option (solution 1).

Regarding naming, I think one problem is that `addRoute` is not very descriptive: I would say it adds a route *handler*, and so we might name the two versions as follows:
```
sig addSimpleRouteHandler : (String, (String) ~> Page) ~> () 
sig addLocatedRouteHandler : (String, (String, Location) ~> Page) ~> ()
```
and keep `addRoute` with its original type for compatibility.

Does that sound reasonable?  

Simon, since you're already all too familiar with the examples that need to be changed, could you do this?  (Actually, all that should be needed is changing existing calls to `addRoute` to call `addLocatedRouteHandler` or whatever we eventually decide to call it.)

**Comment by jgbm** [comment]
I think that routing (i.e., the action performed by routes) is the handling of URLs.  So, `addSimpleUrlHandler` or `addLocatedUrlHandler` would make more sense to me.  De gustibus &c.

**Comment by elordin** [comment]
Now this may be a little odd as I am one of the few non-native speakers, but I'd argue that
_Routing_ is the act of performing actions based on a given _route_ (which in the web happens to be an URI/URL), done by a _router_.

So to me `addSimpleUrlHandler`, `addSimpleUriHandler`, and `addSimpleRouteHandler` are all pretty much equivalent.

Another question for discussion: Would it be sufficient for the base-case to be just `addUrlHandler` with specialized variants like `addLocatedUrlHandler`?
