### ISSUE TITLE
Can start app-server even when port is already bound

### ISSUE THREAD

**Issue by elordin** [links-lang/links#200]
When the port used by the app server is in use by some other application, e.g. a second app server, startup should fail with some descriptive error message.

Instead it currently just runs quietly and unreachably.

**Comment by SimonJF** [comment]
A second webserver running always gives me a port in use error. I can't reproduce this.

**Comment by elordin** [comment]
Double checked. Turns out I can bind multiple times to the same port with other tools/languages as well. So this is not a Links but a OS/virtualization issue.
