### ISSUE TITLE
Tie in prelude with the module system

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#201]
Currently prelude loading is rather magical. It would be nice to have it incorporated into the module system, working towards a more modular standard library.

**Comment by dhil** [comment]
I have also been thinking that it would be good to have virtual modules for some built-in functions such as the collection of `dom...` functions.

**Comment by SimonJF** [comment]
Definitely, I agree. It'll need a bit of designing though so this is certainly not a "Dalry" issue...

**Comment by SimonJF** [comment]
Currently, though, modules opened in the prelude aren't accessible from user files due to a chaser bug, so I'll have to get on that.

**Comment by SimonJF** [comment]
I would say that this is addressed by the "standard library" patch, which has since been merged.
