### ISSUE TITLE
Soundness error due to JS'es treatment of round floats

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#206]
```
[simon@bodygold ~]$ node
> - 1.0
-1
> -1.0
-1
> -(1.0)
-1
> -1.1
-1.1
```

Now, say we have a client program which JSONises `-1.0`. It will get parsed in and treated as an *integer* -- and we then lose type soundness (not great).

The only way I can see of getting around this (save for carrying around type information, which we won't want to do) is boxing floats on the client. Although the prospect does fill me with terror, given the performance hit that would be incurred.

**Comment by SimonJF** [comment]
An alternative could be to ensure unbox_float also works on things boxed as integers. This might be a better idea in fact...

**Comment by jamescheney** [comment]
What would be a concise Links example that breaks (Links) type soundness?

**Comment by SimonJF** [comment]
Sure:

```
sig serverFn : (Float) ~> ()
fun serverFn(should_be_float) server {
  print(floatToString(should_be_float))
}

fun mainPage() {
  var proc = spawnClient {
    receive {
      case x -> serverFn(x)
    }
  };

  page
    <html><body>
      <button l:onclick="{proc ! 5.0}">Click me!</button>
    </body></html>
}


fun main() {
  addRoute("/", fun(_,_) { mainPage() });
  servePages();
}

main()
```

If you click the button, you get:

```
Doing RemoteCall for function fun, client ID: cid_0
Type error unboxing float
```

This is in the RPC setting, but the same goes for anything that crosses the client / server boundary (i.e. distributed actor, or distributed session channel messages).

I'm thinking the "add an integer case to unbox_float" fix is probably better than boxing all floats, but would like to take comments before I do so.
