### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by elordin** [links-lang/links#210]
Technically rather irrelevant, but coming form (graphic) design, the generic auto-generated image on the [links-lang page](https://github.com/links-lang/) bothers me, so I'm just gonna drop this proposal here:

![linkslang](https://user-images.githubusercontent.com/6238752/27503943-ff90231e-5879-11e7-912f-13e9ebf603e0.png)

**Comment by jamescheney** [comment]
Looks reasonable to me (if also a tiny bit reminiscent of the Python logo :)

We could add the text "links" in the dark blue color, with a red dot on the "i", as a vague nod towards the School of Informatics logo (see https://www.facebook.com/InformaticsUoE for example, though weirdly the official University pages don't seem to have it anywhere...)

We would also have to change the style files of the Links main page, as orange doesn't really go with the above :)

**Comment by SimonJF** [comment]
Isn't our logo just "Nope" in <h1>?

Seriously though, nice! Didn't you redesign the website, too? It would be cool to see it at the next meeting!

**Comment by jamescheney** [comment]
Hilariously, in my email version of Simon's comment (but not in the webpage version above) the `<h1>` gets interpreted as HTML, so the rest of Simon's comment renders as large, bold header text.  So I now wonder if Github (or Gmail) has a massive code injection vulnerability...

**Comment by SimonJF** [comment]
Ha! It appeared as large, bold header text here too until I edited and enclosed it with quotes :)

**Comment by elordin** [comment]
Rationale for the logo:
Somewhat reminiscent of the std links icon
![icon_1690](https://user-images.githubusercontent.com/6238752/27510300-8fd40efa-5905-11e7-8c1a-5413efb04a48.png)

Looks like two `L`s

Colours are in fact chosen in reference to the University of Edinburgh colours, though different CI guides give differen colour codes.

Blue "Links" with ret i-dot is an idea I very much like!
![linkslang](https://user-images.githubusercontent.com/6238752/27511537-a9100310-591e-11e7-9d05-ef249692e735.png)

If anyone knows or has the font "School of Informatics" is originally in, I'd apprecciate that.

> We would also have to change the style files of the Links main page, as orange doesn't really go with the above :)

I didn't come unprepared ;)
![5b1cc011-0723-4187-8ed3-12c1a1b0ae15](https://user-images.githubusercontent.com/6238752/27511580-511bff96-591f-11e7-9ea0-46b3cf2e7ab1.png)

**Comment by elordin** [comment]
[Logo](https://github.com/links-lang/links-lang.github.io/blob/master/img/logo.png) etc. are now part of the [github.io-Repo](https://github.com/links-lang/links-lang.github.io/)
