### ISSUE TITLE
replaceNode fails silently if the xml argument contains a l:action form

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#219]
# Input
The following code snippet uses `replaceNode` to add two XML form snippets to a document, one using `l:action` and the other using `l:onsubmit`.

```
fun testPage(msg){
  page
  <html>
    <body>
      <div id="t">
        <h4>HAHAH</h4>
      </div>
      <div id="p">
        <p>LALA</p>
      </div>
      <a href="" l:onclick="{changeContent()}">Click me</a>
    </body>
  </html>
}

fun changeContent(){
  replaceNode(
    <div id="t">
      <form l:onsubmit="{}" method="post">
        <input type="text" l:name="i" value="" />
      </form>
    </div>,
    getNodeById("t")
  );
  replaceNode(
    <div id="p">
      <form l:action="{testPage(i)}" method="post">
        <input type="text" l:name="i" value="" />
      </form>
    </div>,
    getNodeById("p")
  )
}


fun main () {
  addRoute("",testPage);
  servePages()
}

main()
```

# Expected output

When the button is clicked, both HAHAH and LALA should change to input fields; the first should have no results and the second should call testPage again with a new message (this can never actually happen because there is no way to submit the forms, the main thing is that the content should change.)

# Actual output

HAHAH changes to an input field but LALA does not.  Inspecting the (Firefox) JS console suggests that what is happening is a failure in jslib when base64decode is called during a call to _remoteCallHandler (at the point where the server response is sent to _debug).  This in turn suggests that something is going wrong somewhere else, but I don't know what.

I'm uncertain whether this is something that just should not work (in which case we should catch the error somehow) or it should work but doesn't.

Swapping the order of the two replaceNode calls also confirms that the `l:action` call fails, since if we try to do that replacement first then nothing happens.

**Comment by elordin** [comment]
The `base64decode` fails because the server response is

> __Links Error__
> Notfound.NotFound(" (in Hashtbl.find)")

so something fails on the server.

Since the program runs error-free when removing the second `replaceNode` it looks more like the `l:action` is the problem, rather than the `l:onsubmit`.

**Comment by jamescheney** [comment]
Argh, sorry, I got the two attribute names mixed up, now fixed the title of the issue.

**Comment by jamescheney** [comment]
it would be interesting to know why any server-side call is happening; is the `l:onclick='{changeContent()}` handler for `testPage` calling the server for no particular reason?  Why is `_remoteCallHandler` even being called in the first place?

**Comment by jamescheney** [comment]
Having reviewed `desugarLAttributes.ml`, there is a comment near the top: https://github.com/links-lang/links/blob/b850dd24e8ba6fa0b4ef694532639a1c54e47ae3/core/desugarLAttributes.ml#L9-L14

I think this issue is an instance of client-side `l:action` not being supported.  Similarly, the following example that attempts to replace a node with a `l:href` link, also does not work with a similar error:
```
mutual {
fun testPage(msg) {
  page
  <html>
    <body>
      <div id="t">
        <h4>HAHAH</h4>
      </div>
      <div id="p">
        <p>LALA</p>
      </div>
      <a href="" l:onclick="{changeContent()}">Click me</a>
    </body>
  </html>
}

fun changeContent() client {
  replaceNode(
      <form l:onsubmit="{error("asdf")}" method="post">
        onSubmit handled OK
      </form>
    ,
    getNodeById("t")
  );
  replaceNode(
        <a l:href="{testPage("asdf")}">href handled OK</a>
    ,
    getNodeById("p")
  )
}
}

fun main () {
  addRoute("",testPage);
  servePages()
}

main()
```

(note that the original example needed to be updated to be explicit about mutual recursion).

**Comment by jamescheney** [comment]
Fundamentally, this happens because `l:action` and `l:href` are desugared to code that calls `pickleCont` and generates HTML that calls the resulting continuation (from the client).

If the call to `pickleCont` itself happens *on the client* then we see the above behavior.

If in contrast we force the evaluation of the xml snippet passed as the first argument to `replaceNode` to happen *on the server* then the right thing seems to happen:
```
fun snippet () server {
  <a l:href="{testPage("asdf")}">href handled OK</a>
}

fun changeContent() client {
  replaceNode(
      <form l:onsubmit="{error("asdf")}" method="post">
        onSubmit handled OK
      </form>
    ,
    getNodeById("t")
  );
  replaceNode(
        snippet() 
    ,
    getNodeById("p")
  )
}

```
thus, a workaround for this issue seems to be to manually force any XML snippets containing (desugared) `l:href` or `l:action` to be evaluated on the server.

A proper, if maybe inefficient, solution may be to force the evaluation of `pickleCont` (and its arguments) to happen on the server no matter what.  (Such a solution would be complicated by the fact that the continuation that handles the `l:action` or `l:href` may not be closed - suggesting that it might be better to do this l-attribute desugaring after closure conversion...)

But perhaps there is some way of getting the right thing to happen on the client-side without creating extra round trips to the server.

**Comment by jamescheney** [comment]
This should be fixed by first making it possible to put client and server annotations on local functions (#907) then updating/redoing PR #906 so as to ensure that the call to `pickleCont` happens on the server.  It would be good also to enforce that `pickleCont` can only be called on the server.

**Comment by jamescheney** [comment]
As mentioned in #1118, this is partly fixed in that the first example program above now works, but the second one (with href) does not.  To fix that still seems to require enforcing that local functions can be tagged with client or server annotations.the discussion in #907 should be revisited.  Just adding a server annotation on `pickleCont` in prelude.links does not fix the problem on its own, but still seems like a good idea anyway.

**Comment by jamescheney** [comment]
After experimenting with adding client/server annotations (#1133) I am fairly sure that the original bug reported here is now fixed.  The problem mentioned above where l:href and l:action attributes don't work properly on the client appears to be a long-standing issue, documented in a TODO in desugarLAttributes.ml:

```
(* TODO:

   Either disallow l:href and l:action in client-side XML or, more
   usefully, provide proper support for sending client-side closures
   to the server.
*)
```
In fact, at the moment these operations *do* work if they are called from a top-level server function (i.e. if we manually eta-expand, lambda lift and hoist the first argument of replaceNode so that it is called from the server), since this ensures that the functions created during desugaring are called on the server.  If this is not the case then something bad happens, but it appears that that is not new behavior, it was just masked by the original issue.  I therefore think this should be closed and a new enhancement issue created.
