### ISSUE TITLE
Adding `typename` breaks code

### ISSUE THREAD

**Issue by elordin** [links-lang/links#226]
[uselet_kanban.zip](https://github.com/links-lang/links/files/1148071/uselet_kanban.zip)

In this project, in `services.links`, adding line 4, an unused `typename`, leads to a type error (which I will not post here because it is ~21k characters long).

The problem seems to be some kind of clash with the `receive` clause below, since removing that makes it compile just fine.

**Comment by slindley** [comment]
this code turd is far too big for a bug report and highly unlikely to be looked at until some attempt is made to minimise its size
