### ISSUE TITLE
Tail call optimise jslib

### ISSUE THREAD

**Issue by dhil** [links-lang/links#228]
Pull request #216 makes the Links client side code base compliant with JavaScript [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode). As a result our code base gets to benefit from tail call optimisation (TCO) in Chrome (TCO is not supported by Firefox or Microsoft Edge; I think it is supported by default by Safari) which ought to improve the performance of Links client side code.

Now, it would be reasonable to expect that we get TCO for free once we turn on strict mode as the Links JavaScript compiler generates code in continuation passing style. However being JavaScript reasonable is unreasonable. JavaScript employs [an unusual definition of tail position](http://2ality.com/2015/06/tail-call-optimization.html#pitfall-solo-function-calls-are-never-in-tail-position). As an example consider this code
```javascript
function foo() { bar(); }
```
One might be inclined to think that `bar` is invoked in tail position. But it is not, because it is semantically equivalent to 
```javascript
function foo() { bar(); return; }
```
which in turn is equivalent to
```javascript
function foo() { bar(); return undefined; }
```
Thus `bar` must be marked by a `return` statement to be in tail position, i.e.
```javascript
function foo() { return bar(); }
```
This is unfortunate, because the vast majority of code in jslib has no explicit return statements. Therefore, I suggest to amend jslib such that we can take advantage of TCO in the (near) future.

**Comment by dhil** [comment]
I have a (mostly) tail call optimised version of jslib in the `jslib-tco` branch. It is based on @elordin 's `xml-support` branch.

**Comment by SimonJF** [comment]
Super exciting -- congrats and thanks!
