### ISSUE TITLE
Missing DOCTYPE on HTML pages

### ISSUE THREAD

**Issue by elordin** [links-lang/links#233]
As the spec says:

> A DOCTYPE is a required preamble.

Links-generated documents don't have one.

**Comment by SimonJF** [comment]
This should be easy; add it to `irtojs.ml`?

**Comment by elordin** [comment]
Yes. 
In theory at least.
But ...

Adding the `<!DOCTYPE html>` (which I would argue is the only reasonable one) kind of implies that the generated documents are compliant with that doctype.

Since `page` takes abitrary `Xml`, there is no guarantee that it only includes elements that are part of that doctype. Kind of meh.

And then there is additional fun with self-closing tags: There is a list of void elements that must be self-closing, e.g. `img`, and then there are all other elements, including custom elements registered via `customElements.define`, that _must not_ be self-closing, even if empty, to be valid.

**Comment by jamescheney** [comment]
There was some discussion early on about finer-grained typechecking for the XML fragments a la XDuce/CDuce, which I think went by the wayside a while ago (back when it seemed more likely that future HTMLs would align with XML).  

Not sure what to do / if anything should be done about support for HTML5 tag soup style, other than perhaps wait for the Web to collapse.  Does anyone volunteer to write an embedded HTML5 parser/validity checker?  Maybe a lighter-weight alternative might be to keep track of whether a tag is self-closing in our XML representation, and preserve this, making it the programmer's problem...

**Comment by elordin** [comment]
> Maybe a lighter-weight alternative might be to keep track of whether a tag is self-closing in our XML representation, and preserve this, making it the programmer's problem...

This would work for me as a programmer.

**Comment by slindley** [comment]
This didn't "go by the wayside". We consciously decided not to do anything as messy/heavyweight as XDuce/CDuce.

**Comment by rudihorn** [comment]
My workaround for the moment was to just add a comment to force it to not self close, e.g. 
> <script src="/bootstrap/js/bootstrap.min.js">/* test */</script>

**Comment by elordin** [comment]
> My workaround for the moment was to just add a comment to force it to not self close, e.g.

That sure works but having to add a comment for every empty element, except for the 14 void elemnts, is _very_ cumversome.

**Comment by SimonJF** [comment]
Closed in #506
