### ISSUE TITLE
Migrate to http/af

### ISSUE THREAD

**Issue by dhil** [links-lang/links#241]
The built-in web server in Links is based on [cohttp](https://github.com/mirage/ocaml-cohttp). Cohttp is due to be replaced by [http/af](https://github.com/inhabitedtype/httpaf) some time in the future, therefore we might consider replacing cohttp with http/af in Links.

**Comment by SimonJF** [comment]
Are we still looking to do this? From what I can tell, `cohttp` is still going strong.

**Comment by dhil** [comment]
It may be worth to replace cohttp with http/af when we decide to refactor the Webserver and Proc modules (since the performance of http/af is allegedly much better than cohttp).
