### ISSUE TITLE
run-tests ignores port configuration

### ISSUE THREAD

**Issue by elordin** [links-lang/links#250]
Configuring the database port in `tests/database/config` does nothing since it is never used.

**Comment by fehrenbach** [comment]
Care to elaborate?

**Comment by elordin** [comment]
To give a brief written elaboration:
`./run-tests` only uses the user string from `tests/database/config` so when it [actually runs psql as part of run-tests](https://github.com/links-lang/links/blob/master/run-tests#L60) it uses port 5432 regardless of what the config file says.

**Comment by dhil** [comment]
Yes it would be convenient if the test script read some environment variable for the test config. I always manually change `database_args=localhost:5432::links` to `database_args=localhost:5432:links:`.

**Comment by elordin** [comment]
Not even a need for environment-variables, since there is [a config file](https://github.com/links-lang/links/blob/master/tests/database/config.sample). It is just ignored for the most part.
