### ISSUE TITLE
Scoping of nested for comprehensions vs multiple binders

### ISSUE THREAD

**Issue by fehrenbach** [links-lang/links#26]
Are these two snippets meant to be equivalent?

```
for (a <- [[1], [2]])
  for (b <- a)
    [b]
```

```
for (a <- [[1], [2]],
     b <- a)
  [b]
```

They are not, because a is not visible in the binding for b, in the second version.

Type error: Unknown variable a.
In expression: a.

**Comment by jamescheney** [comment]
That looks like a bug to me - later expressions in a single "for" should be in the scope of earlier variables. But probably we should wait until Sam or someone has a chance to check this, in case I'm missing something.

**Comment by slindley** [comment]
I'm pretty sure this was a deliberate design choice (it is not a bug), though I can't quite remember the rationale.

**Comment by fehrenbach** [comment]
Okay, thanks!

For the record, I think this should be changed, or even better: gotten rid of completely.
(Closing anyways, since I don't want to do it and I doubt anyone else does.)
