### ISSUE TITLE
opam pre-release sanity checking

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#267]
We should have a process for testing that the opam installation works correctly (along with any updates needed to the links-tutorial Vagrantfile or other code), before making the official release, to avoid problems like #266.

**Comment by jamescheney** [comment]
@SimonJF could you (once you're feeling better) add a wiki page describing this (or add to the "Release Checklist" page)?

**Comment by SimonJF** [comment]
Sure! I'll do this Sunday / Monday.

**Comment by jamescheney** [comment]
Is this (the wiki page) done now?  It doesn't look like any relevant wiki pages have been changed.

**Comment by SimonJF** [comment]
I thought I'd done this -- but looking on the Wiki, it doesn't look like I have. I'll do it after lunch; thanks for the reminder.

On 27/10/17 11:25, James Cheney wrote:

Is this (the wiki page) done now? It doesn't look like any relevant wiki pages have been changed.

**Comment by SimonJF** [comment]
https://github.com/links-lang/links/wiki/Pre-release-sanity-checking

**Comment by jamescheney** [comment]
Great, thanks!
