### ISSUE TITLE
Table column names with underscores

### ISSUE THREAD

**Issue by fehrenbach** [links-lang/links#27]
(in the shredding branch)

Underscores have special meaning in shredding/nested-records queries. Links gets confused when columns have underscores in their names.

```
var agencies =
  table "agencies"
  with (oid: Int,
        id: Int,
        name: String,
        based_in: String,
        phone: String)
  where oid readonly
  tablekeys [["oid"], ["id"]]
  from db;
```

Generated query:

``` sql
select (0) as "1_1",(t1778."2") as "1_2",(t1776."based_in") as "2_a_data_based_in",(t1776."id") as "2_a_data_id",(t1776."name") as "2_a_data_name",(t1776."oid") as "2_a_data_oid",(t1776."phone") as "2_a_data_phone",(t1776."oid") as "2_a_prov_row",('agencies') as "2_a_prov_table" from (select (1) as "2") as t1778,agencies as t1776
```

> **\* Fatal error : Internal error: NotFound "based" (in Map.find) while interpreting.

**Comment by fehrenbach** [comment]
Correction: the problem seems to be fields with underscores in the result.

**Comment by jamescheney** [comment]
Assigned to Stefan to look at this as per Sept. 2 meeting.
