### ISSUE TITLE
Cannot write comments in XML mode

### ISSUE THREAD

**Issue by elordin** [links-lang/links#270]
Suppose the I want to add comments to my code.

When doing that in between XML there are the following scenarios:
```
<div>
  # Links style comment
</div>
```
Prints the comment on the page

---
```
<div>
  <!-- XML style comment -->
</div>
```
```
Unexpected character : <
            <!-- -->
              ^
```
---
```
<div>{
  # Comment back in Links mode
}</div>
```
```
Type error: XML child nodes must have type `Xml'
```
---
The only thing that works is
```
<div>{
  # Comment with empty XML value
  <#/>
}</div>
```

**Comment by dhil** [comment]
Would you expect an XML comment to be preserved, i.e. to be part visible in source of a generated page?

**Comment by elordin** [comment]
Best case scenario would be to have XML comments preserved and an additional flag, `--no-xml-comments` or something, that allows to hide them.

I personally don't mind limited [support for older IEs](https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx) but there are good reasons for XML-comments. Like, you know, documentation ;)
