### ISSUE TITLE
Table names are case-insensitive

### ISSUE THREAD

**Issue by elordin** [links-lang/links#271]
When working with tables with case-sensitive table-names, Links crashes because the relation could not be found. This is unspurising, since the created query uses the unquoted table-name:
```SQL
SELECT (t3029."id") as "id" FROM myUsers as t3029;
```
Links-strings, used to name tables, are case-sensitive.
Attributes are translated quoted, so they case-sensitive as well.

This makes this unnecessarily confusing. 
All database-related strings should be treated the same with respect to case.

**Comment by jamescheney** [comment]
Does this actually stop us from doing something we want to be able to do, or does it just mean that the case-sensitivity of the Links table name strings needs to be documented somewhere?

**Comment by elordin** [comment]
Given that this is just a matter of naming, it does not prevent any specific thing from being written.

One fix is to document that somewhere and assume that the user has read the full documentation.
But a solution would also be to just quote the table name when generating the query.
