### ISSUE TITLE
Opening an empty module causes Links to crash

### ISSUE THREAD

**Issue by dhil** [links-lang/links#276]
Links crashes if a program opens an empty module.
```
$ touch empty.links
$ echo "open Empty" > openEmpty.links
$ ./links -m --path="." openEmpty.links
*** Error: (Invalid_argument Bytes.create)
```

**Comment by elordin** [comment]
Which, I would assume, is result and cause of 
```
$ touch empty.links
$ ./links empty.links
*** Error: (Invalid_argument Bytes.create)
```
Executing empty Links files leads to errors.

**Comment by dhil** [comment]
Thanks. So (maybe) it is not related to modules.

**Comment by dhil** [comment]
The problem seems to be `find_line` in `sourceCode.ml` (line 58). I think it returns a negative value for the empty program.

**Comment by dhil** [comment]
Fixed. Now it returns a "proper" Links error
```
$ echo "" > empty.links
$ ./links empty.links
*** Parse error: empty.links:1

  
    ^
```
