### ISSUE TITLE
Alien functions are not added to the environment

### ISSUE THREAD

**Issue by dhil** [links-lang/links#281]
Alien functions should be added to the environment after declaration (of course calling them should only be allowed in web mode!)
```
links> alien javascript "test.js" f : () {}-> ();
Raised at file "utility.ml", line 139, characters 25-117
Called from file "value.ml" (inlined), line 280, characters 27-51
Called from file "links.ml", line 280, characters 39-64
Called from file "map.ml", line 196, characters 19-42
Called from file "links.ml", line 272, characters 22-1023
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Called from file "errors.ml", line 114, characters 4-16
*** Error: Notfound.NotFound("2094 (in Map.find)")
```

**Comment by SimonJF** [comment]
This is just at the REPL, right?

**Comment by dhil** [comment]
Yes

**Comment by SimonJF** [comment]
Alright.

**Comment by jamescheney** [comment]
I suggest we defer this to 0.7.3 and release 0.7.2 ASAP.

**Comment by jamescheney** [comment]
This seems likely to be shallow? In any case kicking to >0.7.3 seems fine.

**Comment by dhil** [comment]
I had a look at resolving this issue recently. It requires a bit of plumbing to get right. In particular, we might need to extend the IR with a special value for alien-things such that we can bind the alien binder to that value in the REPL.

**Comment by jamescheney** [comment]
Ah, I was thinking it might be shallow if it is only an issue in the REPL and not in code loaded in from a file.  If changes are needed to the IR we should cross-reference with @frank-emrich 's work on #41

**Comment by dhil** [comment]
It seems reasonable that attempting to run a JavaScript function in the REPL should yield a "not in web mode error". However, when one starts thinking about supporting other languages via the alien interface, such was OCaml, the implications for the FFI starts getting interesting. It seems reasonable that one should be able to run OCaml alien functions from the REPL, since those would be server-side functions. So we need a design for the FFI that is flexible enough to take the "location" of the foreign language in account.

**Comment by jamescheney** [comment]
OK, I get it - previously alien calls were only Javascript call hence always JS so never appearing in IR (or at least represented by a client side continuation).  

This is definitely worthwhile @frank-emrich keeping in mind then.

**Comment by frank-emrich** [comment]
@dhil there is already some alien function support in the IR:
the binding type in the IR has the following  constructor 
 `Alien of (binder * name * language)

**Comment by dhil** [comment]
@frank-emrich yes, alien functions are indeed represented in the (`ir.ml`) IR. The problem is that alien binders never are bound in the value environment in the evaluator. In order to bind them we need some special value.

I realise my comment above was ambiguous, so I have edited it to say "the value variant" instead of IR.
