### ISSUE TITLE
JS calls object as function

### ISSUE THREAD

**Issue by elordin** [links-lang/links#282]
[282.zip](https://github.com/links-lang/links/files/1333309/282.zip)
(the vast majority of the files is fairly old and worked with previous versions of links. the only addition is in `components.links`. Also I realised that I use a non-standard `lib.ml` which additionally has 
```OCaml
  "patchDom",
  (`Client, datatype "(DomNode, XmlItem) ~> ()",
  IMPURE);
  "historyPushState",
  (`Client, datatype "(a, String, String) ~> ()",
  IMPURE);
```
)

`$ ./links -m main.links`

Interacting with the web-page results in 
```
Uncaught TypeError: env_2712_2815.2699 is not a function
```
because
```JavaScript
env_2712_2815['2699'] 
```
is called as a function but is
```JSON
{
  "environment": { "2583": "" },
  "func": "_2588",
  "location": "unknown"
}
```
which is identical to `var _2716` in line 3889 of the generated page.

In multiple previous instances of it being called it actually is a function and works fine.

Any suggestions?

**Comment by jamescheney** [comment]
This needs to be sliced down to a bug report / test

**Comment by dhil** [comment]
Issue #354 provides a minimal example exposing this bug.
