### ISSUE TITLE
Use Dynlink to load database drivers

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#284]
As per #240, adapt the work by @Yuren-Zhong on using Ocaml's Dynlink facility to:

- [ ] Put the DB drivers in separate directories (using jbuilder?)
- [ ] Define OPAM packages links-DRIVERNAME that build and install these libraries in some appropriate place (where the instance of Links installed by OPAM will find them)
- [ ] Add a command line flag / config option to specify which database drivers to load on startup OR (maybe better) Modify Links so that the first time a database driver is referenced, it is loaded in using Dynlink

**Comment by frank-emrich** [comment]
I have posted about this in #265 since my answer is thightly coupled with building with JBuilder

**Comment by jamescheney** [comment]
Now done by #265
