### ISSUE TITLE
Examples page should not be static

### ISSUE THREAD

**Issue by slindley** [links-lang/links#287]
The examples should not be implemented using a static web page containing hard-coded JavaScript as they are now. Crucially, the URLs need to be able to change according to the configuration of Links. (In particular, this is a problem for the online instance of the examples linked from the web page which needs to have an external base URL "/links/".)

If we really need to use native JavaScript for the examples then we can use the FFI.

**Comment by elordin** [comment]
I assume you are deliberately vague on this one. Could you however describe in a bit more detail, what you imagine the example pages to look like?

```JavaScript
// index.links
var files = scandir('/examples')
map(fun (file) { if (file.filetype === 'links') { <a href={ file.url }>{file.name}</a> } else { <#/> }, files)
```
?
```JavaScript
// examples.config
examples = [
  { name: "Draggable list", url: "/draggable.links" },
  ... 
]
```
?

Also, what is the exact downside of using native JavaScript for the convenience-feature of frame-loading? (Except for "It's not Links" of course)

**Comment by jamescheney** [comment]
Would like to get this and #127 done before 0.8.0.

**Comment by slindley** [comment]
Yes

**Comment by jamescheney** [comment]
What concretely needs to be done here (i.e. what file needs to change)?

**Comment by dhil** [comment]
@jamescheney, I suppose `examples/index.html` should be a Links program.

**Comment by slindley** [comment]
It would still be nice to fix this issue in order to allow the examples to be hosted with something other than a root path (as required by the online setup for the examples that the official Links website previously relied on). However, this is no longer necessary for the official Links website as the examples are now hosted on a separate server.

**Comment by SimonJF** [comment]
This is probably easy enough. Instead of continuing to shunt it, I'll take a look after I've finished writing the changelog.

**Comment by jamescheney** [comment]
:tada:
