### ISSUE TITLE
Proposal: Replace <| |> as infix "backtick" operators in OCaml source

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#288]
`|>` and `<|` are common "pipe" idioms for reverse function application. Heavily used in F# and widely gaining adoption elsewhere (Elixir, for example), these operations allow one to chain operations in "pipelines" as so:

```
let example xs =
  List.map (fun x -> if Char.is_upper x then [x] else []) xs
  |> List.concat
```
instead of, say

```
let example xs =
  List.concat (List.map (fun x -> if Char.is_upper x then [x] else []) xs)
```

It's a nice way of writing code. Currently, however, these are shadowed as "backtick" notation for infix operators in `utility.ml`, in order to do things such as the following:

```
  let valenv, v = lazy (Eval.run_program valenv program) <|measure_as|> "run_program" in
  lazy (printer t v) <|measure_as|> "print";
  valenv, v
```

This means that one must explicitly do `let open Pervasives in` before a pipeline to shadow the backtick notation.

I propose we change this, so that we can use the idiomatic pipeline constructs. I don't really mind what we change them to, but I'd really like to have pipeline notation without having to explicitly import Pervasives every time.

**Comment by fehrenbach** [comment]
The backtick versions seem to be used only 6 times in links.ml, once in utility.ml and nowhere else?
I'm in favour.

**Comment by jamescheney** [comment]
The two definitions in Utility.ml are:

```
let ( <| ) arg f = f arg
let ( |> ) f arg = f arg
```
The definition of `|>` in Pervasives is
```
let ( |> ) f x =  x |> f
```
This is the opposite of the utility.ml definition, while `<|` is not defined in Pervasives. (but right-associative application `@@` is.)

I suggest we define `<|` as follows (and remove the shadowing definition of `<|`) 
```
let ( <| ) f arg = f arg
```
and then we can do
``` 
 let valenv, v = lazy (Eval.run_program valenv program) <|measure_as|> "run_program" in
  lazy (printer t v) |>measure_as<| "print";
  valenv, v
```

A bit ugly but it works, and if we aren't using infix backticks that much anyway then hopefully it's not a big problem.

**Comment by dhil** [comment]
When using infix operators we need to be particularly careful about side-effecting functions due to OCaml's undefined evaluation order*.

* Officially evaluation order is undefined, but unofficially the evaluation order is right-to-left.

**Comment by jamescheney** [comment]
@dhil That is a good point, but I believe my proposed fix is behavior-preserving w.r.t. the previous version, at least.  (It's almost alpha-equivalent to the current version of Links, the only difference is that we now use Pervasives.(|>) instead of redefining both pipe operators.  It should in any case be observationally equivalent (whatever the ambient assumptions on evaluation order are) but I don't have a proof of this.
