### ISSUE TITLE
Update Jake's VDOM Library to latest version of the JS Library, and include in standard library.

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#291]
The library makes use of a lot of FFI stuff which has changed. I should fix this.

**Comment by dhil** [comment]
We could potentially make use of this for our new intern's project. Where do I find the source code?

**Comment by SimonJF** [comment]
Just an update on this ancient issue: this is underway, along with a large cleanup. The hope is to get it merged soon.

**Comment by SimonJF** [comment]
Oh wow, I can actually close this! Closed by #640.
