### ISSUE TITLE
Side effecting modules

### ISSUE THREAD

**Issue by dhil** [links-lang/links#314]
In our code base we have several modules which play effects at the top level. Some modules, including `evalir.ml`, `value.ml`, `irtojs.ml`, and `links.ml`, rely on these side-effects to be played in a specific order. Common for side-effecting modules are that the depend on the handling of settings and command line arguments. In PR #227 the settings and their handling were centralised to ensure that their side-effects were played before initialisation of the module `Value` as it depends on the presence or absence of flags like `--enable-handlers` and `--sessions-exceptions`.

Previously the `Makefile` enforced a linking order of modules which happened to be doing the right thing, perhaps by sheer luck. However since PR #254 we no longer control the linking order as a result it introduced artificial dependencies amongst `Value`, `Irtojs`, `Evalir`, and `ParseSettings` to ensure that the side-effecting modules are loaded in the correct order.

This is obviously bad, very bad. The handling of settings needs to be decentralised again, and made pure.

**Comment by jamescheney** [comment]
Doesn't seem critical to resolve before 0.7.3 so happy to kick to next version.
