### ISSUE TITLE
Jbuilder -> Dune

### ISSUE THREAD

**Issue by dhil** [links-lang/links#315]
Jbuilder got itself a new name. Starting from the next release it will be known as Dune.

Presumably, this name change will cause some small amount of migration work to happen on our code base, e.g. new name for `jbuild` files, new name for the `jbuilder` dependency, etc. 

The possible implications of this name change is currently being discussed on ticket janestreet/jbuilder#362.

**Comment by jamescheney** [comment]
Is this worth doing / arleady done for 0.7.3?

**Comment by dhil** [comment]
It is not clear to me whether the configuration format for `dune` has been settled yet.

**Comment by jamescheney** [comment]
No rush, I guess this why we said 0.8 for this originally.

**Comment by jamescheney** [comment]
> I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to pass over me and through me. And when it has gone past I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain.
