### ISSUE TITLE
Hear and hardcoded arrow syntax

### ISSUE THREAD

**Issue by dhil** [links-lang/links#330]
Any function which has the hear effect must also have the wild effect.

However, the wild arrow syntax is hard-coded together with the syntactic sugar for the hear effect in the parser, meaning that the following correct type (and program) is rejected
```
> sig f : () {:a,wild}-> () fun f() { () }
*** Parse error: <stdin>:1

  sig f : () {:a,wild}-> () fun f() { () };
```
In order to make it parse successfully one must use the wild arrow syntax, i.e.
```
> sig f : () {:a}~> () fun f() { () }
f = fun : () {:_}~> ()
```
... or spell out the hear effect, i.e.
```
> sig f : () {hear:a,wild}-> () fun f() { () };
f = fun : () {:_}~> ()
```

**Comment by jamescheney** [comment]
Closed by #739
