### ISSUE TITLE
Type variable names are shared amongst definitions of mutually recursive functions

### ISSUE THREAD

**Issue by dhil** [links-lang/links#344]
Somehow type variables become shared across mutually recursive functions, e.g.
```
sig f : () {hear{a} |_}~> ()
fun f() { g() }

sig g : () {hear{_} |a}~> ()
fun g() { f() }
```
In `f` the type variable `a` is intended to have kind `Presence`, while the type variable `a` in `g` should be of kind `Row`. That is, both variables are supposed have different implicit quantifiers. However the above program produces the following kinding error
```
*** Fatal error : kind mismatch in type variable: ("a", (`Presence, None), `Rigid) vs: ("a", (`Row, None), `Rigid)
```
Introducing explicit quantifiers resolves the problem; the following program type checks
```
sig f : forall a::Presence . () {hear{a} |_}~> ()
fun f() { g() }

sig g : forall a::Row . () {hear{_} |a}~> ()
fun g() { f() }
```
Omitting either of the quantifiers results in one of two errors.

1. Omitting `forall a::Presence` in the signature for `f` yields the error ``*** Fatal error : kind mismatch in type variable: ("a", (`Presence, None), `Rigid) vs: ("a", (`Row, None), `Rigid)``
2. Omitting `forall a::Row` in the signature for `g` yields another error ``*** Error: DesugarDatatypes.UnexpectedFreeVar("a")``

In the absence of recursion the problem does not arise as the follow program demonstrates
```
sig f : () {hear{a} |_}~> ()
fun f() { g() }

sig g : () {hear{_} |a}~> ()
fun g() { () }
```
And for completeness, the problem does not arise when the names are different, e.g.
```
sig f : () {hear{a} |_}~> ()
fun f() { g() }

sig g : () {hear{_} |b}~> ()
fun g() { f() }
```

**Comment by jamescheney** [comment]
This seems potentially related to #42, #377, #368.
