### ISSUE TITLE
List operations on Strings not working

### ISSUE THREAD

**Issue by klaplong** [links-lang/links#347]
While trying to concatenate two `String`s the compiler told me this was not allowed since `++` takes two lists of some type, but is given two `String`s instead. This is odd, since [the quick start guide says](http://links-lang.org/quick-help.html#base_types):

> The type String is not really a base type, but rather an alias for [Char] (the type for lists of characters). This means that any general list operation will work on a String.

Annotating the `String`s as `[Char]`s, e.g. `var s = "test" : [Char]`, does not work either, since the interpreter tells me I'm dealing with a `String`, not a `[Char]`. I suspect the aliasing is not working as expected.

**Comment by dhil** [comment]
Nowadays the `String` type is a base type. Use `^^` to concatenate two strings.

The "quick start guide" used to come with a disclaimer, saying that it is out-dated.
