### ISSUE TITLE
Global let bound anonymous functions are not compiled correctly to the client

### ISSUE THREAD

**Issue by dhil** [links-lang/links#353]
The JavaScript compiler produces meaningless code for global let-bound anonymous functions. The following minimal example illustrates the problem
```
var f = fun() { () };

fun mainPage(_) {
  page
   <#>
    <button l:onclick="{f()}">Click me!</button>
   </#>
}

fun main() {
  addRoute("/", mainPage);
  servePages()
}

main()
```

The global let binding `f` gets compiled as
```
function _fun__g131_2064(__kappa) { _yieldCont(__kappa, {}) }
var f_2065 = {"func":"_2064", "location":"unknown"};
function _fun__g132_2068(_2067, __kappa) { var event_2066 = _2067; _yield(function () { f_2065(__kappa) }) }
```
Clearly, `f_2065` is not a function.

This problem happens irrespective of whether handlers are enabled.

If the binding is localised in for example `mainPage`, then the code generator emits the correct code.

**Comment by dhil** [comment]
It appears to me that `resolveServerValue` in `jslib.js` does not work on toplevel function values; if the function value is tagged by a data constructor, e.g.

```links
var abc = 42;
var bar = Bar(fun(x) { x + abc });

fun mainPage(_) {
  page
   <#>
     <button l:onclick="{switch (bar) { case Bar(g) -> println(intToString(g(42))) } }">Click me!</button>
   </#>
}

fun main() {
  addRoute("/", mainPage);
  servePages()
}

main()
```

Prints `82` in the console. So we may not need to change any changes to the JavaScript compiler to fix this issue, rather, I think we need to rethink `resolveServerValue`.

To me the definition of `resolveServerValue` seems entirely broken as it iterates over keys of an arbitrary JSON object, which is why it wont resolve a bare anonymous toplevel function correctly. I think `resolveServerValue` should be aware of the serialisation format and use that knowledge accordingly.

**Comment by ChefYeum** [comment]
Tested with the following example:

```
fun fOrdinary() {
  print("This is using ordinary function syntax")
}

var fAnon = fun() {
  print("This is using anonymous function syntax, and it doesn't really work.")
};

var fWrapped = Bar(fun(x) {
  print("This is when function value is wrapped inside a data constructor. Print argument int: " ^^ intToString(x))
});

fun mainPage(_) {
  page
   <#>
    <button l:onclick="{fOrdinary()}">Ordinary</button>
    <button l:onclick="{fAnon()}">Anon</button>
    <button l:onclick="{switch (fWrapped) { case Bar(f) -> f(42) } }">Wrapped</button>
   </#>
}

fun main() {
  addRoute("/", mainPage);
  servePages()
}

main()
```
