### ISSUE TITLE
Nontermination in queries due to recursive types

### ISSUE THREAD

**Issue by slindley** [links-lang/links#36]
The effect analysis used to determine whether something is convertible to a query fails to detect recursion that sneaks in via recursive types.  For example,

```
 sig f : mu a . ((a) -> b)
 fun f(x) {x(x)}

 query {f(f)}
```

is accepted and loops for ever.

**Comment by slindley** [comment]
I suspect that this is not a serious issue in practice. It seems unlikely for this to happen by accident.

If we wanted to be more careful, then one possible solution would be to associate a special `negative` effect with negative recursive types and disallow the `negative` effect inside queries. This could get messy.

(I believe that non-recursive terms that use only strictly-positive equi-recursive types are guaranteed to terminate, though it might take some care to verify this for the particular combination of features that Links queries support.)

**Comment by jamescheney** [comment]
This is tagged "wontfix" so I think we should close it.
