### ISSUE TITLE
Relational lenses

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#374]
As discussed a few meetings ago, we want to incorporate @rudihorn's implementation of relational lenses into the master branch for 0.8, guarded by a flag since we aren't entirely happy with the syntax/language embedding strategy yet.

**Comment by jamescheney** [comment]
This is addressed partially by #385 but before closing this we (i.e. @rudihorn) should also document the extension in a wiki page

**Comment by jamescheney** [comment]
This still needs documented.  Not urgent but would be good to do soon in case anyone wants to try it out after the talk.

**Comment by rudihorn** [comment]
I've put together a small though probably not complete description: https://github.com/links-lang/links/wiki/Relational-Lenses.

**Comment by jamescheney** [comment]
Looks good to me (I changed `links` to `linx`). I'd still like to make a more closed-form tutorial example - perhaps for links-tutorials.  But this can be closed.
