### ISSUE TITLE
Closure Conversion does not respect free type variables in hoisted functions

### ISSUE THREAD

**Issue by frank-emrich** [links-lang/links#384]
I had a look at the current closure conversion code and ran across a problem. Consider the following function

```
sig outer : ((a) {}~> a, [a]) {}~> [a]
fun outer(f, l) {
	fun twice (y){
		f(f(y))
	}
	map(twice,l)
}
```
which evokes that twice has type (a) {}~> a, where a refers to the type variable outer is quantified over (in particular, twice is monomorphic).
Our current implementation of closure conversion will hoist twice to the toplevel, as it should. However, it does not respect free type variables. What *should* happen is that when hoisting the function twice, it is made polymorphic, obtaining some type forall b. (b) {wild}-> b for twice. When calling twice from outer (after hoisting), we would then have to generate a type application that instantiates b as a.

For reference, the current result of closure conversion looks as follows. In particular, twice has type ((8264) {}~> 8264, where 8264 is an unbound type variable.

```
[`Fun (((2069, ((8264) {}~> 8264, "twice", `Global)),
         ([], [(2068, (8264, "", `Local))],
          ([`Let (((2066, (8264, "y", `Local)),
                   ([], `Return (`Variable (2068)))));
             `Let (((2067, (8264, "", `Local)),
                    ([],
                     `Apply ((`Project (("2065", `Variable (2073))),
                              [`Variable (2066)])))))
             ],
           `Apply ((`Project (("2065", `Variable (2073))), [`Variable (2067)])))),
         (Some (2073, ((2065:(8264) {}~> 8264), "env_2069", `Local))),
         `Unknown));
   `Fun (((2072,
           (forall 8280.((8280) {}~> 8280, [8280]) {}~> [8280], "outer",
            `Global)),
          ([8264],
           [(2070, ((8264) {}~> 8264, "", `Local));
             (2071, ([8264], "", `Local))],
           ([`Let (((2064, ([8264], "l", `Local)),
                    ([], `Return (`Variable (2071)))));
              `Let (((2065, ((8264) {}~> 8264, "f", `Local)),
                     ([], `Return (`Variable (2070)))))
              ],
            `Apply ((`TApp ((`TAbs (([8274; 8275; 8276],
                                     `TApp ((`Variable (285),
                                             [8274; { |8275 }; 8276])))),
                             [8264; { |wild }; 8264])),
                     [`Closure ((2069,
                                 `Extend (({2065 => `Variable (2065); }, None))));
                       `Variable (2064)])))),
          None, `Unknown))
   ]
```

**Comment by slindley** [comment]
Good point. Before closure conversion `twice` must have a monomorphic type because the type variable `a` is in the type environment. The correct behaviour is to generalise as part of hoisting. Of course this means that any applications of the generalised function must also be augmented with appropriate type applications as well.

It's tempting to think that one might simply generalise all free type variables, but that approach can be broken by the value restriction. The correct implementation should generalise exactly the type variables that go out of scope as a result of hoisting.
