### ISSUE TITLE
Make travis work again

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#387]
It stopped working (or at least being visible in PRs), possibly because I did something wrong when enabling new travis for TryLinks (which I think we then wound up not really using but I digress).

**Comment by fehrenbach** [comment]
When I last looked into this, they were slowly migrating open source repositories from travis-ci.org to travis-ci.com while moving from github whatever to github apps, but there was no option to move immediately. Now they say if we don't want build history, we can send them an email and get it moved immediately. (It's not at all certain that this would fix things, but it might.)

https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg

**Comment by SimonJF** [comment]
It was just a dodgy permissions problem. PRs are going through Travis again, so this can be closed.
