### ISSUE TITLE
Move away from multiple `.opam` files.

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#398]
This is at odds with the usual `dune-release` workflow, and battling it continues to be a considerable source of pain every release.

**Comment by dhil** [comment]
It is not really possible if we want to Links to be modular, unless we are willing to have separate repositories. Is there a particular reason why you want to use `dune-release` over `topkg`?

I suppose you can open an issue/feature request for `dune-release` to have better support for multiple opam files.

**Comment by SimonJF** [comment]
`dune-release` is a Dune wrapper for `topkg`, superseding the old `topkg-jbuilder`. From what I could tell, anything other than `dune-release` is unsupported these days.

Regarding modularity, we only have the postgresql package at the moment. Multiple `.opam`s are a headache (as I've already encountered in trying to do this release, given the new `links-unit.opam`).

**Comment by dhil** [comment]
Arguably `links-unit` shouldn't be a opam package.

**Comment by SimonJF** [comment]
OK. In that case, why not put them in different repositories?

**Comment by dhil** [comment]
Well, it breaks locality. It is convenient that the source code and all "official" plugins are located together. Moreover, other projects are using multiple OPAM files in a single repository too, for example one of our core dependencies `cohttp`.

**Comment by SimonJF** [comment]
Point taken, but just because other projects do this doesn't mean we should as well. Getting multiple `opam` packages working (and in this case, multiple `opam` packages where the release `tbz` is the same!)

The release process is increasingly fragile because we're deviating from the expected workflow. I think this is something we should at least look at in more depth, to see if we can arrive at a better solution.

**Comment by dhil** [comment]
>  [..] just because other projects do this doesn't mean we should as well.
No, but maybe we should copy their release workflow.

> The release process is increasingly fragile because we're deviating from the expected workflow.
I am inclined to be believe the process is fragile because we are doing it wrong.

It may be worthwhile to write a script to automate the release process using the standard `topkg` rather than any of the helper packages such as `dune-release`.

**Comment by jamescheney** [comment]
There seem to be some potentially related dune issues already, which seem to be on the "Dune Coq roadmap":

https://github.com/ocaml/dune/issues/1112
https://github.com/ocaml/dune/issues/1190
https://github.com/coq/coq/issues/8052

Do the proposed solutions on the above Dune issues bear on our problems?

**Comment by jstolarek** [comment]
>  It is convenient that the source code and all "official" plugins are located together.

It sounds like we might need git submodules. Submodules would allow to put database drivers into their separate repositories and at the same time place them within the main source tree.

**Comment by omeid** [comment]
> It is convenient that the source code and all "official" plugins are located together.

It is certainly convenient in many ways,  but once you start having issues around various packages, the issue management alone becomes a pain, that is before you have contributors who are interested to maintain specific drivers or modules but don't need or want access to the whole project.

**Comment by SimonJF** [comment]
Our release pipeline is fine for now; closing.
