### ISSUE TITLE
Type equality for the Lens type is not implemented

### ISSUE THREAD

**Issue by frank-emrich** [links-lang/links#399]
I just saw that eq_types in unify.ml does the following:
```| `Lens _ -> true```
This means that the Lens type is equal to any other type. I assume this is an oversight of @rudihorn ?

**Comment by jamescheney** [comment]
Presumably it would be straightforward to implement by checking each corresponding argument is equal, but it might be better to allow equality-up-to-equivalence of functional dependency sets.  This is the kind of thing that makes me think it would be good to have a writeup of the Links core language extended with lenses...

**Comment by rudihorn** [comment]
Yes this needs to be implemented, I can try doing this at some stage.

**Comment by jamescheney** [comment]
This seems to have been fixed by #454, is that right @rudihorn ?
