### ISSUE TITLE
Better errors for lenses?

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#420]
In `lens/lensTypes.ml` we have:

```
let var_name (var : phrase) =
    match var.node with
    | `Var name -> name
    | _ -> failwith "Expected a `Var type"
```
@rudihorn, would it make sense to report source position in the error message? It is stored as part of a `phrase`.

(On a master branch this code is slightly different, but position information is also available.)

**Comment by jamescheney** [comment]
Special case of #525

**Comment by jamescheney** [comment]
We discussed this on Wednesday and I think we agreed it can be closed. @rudihorn ?

**Comment by rudihorn** [comment]
Yes this can be closed.
