### ISSUE TITLE
Cleaner source code with smart constructors

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#421]
Source code is full of abominations in the likes of:

```OCaml
let x = Utility.gensym ~prefix:"xml" () in
  with_pos (`FnAppl
  (with_pos (`TAppl (with_pos (`Var "plugP") pos, [`Row (o#lookup_effects)])) pos,
   [with_pos (`FunLit
               (Some ([Types.make_tuple_type [Types.xml_type], o#lookup_effects]),
                `Unl,
                ([[with_pos (`Variable (make_binder x Types.xml_type pos)) pos]],
                 with_pos (`Xml (name, attrs, dynattrs,
                                 [with_pos (`Block ([], with_pos (`Var x) pos)) pos])) pos), `Unknown)) pos;
    desugar_nodes pos children])) pos

```
These are especially common in `desugar*` modules and in the parser. GHC avoids this kind of clutter by using smart constructors, e.g.

```Haskell
mkFamDecl :: SrcSpan
          -> FamilyInfo RdrName
          -> LHsType RdrName                   -- LHS
          -> Located (FamilyResultSig RdrName) -- Optional result signature
          -> Maybe (LInjectivityAnn RdrName)   -- Injectivity annotation
          -> P (LTyClDecl RdrName)
mkFamDecl loc info lhs ksig injAnn
  = do { (tc, tparams, fixity, ann) <- checkTyClHdr False lhs
       ; mapM_ (\a -> a loc) ann -- Add any API Annotations to the top SrcSpan
       ; tyvars <- checkTyVarsP (ppr info) equals_or_where tc tparams
       ; return (L loc (FamDecl (FamilyDecl{ fdInfo      = info, fdLName = tc
                                           , fdTyVars    = tyvars
                                           , fdFixity    = fixity
                                           , fdResultSig = ksig
                                           , fdInjectivityAnn = injAnn }))) }
  where
    equals_or_where = case info of
```
and then the parser simply calls `(mkFamDecl (comb3 $1 $3 $4) DataFamily $3 (snd $ unLoc $4) Nothing)`. Perhaps we could make our code cleaner by following the same pattern?

**Comment by jamescheney** [comment]
Maybe I'm missing something about how the Haskell code snippet works, but I'm not sure it's doing hte same thing.  In the Links/OCaml example we seem to be broadcasting the same position to several constructors (presumably, so that any later errors including newly generated constructors are easier to debug because we can relate them to the location in the source that somehow "caused" them.)  

I don't see how the Haskell version is doing this; it seems like the "smart constructors" are wrapped in another constructor L that contains a single location (which presumably applies to the lower nodes).  This seems like a different design, where we'd have a separate constructor for locations and therefore we could choose where to "hang" the location in the result.  This also seems to have strengths and weaknesses - once we start desugaring it is nice not to have to keep annotations on every node, but it also for example allows nodes with multiple annotations (which might or might not make sense) or none when we are expecting at least one.

But since I don't know how L, FamDecl, and so on are defined maybe I'm missing something.

**Comment by jstolarek** [comment]
> In the Links/OCaml example we seem to be broadcasting the same position to several constructors

I think this is not really relevant here. The main point of my suggestion is that instead of repeatedly constructing fragments of an AST that have identical structure but different leaves, we could do it with functions. That would make source code shorter and thus hopefully easier to read.
 
> (presumably, so that any later errors including newly generated constructors are easier to debug because we can relate them to the location in the source that somehow "caused" them.)

I think we are assigning the same position to several constructors because currently we can't do better. A position, as defined in OCaml's Lexing module, contains file name, line number, and two offsets that allow to identify character offset within a line. Assigning position of a whole production to results of several sub-productions will lead to at least incorrect offsets within a line; if a production spans several lines we might report incorrect lines as well. I mentioned this in discussion of migration to Menhir: https://github.com/links-lang/links/issues/411#issuecomment-438246200

As for the Haskell snippet, `L` is a data constructor of data type `Located`, which is identical to `with_pos` that I am working on in #418/#419. The naming convention is that if a data type is prefixed with "L" then it is located. For example `LHsType RdrName` is `HsType RdrName` wrapped inside `Located`, i.e. it has attached source location. So all values coming into `mkFamDecl` already contain source locations. Also, notice how GHC's parser calls `(comb3 $1 $3 $4)` to combine source locations for three sub-productions to produce a single location for the whole production.

In general, GHC's parsing rules are more involved because of [ApiAnnotations](https://ghc.haskell.org/trac/ghc/wiki/ApiAnnotations). These annotations allow to reconstruct layout of a source file and are intended as an API for various IDE tools like autoformatters. These annotations are stored in a separate tree produced by the parser. HTH.

**Comment by jamescheney** [comment]
Yes, that makes sense, I guess what you are suggesting is to abstract out the common patterns of constructor-gunk that we are using, not to adopt the Haskell style wholesale, which seems totally reasonable.

**Comment by jstolarek** [comment]
I'd like to start working on this. I'm planning to begin with the parser because I see a couple of possible wins there. Once the parser is done I'd like to move to `desugar*` modules to see whether they can be cleaned up a bit. The question is: will this interfere with something anyone else is working on? Are there any desugar modules that I shouldn't touch just yet because they are being worked on currently?

**Comment by dhil** [comment]
> Are there any desugar modules that I shouldn't touch just yet because they are being worked on currently?

I'm working on `refineBindings.ml` and `desugarDatatypes.ml`, if you beat me to it, then I don't mind rebasing my work.
