### ISSUE TITLE
Trying to produce an error message for malformed XML raises an exception

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#424]
Say I want to parse a malformed piece of XML `<a></b>`. I expect to get an error message `Closing tag 'b' does not match start tag 'a'` raised by `ensure_match` in `parser.mly`. What I get instead is a `NotFound` exception raised from the code that handles `ConcreteSyntaxError` exception that was raised by `ensure_match`:

```
Raised at file "core/notfound.ml", line 20, characters 4-159
Called from file "core/sourceCode.ml", line 59, characters 34-77
Called from file "core/parse.ml", line 47, characters 26-40
(...)
*** Error: Notfound.NotFound("<non-string> (in Hashtbl.find)")')
```

The culprit is this line of code in `parse.ml`:

```
let _, column = code#find_line finish in
```
`find_line` is defined in `sourceCode.ml`:
```
  method find_line (pos : Lexing.position) : (string * int) =
    (self#extract_line pos.Lexing.pos_lnum,
     abs @@ pos.Lexing.pos_cnum - Hashtbl.find lines (pos.Lexing.pos_lnum -1) - 1)
```
The call to `Hastbl.find` is raising the `NotFound` exception.

**Comment by dhil** [comment]
Just to clarify. The `NotFound` exception is defined in `notfound.ml`. It is a slightly more informative version of the `Not_found` exception from the OCaml standard library. The `Hashtbl` module (also defined in `notfound.ml`) is an overloaded version of the `Hashtbl` module from the OCaml standard library.

Do you happen to have an example to reproduce this bug? For the following program `unmatched.links` I get the intended error message:
```links
$ echo "<a></b>" > unmatched.links
$ ./links unmatched.links
*** Parse error: unmatched.links:1
Closing tag 'b' does not match start tag 'a'.
  <a></b>
         ^
```
There might be an off by one error as the pointer/caret `^` points past the last `>`.

**Comment by dhil** [comment]
Aha! I suppose that's because those tests are evaluated using the `-e` option. It sets up the compilation pipeline differently.

**Comment by jamescheney** [comment]
As of now, all three of the following produce the correct error message:

- entering `<a></b>` in REPL
- `linx -e "<a></b>"`
- adding the above test to `xml.tests` (with an appropriate regexp to match the multi-line error message) and running all tests

Is there any other manifestation of the bug this issue is about, or can we close?

**Comment by jstolarek** [comment]
Looks good. Test added in 90003c3a. Closing.
