### ISSUE TITLE
Improve Links grammar

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#426]
This is a follow-up to #411:

> Some of the production rules such as preamble are essentially garbage. We should get rid of rules like those. In general we should probably simplify/refactor our grammar. (...) Menhir provides some convenient combinators that enable us to get rid of most (if not all) of the _list and _perhaps productions.

Another thing to consider is what positions to attach to nodes that don't correspond directly to source code tokens. For example, here `Unit` is annotated with a dummy position:

```
hear_arrow_prefix:
| LBRACE COLON datatype COMMA efields RBRACE
   { row_with ("wild", `Present (with_dummy_pos `Unit))
              (row_with ("hear", `Present $3) $5) }
```
but other productions assign a position corresponding to a whole production:
```
field:
| field_label   { $1, `Present (with_pos $loc `Unit) }
```
We should decide on a consistent approach and follow it.

**Comment by jstolarek** [comment]
I wonder how others feel about refactoring these two productions:

```
| LPAREN labeled_patterns VBAR pattern RPAREN { with_pos $loc (`Record ($2, Some $4)) }
| LPAREN labeled_patterns RPAREN              { with_pos $loc (`Record ($2, None   )) }
```
into:
```
| LPAREN labeled_patterns preceded(VBAR, pattern)? RPAREN   { with_pos $loc (`Record ($2, $3)) }
```
The latter one shorter and fancier but I'm not sure whether it is easier to understand and, as such, whether it is a good refactoring.

Another thought is that to fully refactor the grammar we also need to change our internal representations. For example:

```
parenthesized_pattern:
| LPAREN RPAREN                        { with_pos $loc (`Tuple []) }
| LPAREN pattern RPAREN                { $2 }
| LPAREN pattern COMMA patterns RPAREN { with_pos $loc (`Tuple ($2 :: $4)) }
```
So parenthesized patterns are internally represented as a `Tuple`, unless it's just one pattern, in which case internal representation is something completely different. If we had a uniform internal representation, e.g. by allowing `Tuple`s with one component, we could have a single production instead of three. But I'll leave this as future work - for now I only plan to focus on refactoring that can be done without touching the AST and further stages of the compilation pipeline.

**Comment by jstolarek** [comment]
The refactoring is going well but I am sometimes running into problems I don't understand. I'm not sure whether this is me not understanding how parsing works or some peculiarity of Menhir (I'm suspecting the former). Consider these two productions:

```
| INSERT exp VALUES LBRACKET LPAREN RPAREN RBRACKET RETURNING VARIABLE
  { with_pos $loc (`DBInsert ($2, [],
    with_pos $loc (`ListLit ([with_pos $loc (`RecordLit ([], None))], None)),
    Some (with_pos $loc($9) (`Constant (`String $9))))) }
| INSERT exp VALUES LBRACKET LPAREN labeled_exps RPAREN RBRACKET RETURNING VARIABLE
  { with_pos $loc (`DBInsert ($2, labels $6,
    with_pos $loc($6) (`ListLit ([with_pos $loc($6) (`RecordLit ($6, None))], None)),
    Some (with_pos $loc (`Constant (`String $10))))) }
```

where `labeled_exps` is defined as a non-empty list:

```
labeled_exps:
| separated_nonempty_list(COMMA, separated_pair(record_label, EQ, exp))  { $1 }
```

But if we allowed `labeled_exps` to span over empty lists in the second production then it would subsume the first one:

```
perhaps_labeled_exps:
| separated_list(COMMA,
    separated_pair(record_label, EQ, exp))                     { $1 }

| INSERT exp VALUES LBRACKET LPAREN perhaps_labeled_exps RPAREN RBRACKET RETURNING VARIABLE
  { with_pos $loc (`DBInsert ($2, labels $6,
    with_pos $loc($6) (`ListLit ([with_pos $loc($6) (`RecordLit ($6, None))], None)),
    Some (with_pos $loc (`Constant (`String $10))))) }
```

This however leads to a conflict with an earlier production:

```
| INSERT exp VALUES LBRACKET LPAREN labeled_exps RPAREN RBRACKET  { ... }
```

Menhir reports a reduce/reduce conflict on `RPAREN` symbol. I don't understand why is it OK to have two separate productions that essentially say the same thing, but collapsing them into one production leads to problems.

Here are more details of what Menhir says (note: `loption(separated_nonempty_list(c, xs))` is how Menhir internally implements `separated_list(c, xs)`):

> ** Conflict (reduce/reduce) in state 823.
> ** Token involved: RPAREN
> ** This state is reached from file after reading:
>
> INSERT exp VALUES LBRACKET LPAREN separated_nonempty_list(COMMA,separated_pair(record_label,EQ,exp))
>
> ** The derivations that appear below have the following common factor:
> ** (The question mark symbol (?) represents the spot where the derivations begin to differ.)
>
> file
> exp END
> lens_expression
> database_expression
> (?)
>
> ** In state 823, looking ahead at RPAREN, reducing production
> ** labeled_exps -> separated_nonempty_list(COMMA,separated_pair(record_label,EQ,exp))
> ** is permitted because of the following sub-derivation:
>
> INSERT exp VALUES LBRACKET LPAREN labeled_exps RPAREN RBRACKET // lookahead token appears
>                                   separated_nonempty_list(COMMA,separated_pair(record_label,EQ,exp)) .
>
> ** In state 823, looking ahead at RPAREN, reducing production
> ** loption(separated_nonempty_list(COMMA,separated_pair(record_label,EQ,exp))) ->
> separated_nonempty_list(COMMA,separated_pair(record_label,EQ,exp))
> ** is permitted because of the following sub-derivation:
>
> INSERT exp VALUES LBRACKET LPAREN perhaps_labeled_exps RPAREN RBRACKET RETURNING VARIABLE // lookahead token appears
>                                   loption(separated_nonempty_list(COMMA,separated_pair(record_label,EQ,exp))) // lookahead token is inherited
>                                   separated_nonempty_list(COMMA,separated_pair(record_label,EQ,exp)) .

**Comment by jamescheney** [comment]
I don't think this is Menhir-specific; I think (ocaml)yacc would do the same thing.  The problem is that LR(1) has one symbol of lookahead so if you combine the two rules for INSERT...VALUES...RETURNING then that means the parser has to decide too early between reducing using the INSERT...VALUES rule (which doesn't allow empty expression lists?) and the INSERT...VALUES...RETURNING rule (which does).  One solution could be to allow empty lists in both (maybe collapsing all three cases into one rule) and check later to treat `insert t values [()]` without `returning x` as a (type) error.  (Or just ignore it?)

**Comment by jstolarek** [comment]
Ah, I see it now. Thanks. I think I'm more used to working with recursive-descent parser that would just backtrack in such case.
