### ISSUE TITLE
Serialization for lenses is not implemented

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#436]
It would be good to have this (maybe just using storing on server and using handles for them on client)  since otherwise declaring a lens at the toplevel and then using it (even in a server-only function) fails with a "lens not serializable" error.

**Comment by jamescheney** [comment]
This is still unresolved.  Here is a minimalistic example based on `01_cds.links`, illustrating that this happens even if the lenses aren't explicitly passed to the client (but are in scope of a closure that is):

```
var db = database "links";

var albumsTable =
    table "albums"
    with (album: String, quantity: Int)
    tablekeys [["album"]]
    from db;

var tracksTable =
    table "tracks"
    with (track: String, date: Int, rating: Int, album: String)
    tablekeys [["track", "album"]]
    from db;

var albumsLens = lens albumsTable with { album -> quantity };
var tracksLens = lens tracksTable with { track -> date rating };

var joinedLens = lensjoin albumsLens with tracksLens on album delete_left;
var droppedLens = lensdrop date determined by track default 2018 from joinedLens;
var filteredLens = lensselect from droppedLens by fun (x) { x.quantity > 2 };

fun mainPage (_) {
  page
    <html>
    <body>
    <h1>Hello world!</h1>
    </body>
    </html>
}


fun main () {
  addRoute("",mainPage);
  servePages()
}

main()
```
Visiting the resultign page yields `Links error: ***: Runtime error: relational lens serialization not supported`.

@rudihorn fixing this would be helpful for making small/tutorial Web examples using relational lenses in Links.  Could you take a look?

**Comment by rudihorn** [comment]
I'll probably try hacking up a quick lens to s-expression serialization and then deserialization as I'm not sure how well handles would work. I think longterm the concept of continuation compression should probably bo looked into though, as it looks like we're still compressing the database connection string.
