### ISSUE TITLE
Type syntax and inference for lenses

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#438]
Type inference doesn't appear to work for lenses; i.e. if we write something like

```
fun remove(l,x,view) {
   var newView = for (y <- view) where (x <> y) [y];
   lensput l with newView;
   mainPage(args)
}
```

then I get an error
```
*** Fatal error : Type is not a lens (LensType.sort).
```
which I suspect means that somewhere we are checking whether a free type variable assigned to `l` equals `Lens(_)` and failing.

Moreover, trying to fix this by ascribing a lens type to `l` doesn't work either:
```
sig remove : (Lens(r),(r),[(r)]) ~> ()
fun remove(l,x,view) {
```

because (going by what is in `parser.mly`) there is no surface language syntax for lenses.

**Comment by jamescheney** [comment]
We discussed this on Wednesday and I think this is either done, or close.  @rudihorn ?

**Comment by rudihorn** [comment]
This can also be closed.
