### ISSUE TITLE
Cleanup block_contents and binding productions in the parser

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#441]
In the parser there's a group of productions that look fishy (slightly reformatted and reordered here):

```
block_contents:
| bindings exp SEMICOLON               { ($1 @ [with_pos $loc($2) (`Exp $2)],
                                          with_pos $loc (`RecordLit ([], None))) }
| bindings exp                         { ($1, $2) }
| exp SEMICOLON                        { ([with_pos $loc($1) (`Exp $1)],
                                          with_pos $loc (`RecordLit ([], None))) }
| exp                                  { ([], $1) }
| SEMICOLON | /* empty */              { ([], with_pos $loc (`TupleLit [])) }

bindings:
| binding                              { [$1]      }
| bindings binding                     { $1 @ [$2] }

binding:
| VAR pattern EQ exp SEMICOLON         { with_pos $loc (`Val ($2, ([], $4), `Unknown, None)) }
| exp SEMICOLON                        { with_pos $loc (`Exp $1) }
| signature FUN var arg_lists block    { annotate $loc($1) $1 $loc
                                          (`Fun ($3, `Unl, ($4, with_pos $loc($5) (`Block $5)), `Unknown)) }
| signature LINFUN var arg_lists block { annotate $loc($1) $1 $loc
                                          (`Fun ($3, `Lin, ($4, with_pos $loc($5) (`Block $5)), `Unknown)) }
| FUN var arg_lists block              { with_pos $loc (`Fun (make_untyped_binder $2,
                                                          `Unl, ([], ($3, with_pos $loc($4) (`Block $4))), `Unknown,
                                                          None)) }
| LINFUN var arg_lists block           { with_pos $loc (`Fun (make_untyped_binder $2,
                                                          `Lin, ([], ($3, with_pos $loc($4) (`Block $4))), `Unknown,
                                                          None)) }
| typed_handler_binding                { with_pos $loc (`Handler $1) }
| typedecl SEMICOLON | links_module
| alien_block | links_open { $1 }
```

We could in theory define `bindings` production using Menhir combinators:

```
bindings:
| binding+  { $1 }
```

but that gets us into a shift/reduce conflict as explained here https://github.com/links-lang/links/pull/434#issuecomment-445784429.  TL;DR: a `binding` production has this rule:

```
| exp SEMICOLON  { with_pos $loc (`Exp $1) }
```
  
which leads to a conflict because if parser sees an `exp` it doesn't know whether to reduce in `block_context` or shift in `bindings`.  So the fact that `exp SEMICOLON` is a rule in both `block_contents` and `binding` looks suspicious, given how the two productions are combined.

Moreover, these two rules in `block_contents` production look strange:

```
| bindings exp SEMICOLON  { ($1 @ [with_pos $loc($2) (`Exp $2)],
                             with_pos $loc (`RecordLit ([], None))) }
| bindings exp            { ($1, $2) }
```

Why does a semicolon make such a big difference in what is being returned by the rules?  Similarly for the pair of rules:

```
| exp SEMICOLON  { ([with_pos $loc($1) (`Exp $1)],
                    with_pos $loc (`RecordLit ([], None))) }
| exp            { ([], $1) }
```

P.S. what is the difference in semantics of our `question` and `confusion` github ticket labels?  I am guessing `question` is a question directed to other developers, whereas `confusion` means a potential confusion of Links user. Correct me if I'm wrong.

**Comment by dhil** [comment]
If we decide to clean up the (main) parser, then I will think it is worth considering modernising the surface syntax of Links at the same time.

**Comment by jamescheney** [comment]
I've had various idle conversations (so far mostly with Frank) about how we might accommodate user-definable syntax extensions a la "reasonably programmable literal notation" (ICFP 2018), though this is not necessarily something that has to be part of Links.  If there are other things people want to fix we should probably start an issue or wiki page to collect requirements for a new syntax.

**Comment by jamescheney** [comment]
@jstolarek: maybe @slindley knows better, but I think the answer to why we have the with/without semicolon productions is to accommodate writing "C-style" sequences of semicolon-separated "statements" (expressions of type `()`).  When the last element of such a sequence is an expression, if we want to return it then we can leave off the semicolon (like in ML) and the expression's value is the result of the "statement".  When we don't want to return its value then parsing the terminal semicolon with nothing after it causes an empty-tuple expression (`()`) to be inserted as the result value.  This saves us from having to write things like:

```
foo();
bar();
()
```
instead of
``
foo();
bar();
```
when `bar()` returns something other than unit.  That said, I'm not sure this convenience is worth the extra parser complexity; do we have a lot of example programs that use this abbreviation?
