### ISSUE TITLE
Examples no longer work

### ISSUE THREAD

**Issue by slindley** [links-lang/links#444]
Commit 4d6d594 (27th September 2018) breaks the examples. For instance, attempting to run the draggable lists example yields: `Assert_failure core/evalir.ml:249:18`.

Every time code is merged into the master branch the standard web examples should be manually tested. Clearly this is not happening!

**Comment by frank-emrich** [comment]
Sorry, I usually test at least some of the examples and must have overlooked the broken ones. Fixed in ee3b32a3aa8d67422abe175e8c8b81c4bf774f66

**Comment by slindley** [comment]
Excellent!

It's certainly not just you who missed the manual tests. Everyone else who checked something in after 27th September (including me) also failed to do so.

Ultimately it would be nice to have a headless web testing framework (#155), but in the meantime we should all try to be more diligent in running the manual tests before pushing to the trunk.
