### ISSUE TITLE
Cannot use variant containing linear polymorphic function

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#445]
Say I have the following variant type, parameterised over some type `a`.

```
typename LinData(a) = [| Apply : () {}~> a | ApplyLinear : () {}~@ a |];
```

Now, say I write the following function taking arguments `dat` of type `LinData(a)`, and access point `ap` of type `AP(?a.End)`. (An access point allows you to establish a session). 

```
sig go : forall a :: Type(Any, Any) . (LinData(a), AP(?a.End)) {}~> () 
fun go(dat, ap) {
  switch(dat) {
    case Apply(f) ->
      var toSend = f();
      var _ = send(toSend, request(ap));
      ()
    case ApplyLinear(f) ->
      var toSend = f();
      var _ = send(toSend, request(ap));
      ()
  }
}
```

However, trying to evaluate this function gives rise to the following error:
```
lindtTest.links:9: Type error: The type of an input to a switch should match the type of its patterns, but the expression
    `dat'
has type
    `LinData (8981::Any)'
while the patterns have type
    `[|Apply:() {}~> 8981::Any|ApplyLinear:() {}~> 8981::Any|]'
In expression: switch(dat) {
    case Apply(f) ->
      var toSend = f();
      var _ = send(toSend, request(ap));
      ()
    case ApplyLinear(f) ->
      var toSend = f();
      var _ = send(toSend, request(ap));
      ()
  }.
```

The type of `f` in the second branch is inferred as `() {}~> 8981::Any`, which cannot be unified with linear function `() {}~@ a`. Thus, we cannot match the declared type.

OK, so that's probably due to the (necessary) incompleteness of inferring whether a function is linear or unrestricted. So let's give it a type annotation:

```
sig go : forall a :: Type(Any, Any) .
  (LinData(a), AP(?a.End)) {}~> () 
fun go(dat, ap) {
  switch(dat) {
    case Apply(f) ->
      var toSend = f();
      var _ = send(toSend, request(ap));
      ()
    case ApplyLinear((f: (() {}~@ a))) ->
      var toSend = f();
      var _ = send(toSend, request(ap));
      ()
  }
}
```
Unfortunately though, this is not the "same" `a` that is universally quantified in the function signature:

```
Unification error: Rigid type variables 8976 and 8982 do not match
lindtTest.links:17: Type error: The function
    `send'
has type
    `(8976::Any, !(8976::Any).9003::Session) ~9001~> 9003::Session'
while the arguments passed to it have types
    `8976::Any'
and
    `~?(8982::Any).End'
and the currently allowed effects are
    `|wild'
In expression: send(toSend, request(ap)).
```

Any idea how to proceed?

**Comment by SimonJF** [comment]
Thanks. Yes, I spotted the unit mistake this morning (and edited the issue accordingly), but you're right that it doesn't make a difference to the problem at hand.

You're also right that dropping the explicit kind annotation on `a` results in this example working. 

However this is problematic in my (larger) setting as without the explicit kind annotation, `a` ends up being treated as an unrestricted type variable, which leads to a unification error along the line. I'll work on a MFE of this, too.

**Comment by dhil** [comment]
It seems that you can refactor the example to work as follows:
```
typename LinData(a) = [|Apply:() {}~> a|ApplyLinear:() {}~@ a|];
sig unlimited : forall a :: Type(Any, Any) . (() {}~> a, AP(?a.End)) {}~> ()
fun unlimited(f, ap) {
  var toSend = f();
  var _ = send(toSend, request(ap));
  ()
}

sig linear : forall a :: Type(Any, Any) . (() {}~@ a, AP(?a.End)) {}~> ()
fun linear(f, ap) {
  var toSend = f();
  var _ = send(toSend, request(ap));
  ()
}

sig go : forall a :: Type(Any, Any) . (LinData(a), AP(?a.End)) {}~> ()
fun go(data, ap) {
  switch (data) {
    case Apply(f) -> unlimited(f, ap)
    case ApplyLinear(f) -> linear(f, ap)
  }
}
```

**Comment by dhil** [comment]
The following also seem to work
```
sig applylinear : forall a :: Type(Any, Any) . (() {}~@ a) {}~> a
fun applylinear(f) { f() }

sig apply : forall a :: Type(Any, Any) . (() {}~> a) {}~> a
fun apply(f) { f() }

sig go : forall a :: Type(Any, Any) . (LinData(a), AP(?a.End)) {}~> ()
fun go(data, ap) {
  var toSend = switch (data) {
    case Apply(f) -> apply(f)
    case ApplyLinear(f) -> applylinear(f)
  };
  var _ = send(toSend, request(ap));
  ()
}
```

**Comment by slindley** [comment]
The default subkind is `(Unl, Any)` by design (see sugartypes.ml) - if in doubt the type system assumes that type variables are unlimited. This is a conscious choice based on the assumption that it is more likely to be annoying to unexpectedly break programs that do not use linearity than to unexpectedly break (more experimental) programs that do use linearity. Our subkinding system trades relative simplicity for not always being able to infer most general types because they do not always exist.

My preference nowadays would be for a more uniform system based on bidirectional typing, but that would be a far reaching change that we should probably steer clear of for now.

**Comment by jamescheney** [comment]
Can this be closed, since there is a workaround?

**Comment by SimonJF** [comment]
Yup, thanks for the help!
