### ISSUE TITLE
Session buffers are not garbage-collected

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#449]
Session endpoints of type `End` are unrestricted and may be discarded. However, there is currently no logic on either the server or the client for removing the empty buffers once the endpoints have been discarded.

With a `close` primitive and a linear `End` type, this would be straightforward -- simply delete the buffer.

The way to solve this without such a primitive is to delete the entry in the buffers table whenever it is empty, and create it whenever a message is received and it doesn't exist. However, presence of a buffer in the local endpoints table is currently used to indicate that a communication is local or remote, for distributed session-typed communication. Thus, it'll be necessary to track presence of an endpoint separately.

**Comment by SimonJF** [comment]
Thinking about it -- the mitigation I suggested would introduce the same problem: we have no way of removing an endpoint from the "it lives here" table!

The other "obvious" fix is to carry type information for session-typed endpoints around at runtime, but I doubt we want to do that.

**Comment by SimonJF** [comment]
I'm personally in favour of making `End` linear instead of unrestricted, and having a `close` primitive (which would be asynchronous, rather than rendezvous-based).

This will have some ripple on existing code but the changes will be straightforward.

Any objections?

**Comment by dhil** [comment]
> Any objections?

https://www.youtube.com/watch?v=ML86JjEyKiA, too intense?
