### ISSUE TITLE
Typenames can escape their scope

### ISSUE THREAD

**Issue by dhil** [links-lang/links#456]
Syntactically, it is possible to declare a typename in any binding context. Therefore it is possible to declare a typename in a local scope, and *that* typename can escape its scope!

Consider the following program.
```links
typename T = Bool;
fun f() {
  typename T = Int;
  0 : T
}

links> f();
0 : T
```
The invocation `f()` produces an integer value, whose type is `T`. But which `T`? Looking at the type constructor environment, it seems that `T = Bool`:
```
links> @tyconenv;
 T = Bool
```
If that is true, then `0 : T` would be ill-typed.

What has happened here, is that the local declaration of `T` within `f` has escaped its scope, and thereby gets conflated with the `T` in the outer scope.

I can think of a couple of potential solutions:

1. Only allow typename declarations in module contexts.
2. Unroll locally defined typenames in positive positions.
3. Disallow locally defined typenames in positive positions.

My preference is for 1, which I believe aligns with other functional programming languages such as `OCaml` and `Haskell`.

**Comment by dhil** [comment]
It seems to be a `+1/-1` change in `parser.mly` to implement the first solution.

**Comment by jamescheney** [comment]
Scala allows this...
```
scala> def foo() = {
     |   type T = Int
     |   0:T
     | }
foo: ()T
```
not that that is an endorsement.

**Comment by yallop** [comment]
Standard ML also allows local type names:

```sml
- fun f () = let type t = int in (0:t) end;
val f = fn : unit -> int
```

and even local data types:

```sml
- fun f () = let datatype t = T in T end;
val f = fn : unit -> ?.t
```

**Comment by slindley** [comment]
The SML / Scala approach (nested type definitions) is the one I find more aesthetically pleasing, but the Haskell approach (only top-level type definitions) is probably easier to implement naively.

I don't think it used to be possible previously to write type definitions nested in Links.

**Comment by frank-emrich** [comment]
Currently, the design for our module system is such that each file implicitly corresponds to a module, similar to OCaml. Allowing type-definitions at the top-level only would result in a divergence between what is allowed in top-level (i.e., file-level) modules and nested modules.

This is not necessarily a problem, as we may want that distinction anyways: We want files/top-level modules to be allowed to end with an expression, which seems odd for nested modules. @dhil also raised the issue that my current solution (turning the trailing `e` in a file into `var _ = e` when wrapping it into a module) has some consequences on the webserver/JS translation.
This discussion may deserve its own issue, I'm just saying that the decision here about where to allow type definitions affects the decision about whether or not we distinguish top-level modules from nested ones syntactically.

**Comment by dhil** [comment]
> The SML / Scala approach (nested type definitions) is the one I find more aesthetically pleasing, but the Haskell approach (only top-level type definitions) is probably easier to implement naively.

It seems SML unrolls transparent types, i.e. akin to my second proposal. As noted in my comment above, implementing the Haskell approach is a 1 line change.

**Comment by dhil** [comment]
> Standard ML also allows local type names:

According to the 1997 revised specification<sup>1</sup> (Appendix G.7, page 109), local type declarations are not permitted whereas they were in the 1990 specification. The specification provides the following example

> For example, the expression
> ```sml
> fn x => let datatype t = C
>            val _ = if true then x else C
>         in 5
>         end
> ````
> is not legal SML ’97, although it was legal SML ’90.

[1]: R. Milner, M. Tofte, R. Harper, and D. MacQueen, *The Definition of Standard ML (Revised)*,1997,  [pdf](http://sml-family.org/sml97-defn.pdf).

**Comment by yallop** [comment]
Local type declarations are permitted in SML'97, but the names of data types are not allowed to escape the scope.

The problem with the example you give from the appendix (and with my second example [above](https://github.com/links-lang/links/issues/456#issuecomment-453075945)) is that `t` appears in the type of the function, and can't be eliminated by resolving aliases.  Examples where `t` doesn't escape the scope (e.g. where the declaration is inside a function of type `int -> int` are allowed.
