### ISSUE TITLE
query.ml and queryshredding.ml misaligned?

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#458]
In commit a543381 which fixed #25, changes were made to query.ml.  At the time the query shredding code was in a parallel branch.  Later, it was merged in as a separate file queryshredding.ml, which does not have this change.  This may mean #25 was not fixed for shredding.  

- [ ] Add test that runs the test for bug  #25 with shredding enabled (and possibly all the other database tests?)
- [ ] Fix queryshredding if needed / resolve this by merging query.ml and queryshredding.ml (cf #431)

**Comment by wricciot** [comment]
My current code (largely importing QueryShredding into Query) does indeed fail on the xpath.links and xpath-reduced.links tests with error DbEvaluationError("Error projecting from record").

More importantly, if I turn on shredding on those examples, I get the following errors:

cmnd=./links --config=tests/database/config tests/database/xpath.links
*** Error: Links_core.Queryshredding.Eval.DbEvaluationError("Error projecting from record")
FAILED TEST xpath
cmnd=./links --config=tests/database/config tests/database/xpath-reduced.links
FAILED TEST xpath-reduced:[(name = "f"), (name = "e"), (name = "c")]but got:[(name = "c"), (name = "e"), (name = "f")]

While the second message should be benign (tuples are reordered by shredding, as expected), the first one appears to show that #25, indeed, was not fixed for shredding.
