### ISSUE TITLE
Attaching of dummy positions inside the pipeline not enforced correctly

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#460]
73e5892b51823d9207759d680ec9332b53e132fd introduced `SugarConstructors.Make` module that was intended to prevent attaching of positions to nodes inside the compiler pipeline (only the parser is allowed to do this). However, that works only if `SugarConstructors.Make` module is open. If a module opens `Sugartypes` directly it is still possible to attach positions to nodes (and there are many places in the code that do so). This should be fixed by moving `with_pos` function from `Sugartypes` to `SugarConstructors` (it isn't really used in that module).

**Comment by jstolarek** [comment]
`DesugarHandlers.desugar_handlers_early` does weird things with positions:

```OCaml
let desugar_handlers_early =
object
  inherit SugarTraversals.map as super
  method! phrasenode = function
    | `HandlerLit hnlit ->
       let (fnparams, body) = funlit_of_handlerlit hnlit in
       let funlit : Sugartypes.phrasenode = (fun_lit `Unl fnparams body).node in
       super#phrasenode funlit
    | e -> super#phrasenode e

  method! phrase {node; pos} =
    match node with
    | `Handle h ->
       let (val_cases, eff_cases) = split_handler_cases h.sh_effect_cases in
       with_dummy_pos (`Handle { h with sh_effect_cases = eff_cases;
                                        sh_value_cases  = val_cases })
    | _ -> super#phrase {node; pos}

  method! bindingnode = function
    | `Handler (binder, hnlit, annotation) ->
       let fnlit  = funlit_of_handlerlit hnlit in
       (fun_binding' ?annotation binder fnlit).node
    | b -> super#bindingnode b
end
```

  * `HandlerLit` is converted into a function literal and the position is kept. (Conversion itself introduces dummy positions into the body of a new literal.)
  * `Handle` has some of its arguments modified and the position is discarded. 
   * `Handler` binding is converted into a function binding, and again the position is kept.

Whatever we decide to do, it should be consistent.

**Comment by dhil** [comment]
I wouldn't pay attention to the `DesugarHandlers` module, it is practically dead code. I want to plan to get rid of it.

**Comment by jstolarek** [comment]
OK, in that case I'll leave it as is. I was planning on fixing positions handling in that module because it is generally too eager (my fault, I'm afraid).

**Comment by dhil** [comment]
The `handler` and `shallowhandler` keywords are syntactic sugar, for example
```
[|handler h { 
    case Return(x) -> M
    case Op(p,k) -> N
}|]
=
fun h(m) {
  handle(m()) {
    case Return(x) -> [|M|]
    case Op(p,k) -> [|N|]
}
```

This was convenient back when `handle` was restricted to work over  values (specifically suspended computations). That restriction no longer exists.

As an aside, I am planning to express everything "handler-related" with `do` and `handle`, so I'll get rid of the keyword `shallowhandle` too.
