### ISSUE TITLE
CI is not failing on warnings

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#477]
Warnings no longer cause the CI to fail.

**Comment by rudihorn** [comment]
I believe this is caused by the `make nc-release` in travis. I'm not sure if this was because of the issue with ppx deriving generating warnings because one of the packages was using a deprecated type.

**Comment by dhil** [comment]
Yes, the build rule looks broken. I think it needs to say:
```
$(BUILD) --only-packages links,links-postgresql @install --profile=release
```
and the release profile should be updated to say
```
 (release
  (flags (:standard -safe-string -dtypes -w @a-4-44-45-60 -cclib -lunix -thread)))
```

**Comment by jamescheney** [comment]
That's strange.  Warnings were definitely breaking CI last week, due to deprecation of `Yojson.Safe.json` which was why I added some warning masking (#471) as a temporary workaround.  But that should only have masked warning 33 in a few files, nothing else.
