### ISSUE TITLE
Shredding for SQLite

### ISSUE THREAD

**Issue by fehrenbach** [links-lang/links#486]
[SQLite has window functions now.](https://www.sqlite.org/releaselog/3_25_0.html) I haven't checked the [details](https://www.sqlite.org/windowfunctions.html), but this might be enough to support shredding.

**Comment by jamescheney** [comment]
[MySQL 8.0 also appears to have window functions](http://www.mysqltutorial.org/mysql-window-functions/).

If these are both SQL:1999 compatible then it "should" just be a matter of making sure a sufficiently recent MySQL or SQLite is installed.  (Famous last words)

**Comment by dhil** [comment]
Resolved by #492.
