### ISSUE TITLE
Kind context of type/row/etc. variables should be handled correctly/checked in desugaring

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#491]
This works:

```
typename PolyPingPong =
  [+|
    Go: forall a. !a.?a.PolyPingPong,
    Stop: EndQuery
  |+];
```
but this doesn't work:
```
typename PolyRowPingPong =
  [+|
    Go: forall a::Row. !(a).?(a).PolyRowPingPong,
    Stop: EndQuery
  |+];
```
it results in an error `*** Fatal error : Free variable (a) in definition of typename FPolyPingPong
`
I think that the second and third examples should both work or both not work (and if not, better error message).  

Also, the session types above are a red herring: the same kind of behavior using variants also works:
```
typename FPolyPingPong =
  [| Go: forall a. (a) {}-> (a,FPolyPingPong)
   | Stop: ()
  |];
```
but locally quantifying over a row variable does not work:
```
typename FPolyRowPingPong =
  [| Go: forall a::Row. ((a)) {}-> ((a),FPolyRowPingPong)
   | Stop: ()
  |];
```

**Comment by jamescheney** [comment]
Ah wait, but this works:

```
typename FPolyRowPingPong2 =
  [| Go: forall a. ((a)) {}-> ((a),FPolyRowPingPong2)
   | Stop: ()
  |];
```
because `a` is used as a `Type` above rather than a `Row` (the `(a)`s are treated as 1-tuples / ignored).  

This also works:
```
typename FPolyRowPingPong =
  [| Go: forall a::Row. ((|a)) {}-> ((|a),FPolyRowPingPong)
   | Stop: ()
  |];
```
because `a` is used in a place where a row variable is expected, which I forgot to do before.

So the problem is really that ill-kinded type variable occurrences are not handled correctly during datatype desugaring, leading to a very mysterious error message.  (When we see `a` in a place where we expect a `Type` but it was actually quantified as a `Row`, the error message just saying that `a` is unbound is misleading; it just wasn't bound in the context we were expecting to find it.)

I also wonder if the right thing happens in the presence of shadowing:
```
typename FPolyRowPingPong3 =
  [| Go: forall a:: Type. forall a::Row. ((|a)) {}-> ((a),FPolyRowPingPong3)
   | Stop: ()
  |];
```
Spoiler alert: the above is apparently just fine!

The error could be improved by reporting the kind we expected the variable to have and the kind it actually has.  Perhaps better would be to maintain a single kinding environment so that shadowing situations like the above are also handled correctly (i.e. we would reject the above because the inner binding of `a` doesn't match the expected use in the return type.)

**Comment by dhil** [comment]
I think the problem you have reported is not confined to session types, it applies to ordinary types too. We should really have syntactic sugar for writing bare row variables, as you intended above. Perhaps we should change the title of the issue to reflect this matter?

**Comment by jamescheney** [comment]
Yes, it is orthogonal to session types.

I could live with the existing syntax as long as the error message if you get it wrong was more enlightening (also potentially the problem with #526).

**Comment by jamescheney** [comment]
Though I'm not sure why (in #526) it's necessary to write `{|e}` instead of just `e`.  If the reason is that by default we currently treat all variables in types as having kind `Type` then I incline towards fixing this  for now by requiring kinds other than `Type` to be declared explicitly somewhere, but respecting these declarations instead of ignoring them.  In the future, some lightweight kind inference/synthesis would be preferable (e.g. to support higher kinds).

**Comment by dhil** [comment]
> Though I'm not sure why (in #526) it's necessary to write `{|e}` instead of just `e`.

Currently, we do not use kind information provided by the context. The `e` in `SComp(e, a)` is simply assumed to have kind `Type`, although, from the context it clearly has kind `Row`.

**Comment by jamescheney** [comment]
This is related to (but not the same as) #344

**Comment by dhil** [comment]
In the light of #631, I think we can close this issue. Please reopen if I am mistaken.
