### ISSUE TITLE
DOS style EOL in irCheck.ml/mli

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#493]
I just realized `irCheck.ml(i)` files are in DOS format. Conversion is trivial but from git perspective it amount to rewriting the whole file, so doing any merge on that file will be a disaster. Does anyone have any changes they plan to commit to this file in foreseeable future? If no then I would make the conversion along with my polymorphic variants patch.

**Comment by SimonJF** [comment]
Good spot. Perhaps we could make a CI test to check for this.

**Comment by jstolarek** [comment]
Yes, this is definitely something CI should check.

**Comment by jstolarek** [comment]
Thanks! But first I need to know no one is doing anything with that file - otherwise it'll be a mess. @dhil? @frank-emrich?

**Comment by dhil** [comment]
I suppose this is due to @frank-emrich using Windows. You probably want to get all files created by him.
```
$ git log --name-status --diff-filter=A --format='> %aN' | awk '/^>/ {tagline=$0}
       /^A\t/ {print tagline "\t" $0}' | grep Frank
> Frank Emrich	A	tests/functions/closure-conv-type-abstr-only.links
> Frank Emrich	A	bin/driver.ml
> Frank Emrich	A	bin/repl.ml
> Frank Emrich	A	install_local_opam2.sh
> Frank Emrich	A	core/irCheck.ml
> Frank Emrich	A	core/irCheck.mli
> Frank Emrich	A	tests/functions/nested-functions-polymorphic.links
> Frank Emrich	A	tests/validate_typecheck_testfile.testscript
> Frank Emrich	A	tests/typecheck_examples.tests
> Frank Emrich	A	tests/typecheck_examples.tests.config
> Frank Emrich	A	core/backend.ml
> Frank Emrich	A	core/irTraversals.ml
> Frank Emrich	A	core/irTraversals.mli
> Frank Emrich	A	core/dbDriverDynload.ml
> Frank Emrich	A	core/dbDriverDynload.mli
> Frank Emrich	A	database/mysql-driver/links_mysql_dependencies.json
> Frank Emrich	A	database/pg-driver/links_postgresql_dependencies.json
> Frank Emrich	A	database/sqlite3-driver/links_sqlite3_dependencies.json
```

**Comment by fehrenbach** [comment]
It doesn't have to be CI. We can configure git itself to Do An Approximation Of The Right Thing™.
https://help.github.com/en/articles/dealing-with-line-endings#per-repository-settings

**Comment by dhil** [comment]
@fehrenbach's solution ought to be easier to maintain.

**Comment by jstolarek** [comment]
> You probably want to checj all files created by him.

All the other files are fine.

One noteworthy exception where we want to keep DOS line endings is `tests/dos-newlines.links` whose purpose is to test whether Links correctly understands DOS file format. Warning: converting that file to UNIX format does not break the test so it is possible to silently disable the test without actually breaking it.

**Comment by frank-emrich** [comment]
yep, that's on me, although it shouldn't. I usually use the checkout-as-LF-commit-as-LF setting, since line endings don't really matter, but should be consistent as LF throughout the repo. I must have forgotten setting that for my links git :( I will create a separate PR changing all line endings once  the current bigger changes are through.
