### ISSUE TITLE
Check code style using OCaml format

### ISSUE THREAD

**Issue by rudihorn** [links-lang/links#501]
Following the whitespace / indentation comments in #498, I also just realised that we could extend this to formatting as well.  We could extend @dhil scripts to check the source code by using ocamlformat (https://github.com/janestreet/ocamlformat) to run on a source code and ensuring it makes no changes to that file during CI tests.

Can discuss at the next links meeting, I'm happy to help sort this out.

**Comment by dhil** [comment]
I think this has been on @frank-emrich's road map for quite some time. I recall discussing it last year. I am generally in favour of using some **automatic** code formatting tool.

**Comment by jamescheney** [comment]
We can close this now!
