### ISSUE TITLE
Continuous integration for SQLite3 database driver

### ISSUE THREAD

**Issue by dhil** [links-lang/links#505]
Currently, the SQLite3 driver is only being built by the CI, not tested. The test script is currently hard coded for PostgreSQL. We should rectify this, and run the database and database+shredding tests for SQLite3 (note, in order to get a system version of SQLite3 that supports shredding, we may have to use a third party source).

**Comment by jamescheney** [comment]
See also: #322

**Comment by dhil** [comment]
It seems Ubuntu 16.04 (as provided by Azure Pipelines) only offers SQLite3 version 3.11, whilst we require at least version 3.25 (c.f. [release notes](https://www.sqlite.org/releaselog/3_25_0.html)). So I suppose we need to find a third-party repository which offers a more recent version of SQLite3 before we can enable the shredding tests.
