### ISSUE TITLE
Test for a clean clone as part of CI

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#507]
Following discussion in #503, I think that CI should test whether the working tree in a cloned Links repo is clean. This will catch situations where we get the `.gitattributes` wrong and files are unexpectedly converted on clone. @SimonJF, you are familiar with CI - would it be a difficult thing to do? `git diff-index --quiet HEAD --` is the command to call. It returns 0 if the working tree is clean and 1 if it is not.

**Comment by jamescheney** [comment]
Is this still a concern?  Will it be obviated if we switch to Azure?
