### ISSUE TITLE
ConcreteSyntaxError vs SugarError

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#514]
In `Sugartypes` we have:

```OCaml
exception ConcreteSyntaxError       of (Position.t * string)
```
In `Errors.ml` we have:

```OCaml
exception SugarError of (Position.t * string)
```
What is the intended difference between the two?

**Comment by SimonJF** [comment]
From what I can tell, `ConcreteSyntaxError` is a syntax error (for example, an invalid primary kind annotation), whereas `SugarError` is a program which parses correctly, but a semantic problem has been found (for example, a duplicate attribute definition).

Generally, `ConcreteSyntaxError` appears in `parser.mly`, and `SugarError` appears during the desugaring stages.

There's also `RichSyntaxError` which is raised as a result of catching a `ConcreteSyntaxError`, containing more positional information.

I think there is a case for keeping them separate: the errors that are printed are distinct (in particular, the syntax errors provide a parse error message, whereas `SugarError` returns the parsed but semantically-incorrect expression).

I propose renaming `SugarError` to `DesugaringError`, and changing the error display of "Syntactic sugar error: " to "Error <description of stage>", for example "Error compiling regular expression: ...".

**Comment by SimonJF** [comment]
This terminology is clarified in #536, so closing.
