### ISSUE TITLE
Preserve aliases when dualising types

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#522]
In `dual_type` in `types.ml`, we have:

```
      (* it sometimes seems tempting to preserve aliases here, but it
         won't always work - e.g. when we use dual_type to expose a
         concrete type *)
      (* | `Alias _ as t         -> `Dual t *)
      (* Still, we might hope to find a way of preserving 'dual
         aliases' in order to simplify the pretty-printing of types... *)
      | `Alias (_, t) -> dt t
```

This has the disadvantage of making the type errors more difficult to read. It would be good to refactor things such that aliases can be preserved when dualised.

**Comment by jamescheney** [comment]
So just leaving the `Dual` constructor in the code (as in the commented-out version) looks like it would mostly just break things in unification, where we currently pattern match against the result to determine whether something is a dualized type variable.  

What about adding a "dual" flag to Alias which could be used to short-circuit type printing  in error messages, and defining `dual_type` to preserve the Alias constructor (with the flag flipped) and recursively dualize the body?

This would necessitate doing an additional `Types.concrete_type` call in a few places where `dual_type` is called, but that seems like an acceptable cost.  Note that `Types.concrete_type` calls `dual_type` in the `Dual` case though.
