### ISSUE TITLE
Phase out `failwith` for error reporting

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#525]
`failwith` is often used in parts of the frontend prior to typechecking to report error messages. It has the disadvantage of being rather ad-hoc, and often leads to lazy error message reporting.

Given all of the improvements to the position propagation recently, I wonder whether it might be a good idea to try and phase out `failwith` in favour of using the `Errors` module, with proper position reporting.

**Comment by dhil** [comment]
I agree, the front end is infested with `failwith`s, being the a source of many poor error messages. Purging `failwith`s should be an easy matter though. The module  `desugarDatatypes` may be a good starting point for the crusade.
