### ISSUE TITLE
Kind mismatch when no annotation is provided

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#526]
In `examples/handlers/aop.links`, we have the type definition:
```
typename SComp(e::Row, a) = (() {Suspend:((Expr, SComp(e, a))) {}-> a|e}~> a);
```
This works fine with stock Links (and we'd expect it to work -- since the quantifier has a Row kind annotation, we'd expect the RHS to also have kind `Row`). However, I think the only reason this seems to work is accidentally because of some voodoo done by the (soon-to-be-removed) type inlining pass.

To demonstrate, consider the following unrolling:

```
typename Expr = ();
typename SComp1(e::Row, a) = (() {Suspend:((Expr, SComp1(e, a))) {}-> a|e}~> a);
typename SComp2(e::Row, a) = (() {Suspend:((Expr, SComp1(e, a))) {}-> a|e}~> a);
```

this does not work: we get a `Kind_mismatch` error since `e` on the RHS of `SComp2` is assigned kind `Type` by the parser, and this is not changed before `desugarDatatypes`, where the check happens:

```
typearg:
| VARIABLE                                                     { (($1, (PrimaryKind.Type, None), `Rigid), None) }
| VARIABLE kind   
```

I'm assuming the intended behaviour is that a bound type variable should have the same primary kind as its associated quantifier, which should be fixable by another pass in `desugarDatatypes`. Am I misunderstanding, or missing something obvious?

**Comment by dhil** [comment]
As discussed offline, there is a bug in the source program. It should be
```
typename SComp(e::Row, a) = (() {Suspend:((Expr, SComp({ |e}, a))) {}-> a|e}~> a);
```
as we do not yet have syntactic sugar for writing bare row variables.

**Comment by SimonJF** [comment]
Thanks, @dhil.
