### ISSUE TITLE
readlink is not portable

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#530]
As discussed here:

https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

the `readlink` command differs between BSD/Mac OSX and Linux.  The difference is the former does not support the `-f` option (which follows recursive symbolic links) which we're using in the Makefile:

```
ROOT:=$(shell dirname $(shell readlink -fn $(firstword $(MAKEFILE_LIST))))
```

It would be good to find a portable way of accomplishing this.  @dhil this seemed to happen in #520.  Is following symbolic links recursively necessary here?

Is there any particular reason to use `readlink` at all here to find a instead of, say, '.' or 'Makefile'?  (since I guess the first word in `MAKEFILE_LIST` will be a relative path)

**Comment by dhil** [comment]
> It would be good to find a portable way of accomplishing this. @dhil this seemed to happen in #520. Is following symbolic links recursively necessary here?

I think my intention was to compute the absolute path of the Makefile, possibly thinking that it would be more robust. Nevertheless, It should be OK to use the relative path instead. I have updated the `Makefile` accordingly.

**Comment by jstolarek** [comment]
> I think my intention was to compute the absolute path of the Makefile

There is also `realpath` command (in coreutils) to do just that. Not sure about portability though.

**Comment by jamescheney** [comment]
Thanks @dhil.  I don't think `readlink` actually computes the absolute path anyway (at least on the OSX and Linux systems I tried) so just using any of  `.` or `Makefile` or `$(firstword $(MAKEFILE_LIST))` should work.

@jstolarek `realpath` doesn't appear to be installed by default on OSX but GNU `grealpath` is available in the same addon package as `readlink`.  So wouldn't be any easier/harder to handle than `readlink`.
