### ISSUE TITLE
Settings are unstructured, hardly documented

### ISSUE THREAD

**Issue by frank-emrich** [links-lang/links#537]
When adding yet more settings to `basicsettings.ml` (cf. #535), I realized that there is already a confusingly large amount of them. There are some attempts to structure them inside of `basicsettings.ml` using sub-modules, but that doesn't affect the way they are presented for instance when using `@settings` in the REPL.

A few ideas:
1. Separate between settings that are actually needed by end users (e.g., database credentials, typing related stuff) and those that are for debugging (the many show_* settings).

2. Make the documentation of the settings first class citizens. Currently, some of the entries in  `basicsettings.ml`  come with a comment. I suggest that the creation methods for settings get a new documentation field, which a) forces people to provide a description of the setting and b) allows us to print those short documentations in the output of `@settings`.

3. Consider a way of qualifying settings. For example all settings `foo` that affect typing could be named `typing.foo`, similarly to the sub-module structure that is already in  `basicsettings.ml`.

Discuss! :)

**Comment by jamescheney** [comment]
+1

Suggestion: modify `@settings` to take an optional parameter.  If omitted, then just some "default" groups of settings are listed (i.e. the ones we'd expect normal people to use) along with a list of all the settings groups.  `@settings <groupname>` should show the settings / descriptions of a given group, thus, saving non-nerds from having to read about all of the different ways to print ASTs if they don't want to know.

**Comment by jstolarek** [comment]
+1 from me as well. This seems like a low-hanging fruit for introducing a beginner to Links development.

**Comment by dhil** [comment]
Please hold back on doing anything settings related. I have partial fix for #314 which will modularise the settings. As a result the most (if not all) of `Basicsettings` will be disappear. Settings will be localised to the module that implement the behaviour that the settings toggle -- just as they were prior to the extension of effect handlers.

**Comment by dhil** [comment]
I should add that, my fix also provides a new API for defining settings and corresponding CLI parameters, and that API already includes the option to document settings.

**Comment by jstolarek** [comment]
> Settings will be localised to the module that implement the behaviour that the settings toggle

I think I don't like that idea - I'm curious to see the patch. In particular, how will it handle settings that are used in several modules and not just one?

**Comment by dhil** [comment]
> I think I don't like that idea

Why not? It is more modular -- and it used to be that way prior to my effect handlers patch three years ago.

> In particular, how will it handle settings that are used in several modules and not just one?

A module can export/expose the settings it defines.

> I'm curious to see the patch.

I will create the PR in a few weeks, I did a chunk of work on it during the flight to Japan last week.

**Comment by jstolarek** [comment]
> Why not? It is more modular

Settings are a single functionality and I'd prefer to have them in one place rather than spread across multiple files. That way, when I need to work on the settings I know where to look. And also any changes to setting are likely to focus on this one file, which I find easier than editing multiple files.

> A module can export/expose the settings it defines.

Right, but if I have a setting that is used equally by several modules, where will such a setting be defined? I'm guessing that it will be in one of those modules (arbitrary pick). 

But of course I haven't seen the actual patch, so I'd rather wait with the discussion until I actually get to see the code. Might be that I will actually like the idea.

**Comment by rudihorn** [comment]
If we are going to refactor command line settings, it might be worth trying to use a library to handle them. This might make it easier to support other things surrounding settings such as autocompletion. An example is the `Core` command subsets (https://v1.realworldocaml.org/v1/en/html/command-line-parsing.html). Though autocompletion is still a bit fiddly, as it still requires you to install something into the bash_completion.d folder.

> Settings are a single functionality and I'd prefer to have them in one place rather than spread across multiple files. That way, when I need to work on the settings I know where to look. And also any changes to setting are likely to focus on this one file, which I find easier than editing multiple files.

This could possibly done similar to the unit tests, where each file specifies it's own settings in a group of settings, but these are referenced by suite from some central location. That way it is possible to just follow a rabbit hole with merlin till you get to the location. Doesn't solve the editing multiple files though, but this isn't as critical IMO.
