### ISSUE TITLE
Support flat and shredded queries simultaneously

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#538]
Right now we support either flat queries and nested queries, depending on settings.  In the REPL one can switch between these options by enabling/disabling some settings.  But within a given expression (or non REPL program) we can only access one style of query.

Since the flat and nested query handlers each support some features that the other one doesn't, and it is reasonable to want to use (e.g.) both ordering/limit/count and nested query results in different parts of the same program, I propose that we enable both via (for now) two different `query` keywords (or by adding some attributes/parameters to the existing `query` keyword). One suggested design is as follows:

- `query [params] { for ... }`  will use the flat query compiler, and the results are statically required to be flat.   I.e. existing Links programs that don't use shredding continue to work as usual.
- `nested_query { for ...}` will use shredding, the results are not statically checked to be flat (and so there may be runtime failures if the return type is not a nested relation).  Existing Links programs that do use shredding would need to be changed to use `nested_query` but this should be a simple search-and-replace, and there aren't many test programs that use shredding.

Though longer-term, I would prefer to abstract over different possible ways of handling queries (so that both `query` and `nested_query` are definable constructs rather than builtin keywords) I don't have a design for this yet.  For now, I think this should be straightforward by adding a keyword and refactoring existing code.  We would also have to change the CI configuration to handle shredding in the new way.  This might make life slightly easier in that we could use the same configuration for shredding and plain queries, unlike now.

**Comment by SimonJF** [comment]
I'm going to take this one on. My proposed design is slightly different to the one in the issue:

```
query [range] policy {
  ...
}
```
where `policy` is either not there (in which case, the `shredding` setting determines whether to shred or not), `nested`, meaning that block is shredded, or `plain`, meaning that block uses the standard normaliser (and can therefore use features unsupported by the shredding algorithm).

**Comment by jamescheney** [comment]
Sounds reasonable to me.  At some point, it may make more sense to make query a "first class" operation (perhaps in an enriched language) that can take various ordinary parameters / arguments.
