### ISSUE TITLE
Create Vagrant image to simplify Links development and deployment

### ISSUE THREAD

**Issue by jgbm** [links-lang/links#54]

**Comment by jamescheney** [comment]
I have pretty much done this now (at least in a simple form) as part of making MSc students able to use Links.  Simon, maybe we should discuss.

**Comment by jamescheney** [comment]
See also:
https://github.com/links-lang/links/wiki/Installing-Links-on-a-fresh-VM

**Comment by jamescheney** [comment]
I will do this when I get a chance.

**Comment by jamescheney** [comment]
Done: https://github.com/links-lang/links-tutorial
