### ISSUE TITLE
Add "expected broken" tests to testsuite

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#542]
I'd like to be able to mark a test as expected to be broken, so that if a test actually passes it is marked as a failure. This will help to catch at least some of the accidental fixes.

**Comment by frank-emrich** [comment]
After working a bit on `test-harness` yesterday I realized that this is already possible:
`exit : 1`
will only succeed if the test exited with status 1. 

Of course, this only works as long as we don't introduce different exit codes for different kinds of errors.

**Comment by jstolarek** [comment]
Ok, that does what I need.
