### ISSUE TITLE
Support types in modules

### ISSUE THREAD

**Issue by jgbm** [links-lang/links#55]
At the 1 August meeting, we discussed supporting types in modules.

One point of discussion was the overlap between session type dots and module syntax.  We decided to require parentheses for types from modules in session types for the time being.  So, rather than writing

    ?A.B.!C.D.End

We would require

     ?(A.B).!(C.D).End

This should hopefully resolve the conflict between session types and module access syntax.

**Comment by SimonJF** [comment]
Fixed in c5e7ac3ec91551bc7d79d0a63ac4f1f34b7adcf2 in modules branch.

**Comment by jgbm** [comment]
"Yeah, that's done"
 -- Simon J Fowler, Esq.
