### ISSUE TITLE
Cleanup or eliminate desugarDbs

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#558]
`desugarDbs` currently does two things:

- `desugar_dbs` pass to remove the `DBInsert` abstract syntax and replace with calls to library functions
- `has_no_dbs` predicate to test whether `DBInsert` is present.  Never called from outside this module.

The code contains comments indicating that previously this stage handled `DBUpdate` and `DBDelete` syntax, no longer does, and that `DBInsert` syntax should also be moved to the IR:

```
TODO:

move insert into the IR

    insert table values rows
  -->
    InsertRows (table, rows)

    insert table values rows returning e
  -->
    InsertReturning (table, rows, field)
```

I think we should do this, and remove `has_no_dbs`, thereby decreasing the number of desugaring passes by one.

To do:
- [x] add insertion operations to `evalir.ml` (adapting code from `lib.ml`)
- [x] add `Insert` IR forms
- [x] extend EvalIR and IrCheck and other IR utilities to handle these forms
- [x] add `sugartoir` cases to translate `DBInsert` forms to their IR equivalents
- [x] disable `desugarDbs` and debug everything
- [x] delete dead `desugarDbs` and library `insert` code

**Comment by jstolarek** [comment]
> `has_no_dbs` predicate to test whether `DBInsert` is present. Never called from outside this module.

This is also true for other desugar modules. See `has_no_formlets`, `has_no_fors`, `has_no_funs`, `has_no_inners`, `has_no_lattributes`, `has_no_processes`, `has_no_regexes`, `has_exceptions`. I was wondering whether we can either make use of these or send them to /dev/null

**Comment by jamescheney** [comment]
Alternatively if the intention was to document the expected postconditions of each stage, maybe we should be checking them. (In either case this one can go if it's stage does.)

**Comment by slindley** [comment]
These should certainly not be deleted. They are indeed intended for checking post conditions and are useful for debugging. They certainly shouldn't be enabled by default, but it could be useful to allow them to be switched on and off dynamically using appropriate flags.

**Comment by jamescheney** [comment]
Understood.  But this issue is about whether we can get rid of the `desugarDbs` pass entirely, including its postcondition checker.  Is there any known obstacle to doing that?

**Comment by slindley** [comment]
No. That sounds like a good idea to me.
