### ISSUE TITLE
Add setting dependencies

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#560]
Some settings only make sense if other settings are enabled. For example `fail_on_ir_type_error` takes effect only if `typecheck_ir` is enabled. I propose that we have setting dependencies such that enabling a setting automatically enables the settings it depends on. For example if I enable `fail_on_ir_type_error` then `typecheck_ir` gets enabled automatically.

**Comment by SimonJF** [comment]
+1 to both of these. Another example of setting dependencies is `session_exceptions` depends on `enable_handlers`. It might be worth emitting a note saying that the dependency has been enabled transitively, too, as to avoid surprises.

**Comment by frank-emrich** [comment]
Yes, that sounds like a good idea. We should keep that in mind when doing any refactoring work related to  #537.

In general, it may be a bad idea if one setting magically enables other settings to resolve inconsistencies. How about a warning (or error?) along the lines of "you enabled X but not Y, that's probably not what you wanted"?

**Comment by jstolarek** [comment]
> In general, it may be a bad idea if one setting magically enables other settings to resolve inconsistencies. How about a warning (or error?) along the lines of "you enabled X but not Y, that's probably not what you wanted"?

Yes, such an alternative design is also an option. I don't have a strong preference here. I just would like to see an improvement of the current design, so that I don't get confused as to why a given setting does not work.

**Comment by SimonJF** [comment]
> How about a warning (or error?) along the lines of "you enabled X but not Y, that's probably not what you wanted"?

We have this in an ad-hoc way already (c.f. session exceptions). It would be nice to do this in a more principled way.

**Comment by jstolarek** [comment]
> We should keep that in mind when doing any refactoring work related to #537.

More generally, there is the Setting project that groups all the tickets related to settings.

**Comment by dhil** [comment]
Fixed by #745.
