### ISSUE TITLE
Fresh type variables should not be generated during parsing

### ISSUE THREAD

**Issue by slindley** [links-lang/links#566]
Links conveniently allows the programmer to omit the name of a type variable when it is irrelevant (e.g. because it occurs only once in a type). This syntactic sugar is particularly handy for first-order effect-polymorphic functions. For instance the type of `+` may be written as

    (Int, Int) -> Int

which actually means

    (Int, Int) -e-> Int

for some fresh effect variable `e`.

Currently the generation of fresh variables is performed during parsing, which is a mistake as it limits the sophistication of the algorithm for generating fresh names. (In general it is a bad practice to mix computation with parsing and we should strive to separate them.)

Currently Links generates fresh type names of the form `_XXX` where `XXX` is a globally unique integer. We should change the parser to just generate the special name `_` and then apply a desugaring phase immediately after parsing in order to generate fresh names.

The particular use-case I have in mind is to extend the syntactic sugar in order to allow effect variables to be omitted from most higher-order functions, inspired by [Frank](https://github.com/frank-lang/frank). Currently the type of map is

    ((a) -e-> b, [a]) -e-> [b]

whereas with the sugar I have in mind it could instead be written as

    ((a) -> b, [a]) -> [b]

The key idea (taken from Frank) that makes this possible is the observation that almost always all of the effect types on the arrows of a higher-order function match up. This is hardly surprising given that typically higher-order functions apply their argument functions, and in order to do so the effects of the arguments must match up with those of the higher-order function itself.

**Comment by SquidDev** [comment]
Should have been resolved by #625.
