### ISSUE TITLE
About the semantics of `open`

### ISSUE THREAD

**Issue by dhil** [links-lang/links#571]
Automatic resolution and loading of external modules is part of the current Links semantics. For example consider two modules `foo.links` and `bar.links`
```links
# foo.links
var hello = "Hello World";
```
```links
# bar.links
open Foo;

fun main() {
  println(hello)
}
main()
```
Executing `./links -m --path=. bar.links` prints out `Hello World`, that is, the compiler has implicitly loaded the external module `foo.links` for us.

However, if you were to slightly rewrite `bar.links` to
```links
# bar.links
fun main() {
  println(Foo.hello)
}
main()
```
then executing `./links -m --path=. bar.links` yields a compile time error
```
bar.links:2: Type error: Unknown variable Foo.hello.
```
Thus the compiler did not load `foo.links` for us, which may be a little surprising if we think of ML languages. However, it is arguably OK, because a simple typo could potentially cause the compiler to load an arbitrary amount of modules.

We can instruct the compiler to load `foo.links` for us by adding back the `open`
```links
open Foo;

# bar.links
fun main() {
  println(Foo.hello)
}
main()
```
Note that `hello` is still prefixed by `Foo`. Running `./links -m --path=. bar.links` prints out `Hello World` just as the first program did. So `open` really acts as an "import statement" instructing the compiler to go figure out how to load the said module.

Now, we also have support for local module definitions. In particular, local definitions may shadow external file-based modules.
```links
open Foo;

module Foo {
  var hello = "Hello from Bar!";
}

open Foo;

fun main() {
  println(hello)
}
main()
```
Running `./links -m --path=. bar.links` prints `Hello from Bar!`. The `bar.links` program contains two `open Foo` expressions. The two are morally different. The first instance **imports a global module**, whilst the second instance **opens a local module** (or more generally, opens a module that has already been loaded [local modules are trivially loaded]).

An import entails resolving a module on disk and transitively load its dependencies, which is quite convenient, but as I argue it is different from simply "opening" a module to bring its contents into scope.

I would like the difference to be reflected in the language for two reasons

* It can lead to mildly confusing behaviour.
* The implementation of the loader can be vastly simplified, as currently the loader needs to understand the binding structure and semantics.

I propose to add `import` (or `using`) as a primitive, whose intended semantics is to load global modules, e.g.
```links
# bar.links
import Foo;

fun main() {
  println(hello)
}
main()
```
where the `import` instructs the compiler to locate `foo.links` on the disk, such that running `./links -m --path=. bar.links` prints `Hello World`. Moreover, omitting the `import` or using `open` instead would be a compile time error, e.g.
```links
# bar.links
open Foo;

fun main() {
  println(hello)
}
main()
```
running `./links -m --path=. bar.links` should yield `error: unbound module Foo`, because no such module `Foo` has been loaded.

Having a primitive like `import` enables the programmer to clearly express their intent, and it provides an easy way to compute the dependency graph of a given module without having to have knowledge of the Links binding structure and semantics.

Further down the pipeline, I can also envisage using `import` to import/use whole namespaces rather than a single module. But I will leave that for future consideration.

**Comment by SimonJF** [comment]
I'm *very* much in favour of this. In my large clone of a scientific database, I'm tripping over this all of the time, and I appreciate you putting my exact thoughts into an issue!

**Comment by jamescheney** [comment]
I think separating `import` (compilation unit management) from `open` (module management) is a good idea.  However, I'd suggest defining `import Foo` to mean *only* that the contents of compilation unit `Foo` are required, not that `Foo` is opened, so that after doing `import Foo` you can reference `Foo.xyz` by fully qualifying, but not otherwise.  If you want do to both at once then that should be `open import Foo` or something.

One of the things that bugs me about OCaml's (and to be fair most other) module systems is the punning of module = file / namespace = directory, which works well only as long as you don't have other modules defined inside compilation units, like in Haskell.  Most module system writeups I've seen assume a "one giant program" model.

However, I'm not familiar with a ML-like system that really gets this right - F# is a little better by distinguishing between namespaces and modules, but still puns compilation units as modules like OCaml (so, referencing `Foo.xyz` creates a requirement to find `Foo` somewhere, not such a pain for a compiled language but definitely a pain for us...)

Has anyone seen a writeup of a ML-like module system that explicitly accounts for compilation units separately from modules?

**Comment by dhil** [comment]
> However, I'd suggest defining import Foo to mean only that the contents of compilation unit Foo are required, not that Foo is opened [...]

Yes, I agree, that is a better semantics.

> One of the things that bugs me about OCaml's (and to be fair most other) module systems is the punning of module = file / namespace = directory, which works well only as long as you don't have other modules defined inside compilation units, like in Haskell. Most module system writeups I've seen assume a "one giant program" model.

Indeed, it is a pain, and I always thought it was somewhat *ad hoc*. In the future, it would be good if we can pin down a modular design for a ML-like module system.

**Comment by jamescheney** [comment]
Maybe this is worth a look:
David Swasey, Tom Murphy, VII, Karl Crary, and Robert Harper. 2006. A separate compilation extension to standard ML. In Proceedings of the 2006 workshop on ML (ML '06). ACM, New York, NY, USA, 32-42. DOI: https://doi.org/10.1145/1159876.1159883

**Comment by frank-emrich** [comment]
I have no strong preference for either choice in terms of language design.
However, Daniel's suggestion makes the implementation much cleaner & simpler. Currently, my replacement for Simon's "chaser" has to understand scoping of modules (including imports) to determine what additional files must be loaded. With Daniel's proposal, this is no longer the case, which is good.
