### ISSUE TITLE
"Type mismatch" IR typing error produced by `curry` Prelude function

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#574]
(results below were obtained from commit dccf4aa, currently in #572 PR)

`curry` function from Prelude:

```
fun curry(f) {
  fun (x)(y) { f(x,y) }
}
```

causes a "Type mismatch" IR typing error:

```
Type mismatch:
 Expected:
  (229:(a::Any, b::Any) -c-> d::Any,230:a::Any)
 Actual:
  (229:(a::Any, b::Any) -e-> d::Any,230:a::Any)
```

Config settings:

```
typecheck_ir=true
prelude=empty.links
optimise=false
debug=true
hide_fresh_type_vars=false
show_flavours=true
```

Error goes away with `optimise=true`.

**Comment by jstolarek** [comment]
Here's what I learned so far. For the sake of brevity I'm replacing long variable representations of the form `MetaTypeVar (Point @ 0x7fe30e285490 Var ((377, (CommonTypes.Linearity.Any, CommonTypes.Restriction.Any), Rigid` with just the number.  The IR checking error reported in this bug is raised in the `Closure` case of `irCheck.Typecheck.value`.  There we have the following instantiatiom map for type variables:
```
{369 => 377; 370 => 378; 372 => 380; }
```
and for row variables:

```
{371 => ({},355,false);}
```

The type of binder obtained via `lookup_closure_def_for_fun f` is:

```
Record (({229 => Present (Function
            (Record ({1 => Present 369; 2 => Present 370; },
             Point @ 0x7fe30e91bc68 Closed, false),
            ({}, 371, false), 372);
          230 => Present 369; },
         Point @ 0x7fe30e91bc68 Closed, false))
```

notice how all variables in that type appear in the domains of instantiation maps.  Indeed, the type of `type_of_environment` (the expected type constructed in the IR checker) is:

```
Record (({229 => Present (Function
            (Record ({1 => Present 377; 2 => Present 378; },
             Point @ 0x7fe30e91bc68 Closed, false),
            ({}, 355, false), 380;
          230 => Present 377; },
         Point @ 0x7fe30e91bc68 Closed, false))
```

which is the same type as the `binder` but with variables replaced according to the instantiation maps.  However, looking at the actual type constructed by recursive call `o#value z` (where `z` is a value stored inside a `Closure` we get:

```
Record (({229 => Present (Function
            (Record ({1 => Present 377; 2 => Present 377; },
             Point @ 0x7fe30e91bc68 Closed, false),
            ({}, 379, false), 380);
          230 => Present 377; },
         Point @ 0x7fe30e91bc68 Closed, false))
```

Notice how effect variable 371 was not substituted with 355 but rather replaced with a 379.

@frank-emrich, is it possible that what I'm looking at here is an artifact of IR typechecking rather than a genuine IR generation bug?

**Comment by jstolarek** [comment]
Important fact: this one example does not typecheck with `recheck_frontend_transformations=true`:

```
Error during desugaring pass 'funs'

:0: Type error: Variable x of linear type `MetaTypeVar (Point @ 0x7f1c5495fe50 `Var ((355,
                                            (CommonTypes.Linearity.Any,
                                             CommonTypes.Restriction.Any),
                                            `Rigid))) was used in a non-linear function definition
In expression: <dummy>.
```

**Comment by slindley** [comment]
#795 fixes the auxiliary problem (that arises when `recheck_frontend_transformations` is set to `true`) but the original bug remains
