### ISSUE TITLE
Abandon Travis in favour of Azure Pipelines?

### ISSUE THREAD

**Issue by dhil** [links-lang/links#584]
Travis offers only dated solutions for projects like ours, meanwhile Microsoft [Azure Pipelines](https://github.com/marketplace/azure-pipelines) offers parallel jobs and a more recent version of Ubuntu, for free.

**Comment by frank-emrich** [comment]
I'm in favor of this, because 
1) It gives us Ubuntu 16.04 rather than the ancient 14.04
2) Sometimes, when multiple people have open PRs they push to and/or a branch in the main Links repo used for active development, it can take some time until your CI job is executed. This is because Travis doesn't give us parallel jobs.

**Comment by dhil** [comment]
... also since Microsoft has acquired GitHub it may be a safe bet to use their CI solution.

**Comment by dhil** [comment]
As an experiment commit [c1b4de49](https://github.com/links-lang/links/commit/c1b4de491f89ab327e9295b1e31cbc199780f9b8) enables Azure Pipelines. The current config is essentially just a transcription of the Travis config, and as such, it does not take advantage of parallel jobs.

**Comment by dhil** [comment]
Patch #628 adds macOS to the test matrix.

**Comment by dhil** [comment]
Patch #633 fixes a regression in the macOS image. Suddenly overnight `brew services start postgres` began to fail due to wrong permissions. The patch ditches the `brew services` interface and instead uses `pg_ctl` to interact directly with the postgres service.

This incident may indicate that using `brew` in the CI image is a poor choice.

**Comment by jstolarek** [comment]
These random failures would be tolerable if there was a sane way to restart a build. Creating a dummy commit does not count as sane. For me that's a blocker for transitioning to pipelines.

**Comment by dhil** [comment]
> These random failures would be tolerable if there was a sane way to restart a build.

Ah, you can restart a build from the web interface. It probably doesn't show for you, because I haven't given you access! I only gave the students access, because I didn't want to spam your inboxes. I should have sent you an invite now.

**Comment by jstolarek** [comment]
What credentials should I use for login?

**Comment by dhil** [comment]
Your university (Microsoft) account. You should have received an invite on that e-mail -- at least I was able to look you up in the Office365 directory.

**Comment by dhil** [comment]
I had to push two changes to the Azure Pipelines configuration (#779 and #781) due to changes in either `brew` or the macOS image. I wonder whether there exists a better alternative to `brew` or a way to configure it such that the CI is more resilient against third party changes.

**Comment by frank-emrich** [comment]
Following the discussion in #793, @dhil suggested abandoning the new Azure CI and keeping just Travis. I still think that the Azure pipelines have advantages, namely newer Linux versions and the ability to run several jobs in parallel (e..g, multiple PRs being checked in parallel). 

It seems to be the Mac version of the pipeline giving us most of the headaches. I suggest we disable the Mac pipeline until we have someone with a Mac setup closer to what is running in the Mac CI (i.e., using brew).

**Comment by slindley** [comment]
@frank-emrich that seems reasonable to me. It would be handy if we could easily switch these things on and off. Can we keep the Mac configuration around in a dormant state that isn't run by default?

**Comment by jamescheney** [comment]
On closer inspection of `travel_portal.*` it seems that WITH OIDS is not really essential for this example (the OIDs are not used in the test queries).

**Comment by dhil** [comment]
The Azure Pipelines Linux image now fails do to issues with initialising `apt` (c.f. https://dev.azure.com/links-lang/links/_build/results?buildId=1052&view=logs&j=9d2c3360-7b91-513f-a835-6d859c349131&t=085f30a3-5311-5f44-7f03-78e773c7228c&l=61):
```
...
Err:12 http://azure.archive.ubuntu.com/ubuntu bionic Release
  404  Not Found [IP: 51.132.212.186 80]
Err:13 http://azure.archive.ubuntu.com/ubuntu bionic-updates Release
  404  Not Found [IP: 51.132.212.186 80]
Err:14 http://azure.archive.ubuntu.com/ubuntu bionic-backports Release
  404  Not Found [IP: 51.132.212.186 80]
...
E: The repository 'http://azure.archive.ubuntu.com/ubuntu bionic Release' no longer has a Release file.
E: The repository 'http://azure.archive.ubuntu.com/ubuntu bionic-updates Release' no longer has a Release file.
E: The repository 'http://azure.archive.ubuntu.com/ubuntu bionic-backports Release' no longer has a Release file.
```

It may or may not be related to the on-going [network service](https://devblogs.microsoft.com/devops/new-ip-address-ranges-with-service-tags-for-azure-devops-services).

I am quite keen to remove Azure Pipelines and close this issue. The primary reason being the rich history of extraneous failures caused by Azure Pipelines, which induce an unacceptable maintenance burden. The original intent of this issue was to investigate whether we could use Azure Pipelines to address the short comings of Travis. Somewhat ironically, the many problems with Azure Pipelines have led us to disable the one major advantage of Azure Pipelines have over Travis (#793), causing us to use Azure Pipelines as a mere shadow of Travis. Whilst it is true that Azure Pipelines offer the ability to run multiple jobs in parallel, our build pressure is low, and moreover, our current CI configuration offer very little value over running tests locally.

Unless someone can make a sensible case for keep hanging on to Azure Pipelines, or someone wants to take on the mantle of maintaining the Azure Pipelines CI configuration, then I will remove Azure Pipelines from the CI configuration by the end of this week.

**Comment by jamescheney** [comment]
I don't object.  I think the issue with macOS (#793) was transient and has been fixed now anyway by avoiding the dependency on the breaking change introduced when PostgreSQL deprecated and removed `WITH OIDS` - we wound up having to fix this anyway when the Linux default version of PostgreSQL increased.

But it seems that Travis now has a macOS environment, so if we wanted to reinstate CI for boutique operating systems that only a fraction of the Links user community uses, we could try that :)

**Comment by dhil** [comment]
> But it seems that Travis now has a macOS environment, so if we wanted to reinstate CI for boutique operating systems that only a fraction of the Links user community uses, we could try that :)

Great! This only strengthens my belief. I think it is good if our continuous integration toolchain has a macOS image to provide a minimal degree of confidence that Links works on macOS. I reckon that future interns or collaborators are likely to be using macOS, so having the CI running macOS could potentially save us some trouble.

**Comment by jamescheney** [comment]
In fact now that Vashti is working on Skye the number of macOS users has doubled.  (And we found out that there is a slightly weird issue due to the `libpq` API changing in PostgreSQL 12 though this was not a macOS issue per se.)
