### ISSUE TITLE
Fix usages of tuple smart constructor

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#592]
As detailed in https://github.com/links-lang/links/pull/577#issuecomment-487694643

**Comment by slindley** [comment]
I think this is the correct fix for now: 3259a9dc73bbe1a55a2c2938dcc679eeff86eb88. Ultimately we should probably do something more robust with regard to tuples, 1-tuples, multi-argument functions, order by, etc.

**Comment by jstolarek** [comment]
Ah, good! Let's keep this ticket open then until your branch gets merged.

**Comment by dhil** [comment]
Closing as I think 3259a9d became part of the FreezeML branch. Please reopen if I am mistaken.
