### ISSUE TITLE
Desugaring session exceptions is not type-preserving

### ISSUE THREAD

**Issue by slindley** [links-lang/links#597]
Desugaring session exceptions - specifically the part that inserts top-level handlers inside a `spawn`  breaks typing. The problem is that the translation to insert top-level handlers creates a `TryInOtherwise` whose body needn't have the special `_SessionFail` effect. (This breaks the typing of practically every single program that uses session exceptions as session typing with spawning is rather useless.)

A couple of possible fixes come to mind.

 * One option would be to change the types of the family of spawn functions such that the body always has the special `_SessionFail` effect whenever the `--session-exceptions` flag is set.

 * Another (probably better) option would be to insert an upcast on the body during the translation to enable top-level handlers.

**Comment by SimonJF** [comment]
Ooft. Good spot. Yes, option 2 sounds best to me: so if I understand correctly, explicitly adding the `_SessionFail` effect to the effect row of the body during the translation?
