### ISSUE TITLE
Boundary Peek

### ISSUE THREAD

**Issue by dhil** [links-lang/links#598]
Modules break the lexical scope as exemplified by the following program
```links
# scope.links
module A {
  var x = "A1";
}

open A;

module A {
  var x = "A2";
}

println(x)
```
The first module `A` is opened, and hence `x` is brought into scope unqualified. The second definition of `A` shadows the first, but crucially its contents are not brought into the toplevel scope, hence the program should print `A1`, but running `./links -m scope.links` produces the output
```
A2
() : ()
```
Thus it is possible to peek across scope boundaries.

The problem has little to do with modules, it just happens that modules expose the problem. The real problem is that our handling of names in the front end is broken. We should really be resolving names early on in the front end to rule out a whole class of problems.

**Comment by jamescheney** [comment]
> We should really be resolving names early on in the front end to rule out a whole class of problems.

+1,000,000
