### ISSUE TITLE
Desugaring of alien blocks is incomplete

### ISSUE THREAD

**Issue by dhil** [links-lang/links#604]
The following example demonstrates that the desugaring of alien blocks is not complete
```links
# foo.links
if (true) {
  alien javascript "foo.js" {
    foo : () ~> ();
  }
  foo()
} else { () }
```
Running `./links foo.links` triggers an assertion failure
```
***: Error: "Assert_failure core/typeSugar.ml:3914:20"
```
Which is the case for `AlienBlock` in `typeSugar.ml` as alien blocks are expected to have been desugared by this point.

The problem is that the desugaring pass does not traverse the `Sugartypes.phrase` component of a given `Sugartypes.program`. It should be simple to fix.

However, we may want to ask ourselves whether we really want alien declarations below the toplevel (where toplevel is defined as the outer most scope of a compilation unit, and/or module)?

**Comment by SimonJF** [comment]
Nested alien blocks make no sense to me. I think this was meant to be a toplevel declaration only. My preference for fixing this would be to simply make the parser more restrictive.

**Comment by dhil** [comment]
> I think this was meant to be a toplevel declaration only. My preference for fixing this would be to simply make the parser more restrictive.

Yes, given that `import` (#571) is supposed to be a top-level thingie too, it would be good we could separate declarations/bindings into two groups: top-level ones and below top-level ones.
