### ISSUE TITLE
Installing with Debian WSL

### ISSUE THREAD

**Issue by montao** [links-lang/links#611]
I get this error but I have the dependencies:

```
The packages you requested declare the following system dependencies. Please make sure they are installed before
retrying:
    debianutils m4 pkg-config
```

**Comment by jamescheney** [comment]
Hi, thanks for trying Links!

Could you provide a little more context: for example what command you used to try to install leading to the above error, and what output did you see before the error message?

If it was something like `opam install links`, this first tries to install many other opam packages that may have such dependencies, so the problem may not be a Links-specific issue.  Links itself does not directly depend on these system packages as far as I know.

**Comment by montao** [comment]
To resolve it, I removed opam and deleted the .opam directory. Then I reinstalled and initiated it with --disable-sandbox and then it worked... It might be that not all these measures are necessary, but it seems that I had to start over in order to reload dependencies. This is with Debian WSL on MS-Windows 10 host. 

Looks like it works:
```


niklas@DESKTOP-B0KNGSD:~$ linx
 _     _ __   _ _  __  ___
/ |   | |  \ | | |/ / / ._\
| |   | | , \| |   /  \  \
| |___| | |\ \ | |\ \ _\  \
|_____|_|_| \__|_| \_|____/
Welcome to Links version 0.6.1 (Gorgie)
links> 1+2;
3 : Int
links>
```

**Comment by jamescheney** [comment]
Thanks! The current version of Links is 0.8 so something may still be out of date. In any case, please let us know if (when) you run into any other problems!
