### ISSUE TITLE
Error Installing Links

### ISSUE THREAD

**Issue by carloprato13** [links-lang/links#618]
=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[links] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of links failed at "dune build -p links -j 4".
Processing  1/1: [links: rm]
=== ERROR while installing links.0.8 =========================================#
 opam-version 1.2.2
 os           linux
 command      dune build -p links -j 4
 path         /home/carlo/.opam/4.06.0/build/links.0.8# compiler     4.06.0
 exit-code    1
 env-file     /home/carlo/.opam/4.06.0/build/links.0.8/links-19389-5f1023.env
 stdout-file  /home/carlo/.opam/4.06.0/build/links.0.8/links-19389-5f1023.out
 stderr-file  /home/carlo/.opam/4.06.0/build/links.0.8/links-19389-5f1023.err
### stderr ###
Info: creating file unit/dune-project with this contents: (lang dune 1.2)
 File "core/dune", line 20, characters 14-56:
 20 |   (preprocess (pps ppx_deriving.std ppx_deriving_yojson)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 Error: No ppx driver were found. It seems that ppx_deriving.std and
 ppx_deriving_yojson are not compatible with Dune. Examples of ppx rewriters
 that are compatible with Dune are ones using ocaml-migrate-parsetree, ppxlib
 or ppx_driver.

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install links 0.8
No changes have been performed
`

What should i do?
I am following https://github.com/links-lang/links/blob/master/INSTALL but can't manage to install

**Comment by dhil** [comment]
The instructions are written for OPAM version `>= 2`. You seem to be using version `1.2.2` which by software measures is quite ancient now. I recommend you update your version of OPAM and try again. The latest version of [OPAM is `2.0.4`](https://opam.ocaml.org/doc/Install.html).

**Comment by carloprato13** [comment]
I managed to install Links (even though i had other troubles relating to bubblewarp package), now i am trying to run the examples ( always following https://github.com/links-lang/links/blob/master/INSTALL).
I run:
linx -m --path=$OPAM_SWITCH_PREFIX/share/links/examples:$OPAM_SWITCH_PREFIX/share/links/examples/games $OPAM_SWITCH_PREFIX/share/links/examples/webserver/examples-nodb.links
without having any response on the stdout, and the webapge http://localhost:8080/examples/ is just a "Not found" message

**Comment by SimonJF** [comment]
`Not found` on its own is weird. Have you tried just going to http://localhost:8080/?

**Comment by carloprato13** [comment]
Yes, stil not found
Could i have a conflict between the links server and my LAMP one in /var/www/html/ ?
Still, when i execute the linx command i get no response on the stdout, is that okay?
i'll try to verify my links installation and i'll try again

**Comment by jamescheney** [comment]
You should indeed make sure there is nothing else running at port 8080 (the default used by Links) - conceivably something else could claim this port without actually using it.  Perhaps the error you are getting is Links's unhelpful way of telling you the port is already in use.  You can try a different port by setting the port parameter in the config file.  (See points 1 and 2 in INSTALL after it says "But first you need to do a few things.)

The correct behavior (for a web-application example) is that there is no output but the program should be responsive on the web page.  (We could maybe provide more visible feedback on the console that the right thing is happening)

If you haven't already, it might be helpful to check whether Links itself is working by trying a few commands at the REPL, e.g.

```
$ ./linx
Welcome to Links version 0.8 (Merchiston)
links> 1+1;
2 : Int
```

**Comment by carloprato13** [comment]
I managed to run the examples without a database, still trying to get to thise with.
In 2) you say i should tie my username to fre in postgresql:
"The database user fred should exist. With postgres, perhaps the easiest way to do this is to tie fred to your unix username and then no separate authentication is required."
How do i manage to do so? the only hint i found : https://www.postgresql.org/docs/9.1/auth-username-maps.html
thanks again for the help

**Comment by jamescheney** [comment]
I think the advice to "tie your username" is not a technical concept but just the idea that if your (Unix/OS) username is `fred` then you also create a database user named `fred` so that the default behavior of assuming the database username is the same as the OS user name helps you.  At least that is what I do.

The instructions how to set up the database in INSTALL are soemwhat basic, and it is assumed that you have some familiarity with generic postgres or mysql configuration.  There are more detailed instructions here which might also be helpful.

https://github.com/links-lang/links/wiki/Database-setup

**Comment by jamescheney** [comment]
By the way, do you know what was blocking running the non-database examples (or what seemed to help overcome the problem)?  It would be good for us to track down the "not found" error message you were seeing and change it to a more informative one.

**Comment by carloprato13** [comment]
I guess my main problem was in executing the command in the right directory and having a proper installation. Also, the docs at https://github.com/links-lang/links/blob/master/INSTALL and those in the links folder inmy opam switch are different, followinf the last one helped me executing everything.
Thanks for the tips, i'll close the issue since my remaining problems are not related to links.

**Comment by jamescheney** [comment]
OK, thanks for trying and let us know if you run into other problems!
