### ISSUE TITLE
Replacing OCamlMakefile with ocamlbuild?

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#62]
Currently used build method - OCamlMakefile - seems to have two drawbacks:
- it puts all the compilation artefacts in the same directory as the source files. I looked at the documentation and it seems that OCamlMakefile can't do better
- file dependencies need to be figured out manually and listed explicitly in the `Makefile`

I was wondering if it would make sense to move from OCamlMake to `ocamlbuild`? As a quick and dirty attempt I managed to compile links with:

```
ocamlbuild -use-ocamlfind -pkgs 'bigarray,num,str,deriving.syntax,deriving.syntax.classes,deriving.runtime,lwt,lwt.syntax,lwt.unix' -syntax camlp4o "links.native"
```

This is definitely not sufficient as it does not seem to compile database backends. It would require a bit more investigation to figure out how to deal with that. Do others think this is worth doing? The benefits would be clean source tree (all `.o`, `.annot`, `.cmi` and `.cmx` files would land in `_build` directory) and there would be no need to manually figure out module dependencies.

See #78 for an uo-to-date list of TODOs.

**Comment by fehrenbach** [comment]
Last time I checked, ocamlbuild did not do parallel compilation.

**Comment by jstolarek** [comment]
AFAIK it still doesn't. Would this be a blocker?

**Comment by fehrenbach** [comment]
I guess not. If you can figure out the database stuff, go for it :)

(My understanding is that the database backends contain side-effecting code at the toplevel with which they register themselves at runtime. It should be enough to convince ocamlbuild that they need to be built and linked into the final executable.)

**Comment by jstolarek** [comment]
Another option that looks promising is [Oasis](https://github.com/ocaml/oasis). It is built on top of ocamlbuild. At a first glance it seems that with Oasis it might be easier to set up all the complex build rules required for building database backends.

**Comment by yallop** [comment]
[topkg](http://erratique.ch/software/topkg/doc/Topkg.html) is also worth a look.  Several packages are currently switching over to topkg from _oasis ([e.g.](https://github.com/mirage/ocaml-git/pull/158)).  Package descriptions are generally very succinct, and it's well integrated with other parts of the ecosystem (ocamlbuild, ocamlfind, OPAM, etc.)

[I hope you don't mind my jumping in.  I think I wrote some of the current OCamlMakefile-based setup for Links, so I feel a certain responsibility here.]

**Comment by jstolarek** [comment]
> I hope you don't mind my jumping in.

Not at all! Every piece of advice is very appreciated, especially that I am only starting to learn OCaml and its tool ecosystem.

**Comment by jstolarek** [comment]
Replying to @fehrenbach's comment in #66 

> Maybe our next buildsystem could even [find `postgresql` installation with `ocamlfind`] automatically?

I would definitely want some kind of automation here. The question is whether we want the build system to automatically look if a database backed is available and, if so, enable it for compilation. What would happen in such a case if there are several backends available? Enable all of them by default? Or would we be happy with saying something like `make postgresql` to compile Links with PostgreSQL support? (This, I think, should be very straightforward to do with the `Makefile` that we have currently.

**Comment by jstolarek** [comment]
As a part of this I propose that we move the source files to their separate directory in the project tree (this usually is `src` directory). Current setup of having source files at the top level directory of the project and in the same place as compiled files is horrible for greping the source code.

**Comment by jstolarek** [comment]
(Some discussion on the build system has been going on [here](https://github.com/links-lang/links/issues/61#issuecomment-250686503))

Notes from today's meeting:

  * OCaml 4.02 should be a reasonable minimal requirement
  * OMake might be an alternative to consider
  * we should declare one database backend as always enabled (Postgres and SQLite were suggested) and only build other backends optionally if dependencies are available

**Comment by jstolarek** [comment]
Following @slindley's yesterday's concerns about Oasis performance I've done some rough timings on both build system.

| No. of cores | OCamlMake  | Oasis |
|--------------|------------|--------------|
| 1            | 11.05s     | 27.07s       |
| 2            |  5.95s     | 21.93s       |
| 3            |  4.39s     | 20.57s       |
| 4            |  3.72s     | 19.96s       |
| 5            |  3.65s     | 19.97s       |
| 6            |  3.43s     | 19.37s       |
| 7            |  3.31s     | 19.12s       |
| 8            |  3.27s     | 19.00s       |

I have also done a quick survey of random OCaml projects to see what build systems they use. Here's a short summary:

  * The largest projects that came to my mind - OCaml and Coq compilers - both use custom Makefiles. These tend to be very large, nearly 2K lines for OCaml and over 2.3K lines for Coq. They determine dependencies using `ocamldep`.
  * Jane Street builds their projects using Oasis (this is well over a hundred libraries).
  * Otherwise there seems to be no dominating solution. Some projects use a custom `Makefile` and determine dependencies using `ocamldep`, while others leave dependency resolution to `ocamlbuild`.

**Comment by jstolarek** [comment]
IIRC there were also some concerns whether the build tools are being actively maintained. I just checked that.

Until OCaml 4.03 (latest stable version) `ocamlbuild` was included in the same repository as the compiler itself, so my understanding is that it is being maintained and developed by the same people that work on OCaml compiler.

Oasis repo also looks active (perhaps even more than ocamlbuild) and is also a part of OCaml organization on github, which in my eyes gives it credibility as a stable project.

**Comment by jamescheney** [comment]
It looks like we have decided not to do this, at least for the time being.  Shall we close this issue?

**Comment by jstolarek** [comment]
>  Shall we close this issue?

That depends. If we think that this is generally a bad idea to move away from OCamlMakefile and we don't want to do it then let's close the issue. If we think it might be a good idea (or at least an idea worth exploring further), but we simply don't have the time to do this at the moment, then we should keep this issue open. I'm leaning towards the second option. What others think?

**Comment by jstolarek** [comment]
Unassigning myself - not working actively on this in foreseeable future.

**Comment by jamescheney** [comment]
This will be superseded by merging #265
