### ISSUE TITLE
IR Typing and effect instantiation

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#620]
Say I have the following program:

```
sig foo : () -> ()
fun foo() {
  ()
}

sig bar : () ~> ()
var bar = foo;
```

That is, I have a pure function, and I want to be able to treat it as wild. This types fine, but we get an IR type error:

```
Continuing after IR Type Error:
Type mismatch:
 Expected:
  () ~> ()
 Actual:
  () ~> ()
occurring in IR binding:
(Ir.Let ((2123, (() ~> (), "bar", Var.Scope.Global)),
   ([], (Ir.Return (Ir.TApp ((Ir.Variable 2122), [{ |wild|_ }]))))))
backtrace:
```
I have also tried this on the `ordered-quantification` branch, which seems to have various fixes.

(Forgive me if I'm missing something obvious here.)

**Comment by frank-emrich** [comment]
I never fully understood how the sub-effecting is supposed to be reflected in the IR. My assumption was that a `Ir.Coerce` should be inserted in the IR code, which makes the casting explicit. That seems not to be the case, given your example...

The alternative would be to allow sub-typing almost everywhere in the IR where currently type equality is expected. I'm not sure if that is what we want.

**Comment by slindley** [comment]
That's *not* subeffecting! It's just plain old instantiation. There's no need for `Ir.Coerce`, which should be used when you write an *explicit* upcast.

There's little point in worrying about bugs in the IR until you've ruled out type errors as a result of the various frontend desugaring phases by running the type checker after each frontend phase - but of course there could be a bug in IR generation or IR type-checking.

We should of course instrument the frontend to make it easier to run the type checker after frontend desugaring phases... I think @frank-emrich is planning to do that at some point.

**Comment by slindley** [comment]
That's *not* subeffecting! It's just plain old instantiation. There's no need for `Ir.Coerce`, which should be used when you write an *explicit* upcast.

There's little point in worrying about bugs in the IR until you've ruled out type errors as a result of the various frontend desugaring phases by running the type checker after each frontend phase - but of course there could be a bug in IR generation or IR type-checking.

We should of course instrument the frontend to make it easier to run the type checker after frontend desugaring phases... I think @frank-emrich is planning to do that at some point.

**Comment by frank-emrich** [comment]
Arrg, I keep forgetting about the effect variables hidden in -> and ~>.

**Comment by SimonJF** [comment]
^ Me too. D'oh! Changed the title to reflect the actual problem.

I believe this also manifests itself in `spawn`, too: it's possible to write `spawn { debug("Hello!") }`, but `spawn { "Hello!" }` is ill-typed. I believe this is for the same reason (since the type of `spawn` has the `~@` arrow).

**Comment by jstolarek** [comment]
> There's little point in worrying about bugs in the IR until you've ruled out type errors as a result of the various frontend desugaring phases by running the type checker after each frontend phase 

Running typechecker after each frontend phase does not change anything here (yet!). At the moment Links typechecker really accepts this program as correct. That being said turning on `show_quantifiers` gives a better error message:

```
***: IR Type Error: Type mismatch:
 Expected:
  forall a::Row.() ~a~> ()
 Actual:
  () ~a~> ()
occurring in IR binding:
(Ir.Let ((230, (forall a::Row.() ~a~> (), "bar", Var.Scope.Global)),
   ([], (Ir.Return (Ir.TApp ((Ir.Variable 229), [{ |wild|a }]))))))
```

**Comment by slindley** [comment]
Well now that frontend desugaring is more robust it is clear what is going on here. The type variable binding that appears in the sugar is incorrectly discarded when we translate to the IR. This is evident if you compare the `Val` and `Fun` cases of the `eval_bindings` function in `Sugartoir`. The fix should be relatively straightforward.

**Comment by jstolarek** [comment]
Similar errors arise with other programs, e.g.:
```
fun (x) {x}
```
gives:
```
Continuing after IR Type Error:
Type mismatch:
 Expected:
  forall a::(Any,Any),b::Row.(a::Any) -b-> a::Any
 Actual:
  (a::Any) -b-> a::Any
occurring in IR binding:
(Ir.Let (
   (232,
    (forall a::(Any,Any),b::Row.(a::Any) -b-> a::Any, "it", Var.Scope.Global)),
   ([], (Ir.Return (Ir.Variable 231)))))
```
Same for `fun (x) {<a>{x}</a>}` and `fun (f,g) {fun (x){f (g(x))}}`.
