### ISSUE TITLE
Introducing git and code conventions

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#63]
I would like to suggest introducing some working conventions for Links project:
- **Clean source code from trailing whitespaces.** These have no semantic meaning for humans or compilers but have meaning for source control systems like git. I would be radical here and suggest that once all major branches are merged and the Gorgie release is made we should just remove all trailing whitespace in one go. Once we've done that we could install a git hook that prevents pushing trailing whitespaces to the repository to make sure they are not re-introduced.
  
  If you want Emacs to highlight trailing whitespaces add these two lines to your `.emacs` file:

```
(setq-default show-trailing-whitespace t)
(setq-default indicate-empty-lines t)
```
- **Stop using merge commits.** Looking at the git history I see that the current convention is to use merge commits. I think this is a Bad Thing as it totally obscures commit history. Firstly, I don't think it is really possible to follow a history that looks like this:

![1](https://cloud.githubusercontent.com/assets/1597921/18555816/23dc67f6-7b61-11e6-8c75-e3d92b2b7157.png)

  Secondly, it is not possible to figure out what commits do. Take for example commit 5786aa191b30478254f017be8629c076c2ba83b1. It introduces a lot of changes in the source code but the commit message gives me (or any of you in six months) no clue as to what these changes are about. It only mentions that some branch was merged but that's not really useful - merged branches usually get deleted and following what work was done on a deleted branch is non trivial (at least to me). So I would propose to stop using merge commits and start using `git rebase` + `git merge --ff-only`.
# TODO
- [ ] set "rebase merging" strategy as the default. This has to be done in repository settings to which I do not have access. In this way "rebase merging" will be the only way to merge pull requests. To change this go to Settings -> Options -> Merge button and untick "Allow merge commits" and "Allow rebase merging".

**Comment by jamescheney** [comment]
These both sound like reasonable things to me.  I think we have generally been using whatever the default git/github behavior is out of ignoramce (at least on my part) - using git well seems to require more conscious effort than svn.  I think the main thing needed is to make instructions explaining how to do the right thing (not just mentioning the correct commands that someone who knows what they are doing would use), and stick them on the wiki somewhere.

**Comment by jstolarek** [comment]
>  I think the main thing needed is to make instructions explaining how to do the right thing

Certainly. I can prepare such instructions. I just wanted to be sure that people would be willing to follow them.

**Comment by fehrenbach** [comment]
I usually follow the approach "git history is an accurate history of development, with merges and WIP commits and wonky commit messages" rather than the approach "git history is the pristine, idealized account of how things should have been done if people knew what they were doing in the first place". But to be honest, this is more because it means I get to use "whatever the default git/github behavior is" and not have to squash and rebase and whatnot.

I'm happy to rebase if you, or anyone else, care enough.

However, this is just wrong:
> Secondly, it is not possible to figure out what commits do. Take for example commit 5786aa1.

The information you're looking for is still there. Merge commits give *additional* information. 5786aa1 has "2 parents 270564b + 8b1cea4" and clearly the changes in the merge are for adding "--path for specifying location to look for files".

+1 for whitespace cleanup!

**Comment by jamescheney** [comment]
As we just discussed, I think adoption / enforcement of any conventions will have to be a consensus-driven process, but I think the obstacle up to this point has been inertia/busyness on the part of everyone rather than disagreement that it would be a good idea to establish some conventions.

Some of us attended part of a recent Agda Implementors' Meeting where there was some discussion of Git usage conventions, but I don't think there was any further progress on this.

**Comment by jstolarek** [comment]
I have started a wiki page [here](https://github.com/links-lang/links/wiki/Working-conventions). It currently describes how to work with git branches to avoid merge commits and tells how to configure Emacs to highlight trailing whitespace. Obviously it is not a fully fledged git tutorial and assumes some level of familiarity with git. If you find the instructions lacking please complain and I will extend them. One topic I have omitted is cherry picking (picking single commits from one branch and applying them onto another branch). Yell if you want this on the wiki.

I am leaving this issue open as a reminder to fix the trailing whitespace issue after the release.

**Comment by SimonJF** [comment]
I'm definitely happy to rebase before I merge bigger features into sessions.

-1 from me on the outlawing of merge commits at the moment. It seems (even after reading your wiki page) that it's a bit of a faff to avoid merge commits, and I'm sure I'd end up accidentally introducing one anyway. Additionally, would I be right in thinking that outlawing merge commits would make it so that it's difficult to use GitHub's PR system from the website?

**Comment by jstolarek** [comment]
> -1 from me on the outlawing of merge commits at the moment

Why "at the moment"? I mean, will you be OK with this at some point in the future?

> It seems (even after reading your wiki page) that it's a bit of a faff to avoid merge commits

Can you please elaborate what you mean by that?

> would I be right in thinking that outlawing merge commits would make it so that it's difficult to use GitHub's PR system from the website?

I believe yes - you would have to do that on the command line.

**Comment by yallop** [comment]
GitHub has recently added support for [squashing](https://github.com/blog/2141-squash-your-commits), which doesn't create a merge commit.

**Comment by SimonJF** [comment]
> Why "at the moment"? I mean, will you be OK with this at some point in the future?

Well, I'm a little undecided -- merge commits didn't seem like enough of a problem to me to warrant the additional workflow (although it could probably be easily automated). Doing a little reading though, not having merge commits seems to be a popular practice.

Squashing looks like an interesting solution and would allow us to keep web-based PRs, which is great. Thanks for the pointer!

**Comment by jstolarek** [comment]
@SimonJF, I extended the wiki by describing how to turn on `--ff-only` flag by default. In this way it will always be on, so you don't need to worry that you forget it accidentally. This still requires you to do some extra work of manually rebasing and merging. I personally consider this extra time needed to do this to be an investment - you do some more work now to save yourself from work in the future when it comes to tracking which commit introduced some critical bug.

@yallop, that's true but I personally prefer not to have automatic tools modifying my commits. For example, what if I really want to merge in 3 separate commits as a single PR? How is my commit message changed when I use github squashing? Again, IMO squashing is something that is best controlled by the programmer.

**Comment by jstolarek** [comment]
Just a bit more rationale behind this.

> merge commits didn't seem like enough of a problem to me

You're right. They are not a problem as long as you're working on a small project. They become a problem the moment project gets bigger and you need to start digging in the history. I guess `git bisect` is the primary use case here. With merge commits [it is really hard to use](http://stackoverflow.com/questions/17267816/git-bisect-with-merged-commits).

**Comment by yallop** [comment]
> For example, what if I really want to merge in 3 separate commits as a single PR? 

GitHub has just [announced support](https://github.com/blog/2243-rebase-and-merge-pull-requests) for this.

**Comment by jstolarek** [comment]
Brilliant! This is exactly the workflow that I described.

**Comment by jstolarek** [comment]
May I suggest that once the sessions+shreading branch is merged (#69) we set the "rebase merging" strategy as the default? This has to be done in repository settings to which I do not have access. In this way "rebase merging" will be the only way to merge pull requests. To change this go to Settings -> Options -> Merge button and untick "Allow merge commits" and "Allow rebase merging".

**Comment by SimonJF** [comment]
Fixed your permissions, so you should have those options now.

**Comment by jstolarek** [comment]
Thanks! All is fine now.

**Comment by jamescheney** [comment]
Shall we close this issue?  It does not look like "rebase merging" is the default yet, though (and I think it would be good to continue to allow "squash merging" on a case-by-case basis).
