### ISSUE TITLE
Weird webserver behaviour in the REPL

### ISSUE THREAD

**Issue by SquidDev** [links-lang/links#634]
Attempting to `@load` a file which calls `servePages` will start a server, but loading the page produces the following error:

```
Links Error

***: Error: Links_core__Notfound.NotFound("1949 (in Map.find)")
```

#### Reproduction steps
Create a `serve.links` file.
```
fun main() {
  addRoute("/", mainPage);
  servePages()
}

main()
```

The `mainPage` function can either be defined in the REPL before loading `serve.links`, or as part of the file.
```
fun mainPage(_) { page <#>Test page</#> }
```

Run `@load "serve.links";` and visit `localhost:8080`. You should see the above error message.

Curiously, this behaviour is not exhibited in these cases:
 - `@load`ing the file without the call to `main`, and calling it from the the REPL.
 - Running `{ addRoute("/", mainPage); servePages() }` directly from the file or REPL.

**Comment by dhil** [comment]
Closing as I can no longer reproduce this issue. I suppose it has been solved by one of the many runtime patches.
