### ISSUE TITLE
Quantifier equivocation

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#666]
Thanks to #662 quantifier lists are now immutable, but this PR also changes the behavior of quantifiers so that the outer quantifiers are not hoisted/normalized up to the top of the type in a single list.  This means that 

`forall a. forall b. ...` 

and 

`forall a, b. ...`

are treated differently, internally the former is `ForAll([a],ForAll([b],...))` while the latter is `ForAll([a,b],...)`.  This is not a distinction we want to make.  I think we should either enforce that quantifier lists of neighboring `ForAll`s are merged, by establishing and maintaining this invariant using a smart constructor or something, or as in #662 perhaps restore the hoisting behavior in unification so that this difference is invisible.  (However, the latter seems more likely to lead to complications for TApp/TAbs generation and typed IR generation.)

**Comment by jamescheney** [comment]
The issue of the beast. 😈

**Comment by SquidDev** [comment]
We currently have a somewhat smart constructor - `Types.for_all` - which constructs a forall and then uses `concrete_type` to collapse adjacent quantifiers.

However, I don't know if there's ever a time when we'll infer `forall a. %` for some term, and then unify that flexible type variable with another forall further down the line - meaning that the two quantifiers won't be (at least immediately) merged.

**Comment by jamescheney** [comment]
I think that can happen in pathological cases, certainly in the presence of type annotations (we had to think about this kind of case carefully in the paper!)

Probably we should check with @slindley when he's back.

**Comment by slindley** [comment]
That case is ruled out because `forall a.%` can only arise due to a type annotation, in which case the flexible type variable must be monomorphic. A fundamental property of FreezeML is that we never guess polymorphism. This property is enforced by maintaining the invariant that no polymorphic flexible type variables ever appear in the type environment.

**Comment by jamescheney** [comment]
I think we agreed that this issue describes undesrable behavior but as far as we know this is resolved by already-made changes in #662.  Closing.
