### ISSUE TITLE
"Incompatible effects" IR typechecking error

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#697]
Some prelude functions (`map`, `concatMap`, `swap`, `mapi`) cause an "incompatible effects" IR typing error:

```
Incompatible effects; Allowed:
|a
actual effects:
wild|a
occurring in IR tail computation:
(Ir.Apply ((Ir.Variable 242), [(Ir.Variable 246)]))
```

**Comment by jamescheney** [comment]
The error in `swap` seem to be as a result of the unsafe signatures on concatMap, map etc. not being taken into account in the IR.  Thus, they require their higher-order arguments to be wild (which means, "must do something with the wild effect").  There may be some additional problem on top of this, for example perhaps the type annotations on the functions that we get after desugaring concatMap are also wrong, but fixing #691 should happen first.

There doesn't seem to be an error with `mapi` at this point.

**Comment by jstolarek** [comment]
>  fixing #691 should happen first.

Yes, I fully agree. That's why this ticket has not been worked on.

> There doesn't seem to be an error with mapi at this point.

Good catch. I made a horrible mistake of not adding a regression test when I reported this bug - this would allow to catch such unintentional fixes right away when they happen. I'm in a process of fixing this now, i.e. adding regression tests for other open typed IR tickets where we know the code is not expected to work.

**Comment by jstolarek** [comment]
Ok, I seems that both `mapi` and `swap` work as expected. It is possible to bypass `concatMap` errors in `swap` by supplying an empty definition of `concatMap` that does not trigger errors related to unsafe signatures. I'm closing this ticket since I have no means of reproducing the original error message on these functions. On the other hand the error messages generated for unsafe signatures have evolved and are now similar in meaning to error message reported in this ticket:

```
Type error: Using the recursive variable
    `concatMap's
makes this term wild
    ``Effect (({},
          Point @ 0x7f26a14d5288 `Var ((347,
                                        (CommonTypes.Linearity.Unl,
                                         CommonTypes.Restriction.Any),
                                        `Rigid)),
          false))'             (CommonTypes.Linearity.Unl,
but the currently allowed effects arenTypes.Restriction.Any),
    ``Effect (({wild => `Present (`Record (({}, Point @ 0x7f26a12fc288 `Closed,
                                       false)));
           },
          Point @ 0x7f26a14a3a80 `Var ((370,x7f26a12fc288 `Closed, false))); },
                                        (CommonTypes.Linearity.Unl,
                                         CommonTypes.Restriction.Any),
                                        `Flexible)),ion.Any),
          false))'             `Flexible)),
In expression: concatMap.
 could not be unified because the former is rigid and the latter contains fields not present in the former, namely `wild'.
```

Anyway, I'm closing this ticket and annotating #691 to make sure we replace dummy definitions of `concatMap` used in tests with a proper definition once unsafe signatures work.
