### ISSUE TITLE
***: Error: Links_core.Utility.Disk.AccessError("") when using DB driver from OPAM install on 0.9

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#706]
Using the installed version of Links (try pinning it) will result in the above error. I have observed this error on Wilmer's and Sid's machines, necessitating source installations. I have also reproduced it on a fresh VM.

This is something to do with the interplay between OPAM and the dynamic linking code, and is of course a blocker for 0.9.

**Comment by jamescheney** [comment]
Huh.  So the CI wasn't catching this because it is a misconfigured install - `AccessError("")` seems to suggest that somewhere we are asking `of_path` or `of_directory` to look for the database driver code in the current directory, where it isn't.  It looks like `of_path` and `of_directory` are called in exactly one place but `AccessError`s are handled for the latter.

**Comment by jamescheney** [comment]
So it seems that `of_path` is being called from `databaseDriver` with argument `""`, and raising the exception.  Is it just a matter of handling the exception in `Glob.files` and returning `[]`?  The workaround to look in the place opam puts the library files isn't tried unless `Glob.files` returns `[]`.

**Comment by SimonJF** [comment]
Yes, I've come to a similar conclusion. I think the issue is the following code in `basicsettings.ml`:

```
module DatabaseDrivers = struct
  let default_path_string () =
    let open Utility in
    let module Glob = Glob.Make(DefaultPolicy) in
    let _build = Filename.(dirname (dirname (dirname Sys.argv.(0)))) in
    let install = Filename.concat _build "install" in
    let files =
      try Glob.files install (Str.regexp "links_[A-Za-z0-9]+_dependencies\\.json$")
      with Disk.AccessError _ -> []
    in
    let paths = List.map Disk.File.dirname files in
    String.concat ":" paths

  (** List of directories where to look for database drivers, split by ':'
      Initialized to point to where the drivers are compiled to if building in the current directory **)
  let path = Settings.add_string ("db_driver_path", default_path_string (), `System)
end
```

The path will always end up as "".  Now, this is used in `databaseDriver.load` as follows:
```
let load driver_name =
  let path =
    String.split_on_char ':'
      (Settings.get_value Basicsettings.DatabaseDrivers.path)
  in
  Loader.load ~path driver_name
```

Then, `split_on_char` results in the initial path of `[""]` instead of `[]`, which causes the error. The fix should simply be to special-case the empty string, since it's not a valid path. Trying now; will let you know how I get on.

**Comment by SimonJF** [comment]
OK -- this was indeed the problem. Fix incoming.

**Comment by jamescheney** [comment]
Just out of curiosity, is there a way to back-patch v0.8 (or create a new version v0.8.1) to include this fix?  Otherwise, it'd be nice to retire or deprecate v0.8 somehow, just so that we don't potentially get people complaining about this bug in the future...

**Comment by SimonJF** [comment]
I think this particular error was introduced between 0.8 and 0.9. But your comment stands, as there was a different bug that I ran into on Sid's stock install.

I'm not entirely sure which patch fixed the 0.8 bug, and how much other stuff would be pulled in. If you like, I could try. I think deprecating v0.8 would be the better option, once 0.9 is accepted by the `opam-repository` maintainers.

**Comment by jamescheney** [comment]
Ah, OK.  Happy with path of least resistance.

**Comment by dhil** [comment]
Yes, this regression was introduced between the release of 0.8 and 0.9.
