### ISSUE TITLE
Implement conditional assertions

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#71]
I `types.ml` I stumbled upon:

``` ocaml
  let combine (name, (flavour, kind, count)) (flavour', kind', scope) =
(*     assert (flavour = flavour'); *)
(*     assert (kind = kind'); *)
```

I assume that these are commented out for performance reasons. This gives me the idea that we could create assertion macros, which would compile conditionally. In a release version such assertions would be a no-op, while in a development version they would contain actual assertions with file name and line number. This would require a CPP pre-processor, e.g. [CPPO](https://github.com/mjambon/cppo). Is this a good idea? Is an extra dependency on CPPO acceptable?
# TODO
- [ ] add a flag to `_oasis` file to enable `-noassert` conditionally
- [ ] make sure that when Links is distributed to users via OPAM `-noassert` is enabled. For us as developers it should be enabled by default.

**Comment by yallop** [comment]
The ` -noassert` compiler option is also worth considering.

**Comment by jstolarek** [comment]
Ha! This will actually suffice, given that it still compiles `assert false`.

I am leaving the ticket open as a reminder to make `-noassert` conditionally available in the build system. Related: #61 and #62.

**Comment by jamescheney** [comment]
We determined that by default we will leave assertion checking enabled in releases until it becomes clear that this is a problem, so closing.
