### ISSUE TITLE
Should type variables be unique?

### ISSUE THREAD

**Issue by frank-emrich** [links-lang/links#734]
A question that has been bothering me for a while (and came up again in #693) is whether or not we require that each type variable may only be bound once in a program?

As a further refinement, we would then have to decide whether type variables bound by \forall may overlap with those bound by \Lambda. More concretely, in
```let f : forall a. a -> a = /\ a. fun (x:a) -> x```
do we enforce that the type variable `a` bound by forall coincides with the one bound by \Lambda, do we accept it (without requiring it), or do we forbid it?
In the the second and third case, the following program would be a valid alternative:
```let f : forall a. a -> a = /\ c. fun (x:c) -> x```

I'm using some explicitly typed pseudo-syntax here, but the question arises both for the frontend and the backend.

Currently, I frequently see cases like 
```let f : forall a. a -> a = /\ a. fun (x:a) -> x```,
where the quantifiers in the annotations coincide with the `tyvars` in the function, so the third option would probably require some work.

On the other hand, I have seen several cases where IR type-checking failed because in the IR program, the type variables bound in annotations were mixed up with those used in the `tyvars`.

Finally, looking at `instantiate.ml`, it seems like this code was written with the assumption in mind that all type variables are unique. Applying the substitution [b/a] to
(forall a. a -> a) -> Int would yield (forall a. b -> b) -> Int, which is bad.

I simply feel like clarifying this will stop people from making different assumptions about this and we could then encode it as a checker pass between transformations.

**Comment by slindley** [comment]
We currently make no assumption that different bound type variables have distinct names. What you describe sounds like a bug in `Instantiate` that should be fixed... but I don't know if it ever manifests in practice.

**Comment by jstolarek** [comment]
> We currently make no assumption that different bound type variables have distinct names. 

I think we sort of do. In the process of fixing #693 I discovered that checking whether quantifiers escape their scope (#678) might not work correctly if a same type variable is bound multiple times. Consider this lengthy snippet:

```
(Sugartypes.Fun
   { Sugartypes.fun_binder = ("and", forall 380::Row.([Bool]) ~380~> Bool);
     fun_linearity = CommonTypes.DeclaredLinearity.Unl;
     fun_definition =
     ([380::Row],
      ([[(Sugartypes.Pattern.Variable ("l", [Bool]))]],
       (Sugartypes.Block
          ([],
           (Sugartypes.FnAppl (
              (Sugartypes.TAppl ((Sugartypes.FreezeVar "all"),
                 [((Sugartypes.Datatype.Type
                      (Sugartypes.Datatype.TypeVar ("$none", None, `Rigid))),
                   (Some Bool));
                   ((Sugartypes.Datatype.Type
                       (Sugartypes.Datatype.TypeVar
                          ("$none", None, `Rigid))),
                    (Some { |380 }))
                   ]
                 )),
              [(Sugartypes.Block
                  ([(Sugartypes.Fun
                       { Sugartypes.fun_binder =
                         ("_fun__g1", forall 380::Row.(Bool) ~380~> Bool);
                         fun_linearity = CommonTypes.DeclaredLinearity.Unl;
                         fun_definition =
                         ([380::Row],
                          ([[(Sugartypes.Pattern.Variable ("x", Bool))]],
                           (Sugartypes.Block ([], (Sugartypes.Var "x")))));
                         fun_location = CommonTypes.Location.Unknown;
                         fun_signature = None;
                         fun_unsafe_signature = false; fun_frozen = true })
                     ],
                   (Sugartypes.TAppl ((Sugartypes.FreezeVar "_fun__g1"),
                      [((Sugartypes.Datatype.Type
                           (Sugartypes.Datatype.TypeVar
                              ("$none", None, `Rigid))),
                        (Some { |380 }))]
                      ))));
                (Sugartypes.Var "l")]
              ))))));
     fun_location = CommonTypes.Location.Unknown; fun_signature = None;
     fun_unsafe_signature = false; fun_frozen = true })
],
```

Here variable `380` bound in the signature of `_fun__g1` is consider to escape its scope because it is used in the definition of `and` (which also binds `380`). But if I freshen variables in the signature of `_fun__g1` so that the type becomes `forall 574::Row.(Bool) ~574~> Bool` all is fine - and it doesn't matter that we repeatedly bind `380` in several different terms.

**Comment by slindley** [comment]
I won't be surprised if there are places in the code that do make this assumption, but if they do then that's probably a bug. Unless and until we come up with a compelling reason to enforce a uniqueness invariant on bound type variables everywhere we should assume that they may not be distinct.

**Comment by jstolarek** [comment]
I think that type variable shadowing at the source level is perfectly fine, but when it comes to internal representations as integers each binder should really be unique. @slindley, if we assumed it is OK to have non-unique type variable binders then how would you go about doing a check like the one in #678? As I said, I've run into a situation where this leads to a bogus report on variable escaping its scope but I can't imagine how this could be fixed without assuming uniqueness of identifiers.

I totally understand that this is not an invariant we are making at the moment and the code we write cannot rely on it in any way. And if it does, clearly that is a bug given the current design. However, I am arguing this is an invariant worth having.

**Comment by jamescheney** [comment]
I agree taht ensuring that the numerical variables in teh IR are unique is a reasonable design choice, but based on what @slindley is saying, it sounds like it isn't a design choice that's been consciously made (rather than incorrectly assumed).

I think the question in the title of this issue is a simple yes/no, with next actionsL:
- if YES then someone should implement a type variable uniquifier or at least a check so that failure to maintain this invariant results in a clear internal error highlighting a problem
- if NO then we need to debug the places where this assumption is made.  Having a uniquifier might helpful for this as well.

**Comment by slindley** [comment]
The answer for now is a NO.

**Comment by frank-emrich** [comment]
Indeed. This was mostly relevant for #774, which now comes with a new facility for freshening quantifiers where needed.
