### ISSUE TITLE
Create links-dev mailing list

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#74]
We need a mailing list for Links developers (links-dev@inf.ed.ac.uk? links-devs@inf.ed.ac.uk?). At the moment set of users and set of developers overlap, but hopefully they will diverge at some point. List should be open for anyone to subscribe.

# TODO
  * [x] create a list
  * [x] add its address to `_oasis` file as contact address to authors

**Comment by jstolarek** [comment]
Once we have a developer mailing list we should update in in `_oasis` file (see #62 and #78).

**Comment by jamescheney** [comment]
Done, created links-dev@inf.ed.ac.uk

**Comment by jstolarek** [comment]
I think it would be a Good Thing to make archives of the list publicly available.

**Comment by jamescheney** [comment]
I've made the links-dev archives public.
