### ISSUE TITLE
Using httpaf instead of cohttp?

### ISSUE THREAD

**Issue by hengestone** [links-lang/links#747]
Would it be possible to switch to using the httpaf web server?

I.e. is there anything structural that would make switching a bigger refactor than it looks like?

**Comment by dhil** [comment]
It has actually been considered before (c.f. #241).

Personally, I would like to migrate to http/af, however, last I checked the websocket support provided by http/af was rather limited and work-in-progress. I think we would require a stable websocket interface on top of http/af before attempting to migrate.

**Comment by hengestone** [comment]
Ah, that makes sense, thanks!
