### ISSUE TITLE
Create Links maintainer email

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#75]
Before we publish Links to OPAM we need an email address that allows to reach Links maintainers. This shouldn't be a discussion list, since it must be something that does not require registration. Perhaps we can have an email alias that forwards the email to developers list (this avoids the need of having to subscribe the list)? Or should we just have a single person that should be contacted regarding package maintenance?

Part of #61

# TODO
  * [ ] create email alias or appoint a single person?
  * [ ] add email address to `_oasis` file as contact address to maintainer

**Comment by jstolarek** [comment]
Once we have maintainer email we should update in in `_oasis` file (see #62 and #78).

**Comment by jamescheney** [comment]
I've asked for a mailing list "links-maintainers@inf.ed.ac.uk" to be created, which we can use.

**Comment by jstolarek** [comment]
Have we been automatically subscribed to the list or should we do this individually?

**Comment by jamescheney** [comment]
I've invited people now, closing.  Anyone else who wants to be invited, let me know.  @yallop?

**Comment by jstolarek** [comment]
After some thinking I came to conclusion that it makes more sense to actually have concrete people appointed as maintainers. I'm volunteering for this but it would be good to have one more person appointed as a maintainer.
