### ISSUE TITLE
Regexes in nested queries do not work

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#754]
Looking at the dictionary suggestion example, (`examples/dictionary/dictSuggest.links`), we can use regex syntax to translate to SQL `LIKE` predicates. However, this is unsupported when using nested queries.

MFE:

```
var db = database "test";

var testTable = table "testTable" with (field: String) from db;

query {
  for (x <-- testTable)
    where (x.field =~ /^{"foo"}.*/)
    [x]
}
```

yields

```
   (Query.Lang.Concat
      [(Query.Lang.Singleton
          (Query.Lang.Variant ("StartAnchor", (Query.Lang.Record {}))));
        (Query.Lang.Singleton
           (Query.Lang.Variant ("Quote",
              (Query.Lang.Variant ("Simply",
                 (Query.Lang.Constant (CommonTypes.Constant.String "foo"))))
              )));
        (Query.Lang.Singleton
           (Query.Lang.Variant ("Repeat",
              (Query.Lang.Record
                 {1 => (Query.Lang.Variant ("Star", (Query.Lang.Record {}))); 
                 2 => (Query.Lang.Variant ("Any", (Query.Lang.Record {}))); })
              )))
        ])
   ))
```

**Comment by SimonJF** [comment]
In the short term, I will unblock myself by implementing #538 as I'm not too familiar with the intricacies of the normalisation algorithm.

**Comment by jamescheney** [comment]
This is a little surprising to me, since the query itself is flat, we should take a look.  It may be a shallow problem, perhaps just due to not doing the regex translation when shredding is enabled.
