### ISSUE TITLE
Range notation in `for` comprehensions results in nontermination

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#755]
Range notation (`..`) in a query block causes nontermination:

```
links> query { for (x <- [1..6]) [(num=x)] };;
compiling to IR
compiled IR
```

**Comment by jamescheney** [comment]
The right thing happens if the list is hoisted out:
```
links> var l = [1..3];
l = [1, 2, 3] : [Int]
links> query {for (x <- l ) [(num=x)]};
[(num = 1), (num = 2), (num = 3)] : [(num:Int)]
```
so the problem is just that the normalizer is not correctly expanding out the range notation to a list value.  

I'll take a look.

**Comment by jamescheney** [comment]
[I tried to comment this earlier but it got lost]

As per #760 I think it should be an error to do `[n..m]` inside a query.  Ranges expand out to calls to the (recursive/wild) `intRange` function and inside a query, the arguments need not be constants.  For example it's not immediately obvious what the SQL equivalent of
```
query { for (x <-- r) [1..(x.n)] }
```
is.  In the specific case above, I expect the recursive definition of `intRange` is just being inlined forever.

As a special case, we could handle `[n..m]` when `n` and `m` are literal integers, by desugaring them to the equivalent list.  But hoisting ranges out of queries to force this evaluation to happen earlier seems like a perfectly fine workaround in this case, and also allows using lists constructed by ranges of dynamically-computed integers, as long as they do not depend on database data.
