### ISSUE TITLE
Promoting previously inferred types to signatures vs. behavior of recursive functions

### ISSUE THREAD

**Issue by frank-emrich** [links-lang/links#773]
The following properties seem to be at odds with each other:

1. When `TypeSugar` runs again after a previous run, the types stored in binders (put there by the previous run) are treated as if they were type signatures to check against.

2. Polymorphic functions are typed differently based on whether they have a type signature or not. If they do, they may be used polymorphically in their bodies, if they don't, they can only be used monomorphically inside.

3.  The transformation `DesugarInners` runs after type-checking and treats all (on the outside) polymorphic recursive functions polymorphically in their bodies as well. Hence, in their bodies it inserts the necessary type applications around usages of itself/other recursive functions from the same group. This step essentially removes the distinction between inside and outside in terms of typings, as the IR expects.

Together, these three properties mean that a problem can arise when `TypeSugar` is run again, but before `DesugarInners` has run. In this situation, by the first point, the recursive functions have signatures and are treated polymorphically inside. However, `TypeSugar`  should then notice that the necessary type applications are missing, because they are only inserted later on by `DesugarInners`.

The easiest solution seems to be to make sure that `DesugarInners` runs immediately after `TypeSugar`. Currently, however, `DesugarCP` runs between `TypeSugar` and  `DesugarInners`. We should make sure if we can swap `DesugarCP` and  `DesugarInners`.

**Comment by jstolarek** [comment]
> The easiest solution seems to be to make sure that DesugarInners runs immediately after TypeSugar.

I think it would be best if `TypeSugar` produced a well-typed AST. The solution above wouldn't address that - it still would be illegal to run typechecker twice in a row.

**Comment by slindley** [comment]
`TypeSugar` does produce a well-typed AST.

The only problem is that the type inference algorithm doesn't properly deal with the "extras" component of the generated inner type annotation - which specifies how to map the outer quantifiers to the inner ones. If we ensure that `DesugarInners` runs immediately after the first call to type inference then that won't matter - after that unannotated functions should never be encountered again by the type inference algorithm.

If we wanted to be a bit more robust then we could fix `DesugarInners` to indicate that the "extras" mapping has been applied and write some (redundant) code to deal with type inference in the case that the extras mapping has not yet been applied. Alternatively, it would also be perfectly reasonable to simply fail in that case as we can assert that it should never happen. We can mark the extras mapping as having been applied by setting it to the empty list (and tweaking `DesugarInners` accordingly).

(The name "extras" is somewhat contrived and should perhaps be changed to something more informative - it used to make more sense when it performed a slightly different function.)

**Comment by jamescheney** [comment]
> We should make sure if we can swap DesugarCP and DesugarInners.

I tried this and all tests seem to pass (branch `issue773`).  However, all tests also pass if we simply comment out the `desugarCP` desugaring pass. 

Looking at `desugarCP` and `desugarInners` I don't see an obvious conflict, but since we have no tests involving `CP` syntax, it is hard to be sure that these passes commute.
