### ISSUE TITLE
Inconsistent order of return arguments between TYPE_VISITOR and other traversals

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#776]
`SugarTraversals.fold_map` and `TransformSugar.transform` return `self` object as the first component of the returned tuple, but `Types.Transform` (of type `TYPE_VISITOR`) returns `self` as the last component. We should make this consistent by swapping order of return components in `TYPE_VISITOR`.

**Comment by frank-emrich** [comment]
Indeed, that's very annoying, put probably takes a lot of manual effort to fix

**Comment by jstolarek** [comment]
I'll fix that once #774 is done.

**Comment by jamescheney** [comment]
After spending ~30 minutes on this (#904) I noticed that the IR traversals (signature IR_VISITOR) also have the same argument order as TYPE_VISITOR.  Does that mean we also want to permute them to be consistent with the frontend syntax traversals?  If so, I can probably go ahead and do that. while I'm at it.

**Comment by jstolarek** [comment]
>  Does that mean we also want to permute them to be consistent with the frontend syntax traversals?

That sounds like a good idea. Assuming nobody is doing anything with that part of the code and a sudden massive refactoring won't affect their work.
