### ISSUE TITLE
Create .merlin file

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#79]
It might make our like easier if we configure Merlin - see @Drup's hints in #78 and tutorials: [here](https://github.com/the-lambda-church/merlin/wiki/project-configuration) and [here](https://opam.ocaml.org/blog/turn-your-editor-into-an-ocaml-ide/).

**Comment by jstolarek** [comment]
Sam says in the past there were problems with setting up Merlin to work with deriving.

**Comment by Drup** [comment]
Indeed. But `ppx_deriving` works fine, so time to switch :3

**Comment by jstolarek** [comment]
Unassigning myself - not working actively on this in foreseeable future.

**Comment by jamescheney** [comment]
This will be superseded by merging #265, since jbuilder supports generating merlin files.

**Comment by jamescheney** [comment]
Now done by #265
