### ISSUE TITLE
Azure Mac CI breaks during database setup

### ISSUE THREAD

**Issue by frank-emrich** [links-lang/links#792]
This [build](https://dev.azure.com/links-lang/links/_build/results?buildId=621) failed repeatedly with the following error. Those changes are unrelated to DB-stuff; I guess master would equally fail.

```
cmnd=psql -h localhost -p 5432 -v ON_ERROR_STOP=1 -q -d links -f tests/shredding/travel_portal.sql
psql:tests/shredding/travel_portal.sql:1: NOTICE:  table "agencies" does not exist, skipping
psql:tests/shredding/travel_portal.sql:2: NOTICE:  table "externaltours" does not exist, skipping
psql:tests/shredding/travel_portal.sql:9: ERROR:  syntax error at or near "OIDS"
LINE 6: ) WITH OIDS;
               ^
```

Maybe the mac setup uses a new version of postgres that's not compatible with our script anymore?

**Comment by slindley** [comment]
We should either fix this ASAP or remove the Azure Mac CI.

Is anyone attempting to maintain the Mac CI?

If a Mac user isn't actively maintaining this CI, then I suspect keeping it may cause us more trouble than it's worth.

**Comment by jamescheney** [comment]
As "the"  user of Links on mac, I have had nothing to do with this so far.  I don't think fixing it requires Mac know-how.  I suspect the reason things broke is that the brew postgres package just went to postgres 12.  Pinning a specific stable version that Links is believed to be compatible with (such as 9.5) ought to work.  I'll see if my minimal knowledge/competence to edit the Azure configuration suffices, but if not I don't object to retiring the Mac CI.

**Comment by jamescheney** [comment]
The reason appears to be that prior to Postgres 12, if you wanted OIDs to be added to a table then you have to explicitly say WITH OIDS.  As of version 12, you don't have to say this and it happens automatically, and they retired the now-redundant syntax non-backwards-compatibly.  So, for this exampel to work on both <12 and >=12 versions will require conditional code depending on the Postgres version.

This will presumably also affect the Azure Linux config at whatever point the default version of Postgres you get increases high enough.  At that point, we should probably just stop supporting versions < 12.

**Comment by jamescheney** [comment]
#793 disables the macos CI so that we don't get red X's anymore, but we should rename this issue to "avoid WITH OIDS syntax that postgres 12 is not backwards compatible with" because this problem will arise again with Linux as soon as the default postgres version you get with linux exceeds 12.  (Which to be fair may be several years.)  Once we fix things so that the database code doesn't depend on a nonstandard postgres feature the Mac CI should be re-enabled.

**Comment by dhil** [comment]
I maintain it for the time being until we have made a decision whether we want to keep it or not. See issue #584 (this issue should go there too).

**Comment by frank-emrich** [comment]
Closing this for now  (due to #793), but the underlying issue isn't fixed.
