### ISSUE TITLE
Winestore example can produce a runtime error

### ISSUE THREAD

**Issue by dhil** [links-lang/links#808]
The Winestore example can produce the following runtime error
```
Links Error
***: Runtime error: range: argument less than zero
```
Steps to reproduce:
1. In the "filter wines by" section select:
   - Region: Barossa Valley
   - Wine type: Sweet
2. Click "Show wines"

**Comment by jamescheney** [comment]
This is not a bug in Links, but in the winestore example.

The error message is generated by Links code in `wine.links`, not a runtime error in the Links interpreter (and in particular nothing to do with ranges in queries):
```
fun range(n) {
  if (n < 0) error("range: argument less than zero")
  else if (n==0) [0] else
  range(n-1) ++ [n]
}
```
The line with the `error` call was added to stop the range function diverging if called with a negative argument.

The reason it is being called with a negative argument appears to be 
```
    var numPages = numWines/page_size;
 ....
       {for (i <- range(numPages-1)) {
```
When the number of wines is less than `page_size`, `numPages` is 0 and thus `range` is called with -1.  That is, `numPages` actually calculates the number of full pages of size `page_size`.  Meanwhile, `range` returns the numbers from zero to its argument.  So, in the common case where there is at least one full page, the code doesn't fail but presumably prints one fewer page number than it should; if there isn't a full page then the error is triggered.

**Comment by jamescheney** [comment]
Indeed, the combination region=Barossa Valley and type=Sweet returns only 8 wines, and this is the only region/type filter combination that causes this error:
```
select r.region_name,t.wine_type, count(*) 
from wine w,
	region r, 
	winery x,
	wine_type t
where r.region_name = 'Barossa Valley'
  and w.winery_id = x.winery_id
  and r.region_id = x.region_id
  and t.wine_type_id = w.wine_type
group by r.region_name,t.wine_type
having COUNT(*) < 12
```
returns only this tuple.
