### ISSUE TITLE
Move source files to their separate directory

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#81]
I suggest that we move all the source files into a separate `src` directory to keep the project structure clean.

There was a question yesterday whether this is something that should be done as part of the release or perhaps sometime later. I strongly believe this should be done before the stable release. Once we have an official release we don't want stable and development branches to diverge too quickly. Otherwise backporting bugfixes from development branch to stable branch will be problematic.

**Comment by jamescheney** [comment]
We determined that this should be done after the appserver, modules and any bugfix merges are done but before creating the release.

**Comment by jamescheney** [comment]
Delaying to Dalry.

**Comment by dhil** [comment]
I think we should delay this until whether we decide whether to go with `jbuilder` as our build system, because `jbuilder` will naturally enforce/impose some directory structure.

**Comment by jamescheney** [comment]
Fine with me.  I haven't had time to look at jbuilder yet.

**Comment by jamescheney** [comment]
Anyone know what the next version name after Dalry is?  Or should we tag this "0.7.x"?  I think it would be good to do as a minor version bump since it should not affect the actual behavior of programs, just the build setup.

**Comment by dhil** [comment]
I am happy to go with Dalry 0.7.2. We can reserve the next major version for Simon's sessions work :-)

**Comment by jamescheney** [comment]
Now done by #265
