### ISSUE TITLE
Test script executor leaks memory

### ISSUE THREAD

**Issue by dhil** [links-lang/links#816]
The test script executor (`test-harness`) can leak memory when a test script times out. The reason is that the executor does not perform proper clean up of timed out scripts, allowing their processes to keep running forever. 

Here is a small reproduction `hungry.links`.
```
Hungry
fun f() { 1 :: f() } f()
stdout : () : ()
```
Be careful if you run the above snippet as it will quickly consume all the memory on your machine.
```
$ ./test-harness hungry.tests
!FAILURE: Hungry [TIMED OUT]
1 failures (+0 ignored)
0 successes
$ echo $?
1
$ ps -ef | grep links.exe
joe     15972 15971 99 21:52 pts/1    00:00:18 _build/default/bin/links.exe -e fun f() { 1 :: f() } f()
```
The process is kept alive even after `test-harness` has completed.

**Comment by jamescheney** [comment]
Is this now closed by #821?

**Comment by frank-emrich** [comment]
Yes, apparently the auto-closing isn't triggered from comments, just from the main description of a PR. Learned something new today!

**Comment by jamescheney** [comment]
It seemed to get this right using other examples (e.g. #810/#811).  The NLP is obviously unreliable (like all ML/AI) but it can be explicitly set using the "Linked pull requests" sidebar.
