### ISSUE TITLE
Write a JOSS paper

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#819]
This is something I wanted to bring up during upcoming Links meeting, but since I already did some preliminary work today I thought I'll post a ticket and give everyone a heads-up.  A while back during one of James' group meetings there was a discussion about writing "The Links Paper" and submit it to [Journal of Open Source Software](https://joss.theoj.org/). I want to move forward with that initiative. The goal of JOSS is to publish papers on research software with the intention of having a publication that can be cited when referencing a piece of software.  The idea is that we should have a paper that we can cite whenever we reference Links, instead of referring to the Links webpage or some randomly picked Links paper.  Our JOSS paper can gather all the papers written on Links so far and act as a central hub for anyone seeking further information on Links.

Below is a summary of important [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html):

  * **JOSS papers are only expected to contain a Statement of Need, Summary, Acknowledgements, and References sections.** A "full length" paper is not permitted.
  * 250-1000 words
  * paper written in Markdown format and placed in repo as paper.md (ideally together with software)
  * A summary describing the high-level functionality and purpose of the software for a diverse, **non-specialist audience**.
  * A **clear Statement of Need** that illustrates the research purpose of the software.
  * A list of key references, including to other software addressing related needs.
  * Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.
  * **Acknowledgement of any financial support.**
  * *"we require that authors include in the paper some sentences that **explain the software functionality and domain of use to a non-specialist reader**. We also require that authors explain the research applications of the software."*

My initial work is on the `joss-paper` branch:

  1. `paper.md` contains the paper meta-data (but see TODOs below) and section headers. No content yet.  As you can see the paper is not intended to be long and should not be a technical paper (no typing rules, etc).  I'm hoping someone better at writing than me will pick this up and write up the actual text :-) If not I will start working on this in the near future.

  2. I populated the bibliography in `paper.bib` with the papers listed at http://www.links-lang.org, provided they were listed at [DBLP](https://dblp.uni-trier.de/).  The following papers were not listed in DBLP and are therefore missing from the bib file:

       * [ ] "Lightweight functional session types".  Sam Lindley and J. Garrett Morris. In [Behavioural Types: from Theory to Tools](https://www.riverpublishers.com/book_details.php?book_id=439), River Publishers, 2017.
       * [ ] "Compiling Links Effect Handlers to the OCaml Backend".  Daniel Hillerström, Sam Lindley, and KC Sivaramakrishnan.
       * [ ] "DBWiki: a database wiki prototyped in Links". James Cheney, Sam Lindley, and Heiko Müller. In the proceedings of DBPL 2011.

     @slindley, you are an author on each of these papers.  Could I ask you to add these entries to the bib file?

     If any of you has written a Links paper that is missing from the `paper.bib` bibliography file (other than the 3 papers listed above) **it means it is also missing on the web page**.  It would be best if you could add a missing paper in both the web page and the bib file.  Follow DBLP condensed format when adding entries to bib file, but shorten citations e.g. from `DBLP:journals/pacmpl/FowlerLMD19` to `FowlerLMD19`.

  3. Submission instructions say the paper should:

     > include a list of the authors of the software and their affiliations (...)  Purely financial (such as being named on an award) and organizational (such as general supervision of a research group) contributions are not considered sufficient for co-authorship of JOSS submissions, but active project direction and other forms of non-code contributions are.

     Should we therefore list anyone who ever contributed significantly to Links as an author of the paper?  Below is a list of such people that came to my mind:

       * [ ] Ezra Cooper
       * [ ] Jeremy Yallop
       * [ ] Stefan Fehrenbach
       * [ ] Philip Wadler
       * [ ] J. Garrett Morris

     **Please yell if you believe someone should/shouldn't be on the above list**.  Once we agree on past authors, these people should be contacted and asked for permission to be added as the authors of the paper.

     For now I only listed myself as the author in the metadata, to serve as a template - **please add yourself and your affiliations**.

  4. I went with "Links: Linking Theory to Practice for the Web" as the title because that's what the web page and repo description say.  I was also considering "Links: A Functional Tier-less Web Programming Language". Thoughts?

  5. I made a tentative list of tags - please revise and expand.

  6. The paper needs to acknowledge funding.  Links web page lists several grants but I don't know how to cite them (they probably have some unique identifiers used to identify a funding source).

  7. We should probably also acknowledge contributions of numerous interns. Should we list everyone by name?  (Aside: [ACKNOWLEDGEMENTS](https://github.com/links-lang/links/blob/master/ACKNOWLEDGEMENTS) file has not updated for eleven years.)

Paper preview can be generated [here](https://whedon.theoj.org/).  Reviews are carried out using a github issues.  [Here's a glimpse.](https://github.com/openjournals/joss-reviews/issues/2171)

Currently submissions are suspended at least until April 11 due to COVID situation, but I think we can begin our work and assume submission will be un-suspended at some point.

**Comment by jstolarek** [comment]
Note to self: make sure Links is in scope of JOSS.

**Comment by jstolarek** [comment]
Pre-submission enquiry: https://github.com/openjournals/joss/issues/719

**Comment by jstolarek** [comment]
After discussing with JOSS editors it seems that at the moment Links seems out of scope of JOSS. However, this is largely a matter of how we present Links on the webpage and in the project readme. I'll quote one of the editors:

> Your statement here implies research usage, but the content of the website & repo's README focus on non-research usage, and the research usage seems to entirely be from the team who wrote the software.
>
> In my opinion, to make this something that JOSS would review, the website and README would have to talk about the research aspects of using the software, including kinds of problems that could be researched, and ideally, examples of research publications in those kinds of problems.

So the question is whether we want to address this, that is shift the focus of the reamde an web page from how Links can be used as a web development language to how Links can be used as a PL research testbed. My guess would be that we probably don't want to do that. If so, then we need to give up on the idea of JOSS submission.

**Comment by jamescheney** [comment]
Based on the JOSS response, It looks like we are not doing this; shall we close?

**Comment by jstolarek** [comment]
Yes, this should be closed, though I was waiting for a proper (i.e. not refactoring) Links meeting to follow up on this.

Anyway, I've taken a `.bib` file that I prepared for the purpose of JOSS paper - it contains Links papers listed on links-lang.org - and places it in the `doc/` directory. I think it might be useful.
