### ISSUE TITLE
Don't store database configuration in the repo

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#82]
Sam says that we should not have default database configuration stored in the repo (`tests/database/config`) because different people might have different database setup and should be able to edit database configuration without it being visible to git as a change. We should instead have a `config.sample` with a sample default configuration stored in the repo. Test script should check whether configuration is present and, if it is not, create a default `config` file by copying `config.sample`. I fully agree with this idea.

# TODO

  * [ ] [Update the wiki](https://github.com/links-lang/links/wiki/Running-the-test-suite)

**Comment by jstolarek** [comment]
@slindley, here's an implementation. Is this what you wanted?

**Comment by slindley** [comment]
@jstolarek, that only does part of what is required. The `psql` command should also attempt to use the database arguments from the config file. In particular, if I want to connect to the database as username `foo` then `-U foo` should appear in the arguments to `psql`.
