### ISSUE TITLE
orphaned .links files in tests directory

### ISSUE THREAD

**Issue by frank-emrich** [links-lang/links#827]
I'm currently working on a script that detects .links files in `tests/` that are not mentioned in any .tests file. Of course, there are files where this is not a bug, for example files that contain a non-standard prelude. I have created a whitelisting mechanism for this.

For the following files it wasn't immediately obvious to me whether their creators forgot to add them to some .tests file, if they serve some other purpose or if they can be deleted. Would the people in question question kindly add those files to the respective `.tests` file or let me know if a given file is not a standalone test file (i..e, it's part of a larger test) or if it can be deleted?

- Database stuff (@jamescheney @wricciot ):
tests/database/emptyfun.links
tests/database/empty.links
tests/database/factorials.links
tests/database/unit.links
tests/database/xpath.links
tests/database/xpath-reduced.links
tests/shredding/emptyfun.links
tests/shredding/empty.links
tests/shredding/jrules.links
tests/shredding/organisation.links
tests/shredding/travel_portal.links
tests/shredding/unit.links

- Session stuff (@SimonJF) :
tests/session-exceptions/cancel5-cp.links
tests/session-exceptions/clientCancel10.links
tests/session-exceptions/clientCancel11.links
tests/session-exceptions/clientCancel1.links
tests/session-exceptions/clientCancel2.links
tests/session-exceptions/clientCancel3.links
tests/session-exceptions/clientCancel4.links
tests/session-exceptions/clientCancel5.links
tests/session-exceptions/clientCancel6.links
tests/session-exceptions/clientCancel7.links
tests/session-exceptions/clientCancel8.links
tests/session-exceptions/clientCancel9.links
tests/session-exceptions/clientClosure2.links
tests/session-exceptions/clientClosure.links

- Lens stuff (@rudihorn):
tests/relational-lenses/01_cds.links
tests/relational-lenses/02_cds.links
tests/relational-lenses/03_cds.links

- Modules (@SimonJF  @dhil )
tests/modules/cyclicA.links
tests/modules/cyclicB.links
tests/modules/cyclicC.links
tests/modules/import0.links
tests/modules/import_via_open1.links
tests/modules/moduleB.links
tests/modules/moduleC.links
tests/modules/records.links
tests/modules/switch-test.links
tests/modules/type-res110/bar.links
tests/modules/type-res110/foo.links
tests/modules/varRefA.links
tests/modules/varRefB.links

- Mutuals (@SimonJF ) :
tests/mutual/duplicateFun.links
tests/mutual/unguarded.links

- Distribution (?) stuff, committed by @SimonJF 
tests/distribution/10/test.links
tests/distribution/11/test.links
tests/distribution/12/test.links
tests/distribution/1/test.links
tests/distribution/2/test.links
tests/distribution/3/test.links
tests/distribution/4/test.links
tests/distribution/5/test.links
tests/distribution/6/test.links
tests/distribution/7/test.links
tests/distribution/8/test.links
tests/distribution/9/test.links

**Comment by jamescheney** [comment]
> Database stuff (@jamescheney @wricciot ):
> tests/database/emptyfun.links
> tests/database/empty.links
> tests/database/factorials.links
> tests/database/unit.links
> tests/database/xpath.links
> tests/database/xpath-reduced.links
> tests/shredding/emptyfun.links
> tests/shredding/empty.links
> tests/shredding/jrules.links
> tests/shredding/organisation.links
> tests/shredding/travel_portal.links
> tests/shredding/unit.links

These tests are run in a different way by the run-tests script, because they require some initial database setup; they are listed in the `tests/[shredding|database]/testsuite.config` files.  Adding these files as places to look for test references should fix this.

Alternatively, maybe it would be sensible to move the logic for the database config / test running into the main test runner so that database-dependent tests can be run from `.tests` files.  Separate issue if so.

**Comment by dhil** [comment]
> Modules (@SimonJF @dhil )
tests/modules/cyclicA.links
tests/modules/cyclicB.links
tests/modules/cyclicC.links
tests/modules/import0.links
tests/modules/import_via_open1.links
tests/modules/moduleB.links
tests/modules/moduleC.links
tests/modules/records.links
tests/modules/switch-test.links
tests/modules/type-res110/bar.links
tests/modules/type-res110/foo.links
tests/modules/varRefA.links
tests/modules/varRefB.links

As far as I am aware these are working as intended.

**Comment by frank-emrich** [comment]
@jamescheney 
> These tests are run in a different way by the run-tests script, because they require some initial database setup; they are listed in the `tests/[shredding|database]/testsuite.config` files. Adding these files as places to look for test references should fix this.
> 
> Alternatively, maybe it would be sensible to move the logic for the database config / test running into the main test runner so that database-dependent tests can be run from `.tests` files. Separate issue if so.

I've amended my checker script to treat testsuite.config files accordingly, let's keep the test drivers for this as they are for now.

@rudihorn 
This also solves the issue with 
tests/relational-lenses/01_cds.links
tests/relational-lenses/02_cds.links
tests/relational-lenses/03_cds.links

**Comment by frank-emrich** [comment]
@dhil 
> As far as I am aware these are working as intended.

On closer inspection some of them are okay (referenced by other modules), but the following files look as if they are indeed orphaned.
tests/modules/records.links
tests/modules/switch-test.links
tests/modules/type-res110/bar.links
tests/modules/type-res110/foo.links
tests/modules/varRefA.links

The idea of this issue is mostly that the original authors of those files can have a look and say whether we should just add those files to the corresponding .tests file. It looks like @SimonJF is the author of all of these remaining module tests. Could you please have a look, @SimonJF ?

**Comment by SimonJF** [comment]
Sorry for not responding sooner -- it seems that I wasn't getting notifications for mentions...

Sessions stuff: these are tests to see whether cancellation and exceptions work correctly on the client. Since we don't have a client-side web testing framework, these don't get run automatically, but I think they're still useful to have in the codebase.

Distribution stuff: This is a bit of a mess, done during my PhD when I was tinkering with a custom Node.js runner to emulate client-server communication. I'd be happy with them being deleted.

Mutuals stuff: Unintentional omissions.

Modules: Also most likely unintentional omissions.


Thanks for pointing these out. I will open a PR which fixes the orphaned tests and deletes the distribution ones.

**Comment by frank-emrich** [comment]
Thanks for everyone's help! #830 will make sure that this doesn't happen again.
