### ISSUE TITLE
Improve the test suite driver

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#83]
Current testing script is not very flexible. It would be nice to have something more powerful that would allow more complicated testing scenarios. Here are some features we might want in a testsuite:
- Add custom compilation flags separately to each test
- Run extra setup before actually running a test (e.g. prepare database)
- Display summary at the end so no failures go unnoticed
- Expect that some tests will be broken
- Testing for errors, i.e. expecting that compilation of a given file will fail with a specific error message
- Performance testing?

GHC has a testsuite drivers that would most likely allow us to do all the above. I'm just not sure how difficult would it be to adapt it to work with Links. The core of GHC's testsuite driver is written in Python but there is also some Haskell code. At the very least this code will need to be rewritten to OCaml but I suspect there might be more GHC-specific pieces of code.

See also #64 for some earlier work and discussion on testsuite improvement.

**Comment by jamescheney** [comment]
Related to #163 ?

**Comment by jamescheney** [comment]
I think some of these things have now been added to the tests, so I propose we close this and create a new issue about any specific needs that are not yet met.

**Comment by jamescheney** [comment]
Closing
