### ISSUE TITLE
More efficient SQL query building

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#833]
As per #832, it would be useful to have an efficient way of constructing SQL strings rather than using naive string concatenation.

It might be nice to tie this into pretty-printing, too.

**Comment by rudihorn** [comment]
Worth checking out the relational lenses SQL code (https://github.com/links-lang/links/blob/master/lens/database.ml and https://github.com/links-lang/links/blob/master/lens/database.mli) as it already uses more efficient formatting, has single code for pretty printing (by using the dummy database driver) and is fairly compact. Though it doesn't support all of the operations required by links' query engine.

**Comment by jamescheney** [comment]
It would be nice to avoid this overlap in code capabilities...
