### ISSUE TITLE
Stricter enforcement of query effects?

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#841]
Following discussion in #835 I propose the following (mildly) breaking change:

- The use of `asList` and `for(<--)` is limited to tame contexts, i.e. the wild effect is required to be definitely absent.
- As a consequence, it becomes a type error to write a query that accesses database tables without explicitly writing `query` around it.
- Therefore, the implicit insertion of `query` keywords around `Iteration`s that happen to contain table references is no longer necessary; moreover, it would be possible to desugar such comprehensions to calls to `asList` (or vice versa, as currently `asList` is defined in terms of a table comprehension), since the two supposedly equivalent constructs are actually equivalent.

I think this would be cleaner and matches what we say about `query` and `asList` in various papers.

It does potentially break existing code, in the following sense:
- any code that explicitly relied on the implicit insertion of `query` keywords around table comprehensions, now fails to typecheck.
- relatedly, any type annotations that previously used effect / presence polymorphism for code that runs on the database, now need to be changed to specify that the code must be tame (i.e. the wild effect is absent).

I am creating a PR building on #838 that shows all of the places that need to be fixed in the test suite.  There aren't that many: the most affected example is the winestore which uses queries with implicit table comprehension syntax freely, and there are a couple of other places where query keywords need to be added or type annotations strengthened.

My sense is the number of changes is small and it's worth it to get rid of the implicit `wrapTableIterators` pass, which was always ad hoc (i.e. applied to queries with table comprehensions but not those containing asList), and makes it crystal clear when/where queries are actually issued (with the caveat that query expressions that don't actually refer to the database will still execute in-memory.)

However I'd like there to be a discussion of this (and ideally for the impact on larger applications like GtoPdb to be assessed) first.

**Comment by SimonJF** [comment]
I'm very much in favour of this change. It's always seemed counterintuitive that unenclosed <-- comprehensions were allowed. I'll check it on my GtoPdb code, but I doubt it'll be problematic modulo maybe some superficial changes.

**Comment by jamescheney** [comment]
Per #838, something like this needs to be done to resolve #835 without introducing new bugs due to failure to check that query results are flat.
