### ISSUE TITLE
Ordering behavior is incorrect/inconsistent on some database drivers

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#856]
`orderby` appears to produce inconsistent results (as already documented in `factorials.links`).  A minimal example:
```
var db = database "links";
var factorials = table "factorials" with (i : Int, f : Int) from db;

fun insertSome() {
  delete (x <-- factorials);
  insert factorials
  values (f, i)
     [(f=1, i=1),(f=2, i=2),(f=6, i=3)];
}
var asdf = insertSome();
query {
    for (row <-- factorials)
    where (row.i <= 5)
    orderby (row.i)
      [(i=row.i, f=row.f)]
  }
```
We get the result list in reverse order in Postgres and MySQL, while for SQLite3 the order is correct.

The SQL query that is generated for each database is the same, so presumably somewhere in the Postgres and MySQL database drivers the order of the returned results is being reversed.

This blocks #322 since it prevents us running the tests on all three databases and getting the same results.

**Comment by dhil** [comment]
For postgresql the "bug" is in the `ocaml-postgresql` library as our database driver defers to the `get_all_lst` implementation in that library. The problematic code https://github.com/mmottl/postgresql-ocaml/blob/master/src/postgresql.ml#L736.

We can workaround this by wrapping the call to `get_all_lst` in a `List.rev`.

**Comment by jamescheney** [comment]
This isn't the only problem, but my upcoming PR will fix this.

(basically, Sqlite3 was building a reversed list, which was correctly un-reversed by List.map later but MySQL and PostgresQL were correctly building non-reversed lists which were incorrectly being reversed.)  But we can do this without any reversing.

Note that `get_all_lst` is used only in `execute_insert_returning` (where the order doesn't matter since the result has to be a singleton) and `execute_untyped_select` which appears to be dead code.  Most queries construct results lists using `dbvalue#map`
