### ISSUE TITLE
null.links: Database test failure

### ISSUE THREAD

**Issue by dhil** [links-lang/links#862]
The test `tests/database/null.links` fails on my machine. 
```
$ ./run-tests db-only
cmnd=psql -h localhost -U links -p 5432 -v ON_ERROR_STOP=1 -q -d links -f tests/database/factorials.sql
cmnd=psql -h localhost -U links -p 5432 -v ON_ERROR_STOP=1 -q -d links -f tests/database/null.sql
cmnd=psql -h localhost -U links -p 5432 -v ON_ERROR_STOP=1 -q -d links -f tests/database/xpath-reduced.sql
cmnd=psql -h localhost -U links -p 5432 -v ON_ERROR_STOP=1 -q -d links -f tests/database/xpath.sql
cmnd=./links --config=tests/database/config tests/database/factorials.links
() : ()
cmnd=./links --config=tests/database/config tests/database/factorials-large.links
() : ()
cmnd=./links --config=tests/database/config tests/database/empty.links
[] : [(|_::Base)]
cmnd=./links --config=tests/database/config tests/database/emptyfun.links
[] : [(f:Int,i:Int)]
cmnd=./links --config=tests/database/config tests/database/null.links
Raised at file "core/database.ml", line 63, characters 12-92
Called from file "core/database.ml", line 144, characters 23-51
Called from file "core/database.ml", line 163, characters 29-50
Called from file "list.ml", line 69, characters 12-15
Called from file "core/database.ml", line 162, characters 9-19
Called from file "core/evalir.ml", line 723, characters 34-71
Called from file "src/core/lwt.ml", line 818, characters 19-23
Re-raised at file "src/core/lwt.ml", line 823, characters 6-15
Called from file "core/proc.ml", line 288, characters 5-64
Called from file "core/proc.ml" (inlined), line 297, characters 4-13
Called from file "core/proc.ml", line 300, characters 17-27
Called from file "core/evalir.ml", line 932, characters 10-67
Called from file "camlinternalLazy.ml", line 31, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 36, characters 4-11
Called from file "bin/driver.ml", line 84, characters 8-75
Called from file "camlinternalLazy.ml", line 31, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 36, characters 4-11
***: Runtime error: Attempted to read null integer from the database 
FAILED TEST null
cmnd=./links --config=tests/database/config tests/database/unit.links
[(), ()] : [()]
cmnd=./links --config=tests/database/config tests/database/xpath.links
() : ()
cmnd=./links --config=tests/database/config tests/database/xpath-reduced.links
() : ()
executing custom test script tests/validate_typecheck_testfile.testscript
SUCCESS: All examples occur in tests/typecheck_examples.tests
```

**Comment by jstolarek** [comment]
I tried running bisect. On eda2a17c all database tests fail on my machine (`Fatal error: exception Links_core.Settings.Name_clash("show_raw_type_vars"`), though there seems to be no problems on Travis. (Why?) Then the next commit (4393d7fa) fixes the problem and all database tests pass, and then the current head commit (db2cfa2c) breaks the one test that @dhil reports above.

**Comment by jamescheney** [comment]
`null.links` tests that the settings `coerce_null_integer` and `null_integer` are working correctly.  I added this test because drivers for mysql was not handling nulls in the same way as the other drivers.

The sample config file (and the database-specific ones I just added) all have these settings:
```
coerce_null_integers=on
null_integer=-1
```

I suspect that you are using local versions of the config files, i.e. `tests/database/config`, and the `run-tests` script will use that by default if it is present instead of `config.sample`.  Therefore, you should be able to resolve this by copying `config.sample` or adding the above two lines to your local `config`, it is not an issue with the Links codebase per se.

Eventually, we will support nulls (#655), design is still WIP.

**Comment by jstolarek** [comment]
>  you should be able to resolve this by copying config.sample or adding the above two lines to your local config

Indeed, that works.

**Comment by dhil** [comment]
> I tried running bisect. On [eda2a17](https://github.com/links-lang/links/commit/eda2a17c59d958215ccd04d56d065760bf96717a) all database tests fail on my machine (`Fatal error: exception Links_core.Settings.Name_clash("show_raw_type_vars"`)

You need to delete "types_refactor.{ml,mli}" from your source tree.

**Comment by dhil** [comment]
Thanks @jamescheney. I was using the "old" config.sample as config. The test suite pass now that I updated the config file with the two new entries.

**Comment by jstolarek** [comment]
> You need to delete "types_refactor.{ml,mli}" from your source tree.

Apparently, these are part of the commit and only removed in 4393d7fa4.
