### ISSUE TITLE
`make tests` does not (re)build links executable

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#872]
I would expect that `make clean && make tests` will build `links` executable before running tests but instead it complains - rightly - that there are no rules to build `links` target since no such target is defined in the `Makefile`. This is easily fixed but the fix will have an effect that it will rebuild `links` target every time before running tests. This is potentially undesirable, e.g. if we want to run tests but the code does not compile at the moment. Thoughts on the desired behaviour here?

**Comment by dhil** [comment]
I think the current behaviour is the desired behaviour.
