### ISSUE TITLE
"Type mismatch" IR typechecking error with Prelude `linFork`

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#875]
Compiling `linFork` function from Prelude:
```
# #sig linFork : forall s::Session,e::Row.((s) ~e~@ ()) ~e~> ~s
sig linFork : forall s::Session,e::Row.((s) {SessionFail:[||]}~@ ()) ~e~> ~s
fun linFork(f) {
  var ap = new();
  var _ = spawnAngel {
    f(accept(ap))
  };
  request(ap)
}

```
produces an IR typechecking error:
```
***: IR Type Error: Type mismatch:
 Expected:
  (454::Session) {SessionFail:() {}-> [||]}~@ ()
 Actual:
  (454::Session) {SessionFail:() {}-> [||]}~@ ()
occurring in IR binding:
(Ir.Let (
   (1805,
    ((454::Session) {SessionFail:() {}-> [||]}~@ (), "f", Var.Scope.Local)),
   ([], (Ir.Return (Ir.Variable 1811)))))
```
Reproduced on 74bb29ee with following config:
```
typecheck_ir=true
fail_on_ir_type_error=true
prelude=tests/empty_prelude.links
optimise=false
debug=true
print_types_pretty=true
recheck_frontend_transformations=true
hide_fresh_type_vars=false
show_flavours=true
show_quantifiers=true
show_raw_type_vars=true
```
Set `print_types_pretty=false` to see the full structure of types in the error message.

#874 is likely related.

**Comment by jamescheney** [comment]
This also seems to be caused by the same problem as #876, #874.

**Comment by jstolarek** [comment]
Indeed, I should have written this earlier. An obvious advantage of creating tests for newly-reported bugs is that we can immediately notice when we fix something accidentally. This single fix in the irCheck immediately shows in the test suite since tests for #874, #875 and, #876 now all pass. I'll push a fix later.
