### ISSUE TITLE
Release Links version 0.9.2 (Burghmuirhead)

### ISSUE THREAD

**Issue by dhil** [links-lang/links#910]
**Task**: Package and release Links on OPAM.
**Version**: 0.9.2 (Burghmuirhead)
**When**: primo-September
**Responsible**: @frank-emrich (aided by @dhil)

**Comment by dhil** [comment]
Post release close this issue by merging a PR that bumps the version number to 0.9.3.

**Comment by dhil** [comment]
I understand that you, @frank-emrich, are currently interning at Google, so I understand if you are occupied with other stuff at the moment. If you still want to perform release let me by end of next week, otherwise I will start the release process.

**Comment by frank-emrich** [comment]
The internship hasn't started yet and I'm intending to do the release. I will get in touch with you about this next week.

**Comment by jamescheney** [comment]
It would indeed be good to get this done soon.  But there are still a few issues milestoned 0.9.2 that are not (as far as I know) resolved yet.  I will check on their status.

**Comment by dhil** [comment]
As far as I am aware @frank-emrich is looking into performing the release, though, I think there were a few bits he wanted to land in master first.

**Comment by frank-emrich** [comment]
Indeed, I will tackle this tomorrow (=Friday).

**Comment by frank-emrich** [comment]
I drafted a changelog, which can be seen in 
https://github.com/frank-emrich/links/blob/f39dc87aa86086944ac371bbd0e76d1f64e2dc34/CHANGES.md
(We don't seem to be creating PRs for changelogs).

I vaguely remember that this release fixes some problem in 0.9.1 where many (all?) web or database examples were broken, but I may be wrong. Does this ring a bell? I went through all commits sine 0.9.1 to create the changelog, but I couldn't find something sounding like that.

**Comment by dhil** [comment]
Do you mind opening a PR with your `CHANGES.md`?

**Comment by frank-emrich** [comment]
Here you go: #918

**Comment by frank-emrich** [comment]
The new release has been accepted into the opam repository.
