### ISSUE TITLE
Odd syntax restriction on the body of an escape

### ISSUE THREAD

**Issue by dhil** [links-lang/links#921]
Links fails to parse the body of an `escape` expression, if the body is a variant, e.g.

```links
# escape0.links
escape k in A

$ ./links escape0.links
***: Parse error: escape0.links:3

  
   ^ 
```

A possible workaround is to enclose the body expression in a pair of parentheses.

```links
# escape1.links
escape k in (A)

$ ./links escape1.links
A : [|A|_::Any|]
```

It seems to me the (implemented) grammar is overly restrictive, and I am fairly confident this is a mistake/bug.

We may elect to ignore this bug, if we are ultimately going to dispense of `escape` (c.f. #23).

**Comment by jamescheney** [comment]
Huh.  I'm a bit surprised that the body is allowed to be anything other than a curly brace delimited block.  Though I guess it would make sense to allow things like this:
```
escape k in A(<complicated expression using k>
```

**Comment by jamescheney** [comment]
And I think the alternative to having escape is either some similar syntax for call/cc (matching what is in the IR) or using delimited continuations via handlers instead, which seems like a longer-term project.

**Comment by dhil** [comment]
I'd like to dispense of `escape` and the internal callcc in favour of handlers. There is loads of research yet to be done to make this possible!
