### ISSUE TITLE
Row types should be printed in round-trippable canonical forms

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#926]
Type inference can result in row types that get printed out in non-parsable ways, for example:

```
links> fun f(tbl) { for (x <-- tbl) where (x.id == 42) [x] };
f = fun : (TableHandle((|id:Int|a::Base),(|_::Base),(|_::Base))) -> [(|id:Int|a::Base)]
```
If we try to actually ascribe the above signature then this doesn't parse:
```
links> sig f : (TableHandle((|id:Int|a::Base),(|_::Base),(|_::Base))) -> [(|id:Int|a::Base)]
***: Parse error: <stdin>:1

  sig f : (TableHandle((|id:Int|a::Base),(|_::Base),(|_::Base))) -> [(|id:Int|a::Base)]
                            ^ 
```
because of the superfluous `|`, whereas this is fine:
```
links> sig f : (TableHandle((id:Int|a::Base),(|_::Base),(|_::Base))) -> [(id:In
...... fun f(tbl) { for (x <-- tbl) where (x.id == 42) [x] };
f = fun : (TableHandle((id:Int|a::Base),(|_::Base),(|_::Base))) -> [(id:Int|a::Base)]
```

HT @vcgalpin

**Comment by dhil** [comment]
Yes, this has been a long time problem with the type pretty printer. I think the best course of action is to completely rewrite it using the visitor framework. The current implementation carries some optional state arguments that are difficult to keep track of.

**Comment by frank-emrich** [comment]
I have a question regarding this:
To me it seems like we currently don't have any source syntax for the `Mono` restriction. Are we planning to change this? Just hiding this information when printing quantifiers seems dodgy to me.

**Comment by dhil** [comment]
No, we should have syntax for it. Open an issue for it, then we can track it.

**Comment by dhil** [comment]
The ultimate goal is ensure that every inferred type is typeable (as in writing) in Links.
