### ISSUE TITLE
Correction for install.md

### ISSUE THREAD

**Issue by vcgalpin** [links-lang/links#948]
The line:

>
>You can then install Links simply by issuing the command:
>```
>$ opam install postgresql links
>```

should be modified to 

>
>You can then install Links simply by issuing the command:
>```
>$ opam install postgresql links-postgresql
>```

otherwise the db interation won't work.

**Comment by jamescheney** [comment]
Closed by 2923893c80677b67cacc6747a25b5bcd65c4c2b6
