### ISSUE TITLE
Regression in examples URL

### ISSUE THREAD

**Issue by slindley** [links-lang/links#949]
The installation instructions in `INSTALL.md` suggest that the examples should be found at the URL `http://localhost:8080/examples/`. But this fails with a `Not found` error (it certainly used to work once). Using `http://localhost:8080/` does work, though - which is arguably fine providing we synchronise the instructions with the implementation!

**Comment by jamescheney** [comment]
This inconsistency seems to have been introduced by  #705 which made the examples page dynamic, as requested in #287
