### ISSUE TITLE
Travis build fails due to Sphinx requiring Python >= 3.6

### ISSUE THREAD

**Issue by frank-emrich** [links-lang/links#955]
Travis currently [fails](https://travis-ci.org/github/links-lang/links/builds/770921976#L848) at `make doc` on master because the `sphinx`  Python library seems to have started using features that are only available in Python >= 3.6.

There are several remedies:
1. Try to hard-code using an older version of `sphinx`.
2. Manually request installation of Python 3.6 (Ubuntu Xenial/16.04, which we currently use in Travis, has a default version of 3.5 when installing "python3", but Python 3.6 can be requested manually).
3. Update our Travis bots to use Ubuntu Bionic/18.04, which installs Python 3.6 as default.

The last option seems favorable to me, as we've had several problems in the past due do using an ancient Ubuntu version. However, this would mean that we never make the requirement for Python >= 3.6 explicit anywhere. I have verified in an experiment that simply raising the Ubuntu version in Travis from Xenial to Bionic fixes the problem, without needing to change anything else in the Travis config.

**Comment by slindley** [comment]
We should definitely go for 20.04! That's already over a year old.

**Comment by frank-emrich** [comment]
Pros of going straight to 20.04: We could finally get rid of the custom installation logic for opam 2 that is currently happening in Travis, because Ubuntu 20.04 has packages for opam 2.x (unlike 16.04 and 18.04).

Cons: Using a slightly older version of Ubuntu allows us to notice when we depend on "recent" versions of certain packages, which allows us to document this (like requiring Python 3.6). This means that whenever we ask a random person (like a reviewer) to install Links, we are aware of the requirements for the underlying system.

**Comment by slindley** [comment]
20.04 *is* a relatively old version of Ubuntu. Links is a research language. We should go with 20.04 and in general stick with the latest LTS release (perhaps with a lag of 6-12 months following initial release).
