### ISSUE TITLE
Consider mergng links-mysql and links-mysql8

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#963]
In #958 we have created a new library `links-mysql8` which uses `ocaml-mysql8` to connect to MySQL 8.x DBMSs.

I recall seeing somewhere that the MySQL8 client library is backwards compatible with older MySQLs but not the reverse.  So, the extra library may not be necessary.  We are not currently able to test this in CI, since it is difficult to set up MySQL5.7 on Ubuntu 20, but it should be easy enough to test it in a VM using an older distribution that comes with MySQL 5.7 standard.

If this works, I'm happy with going back to using only `ocaml-mysql8` and `links-mysql`.  If not, given the current code duplication between the `links-mysql` and `links-mysql8` libraries I'd slightly prefer merging the two libraries so that we adaptively use the right one dpeending on the mysql version of the database we are connecting to.

**Comment by jamescheney** [comment]
On reflection combining into two libraries doesn't seem like a good thing to do, since the single library would depend on both ocaml-mysql and ocaml-mysql8.  So the main question is whether we can connect to legacy MySql 5.x instances from ocaml-mysql8.

**Comment by dhil** [comment]
I am closing this issue as #966 tests `links-mysql8` against a MySQL 5.7 instance.
