### ISSUE TITLE
Licenses for packages `links`, `links-{postgresql,mysql,mysql8,sqlite3}`

### ISSUE THREAD

**Issue by dhil** [links-lang/links#974]
The OPAM linter complains about the license field in the packages `links` and `links-{postgresql,mysql,mysql8,sqlite3}` (c.f. ocaml/opam-repository#18781), because it is not [SPDX compliant](https://spdx.org/licenses/). I think all we have to do to make it compliant is to append `-only` or `-or-later` to the license string in the package definitions. The question is: do we want to be conservative, and insist on GPL version 2 only, or be liberal, and allow later revisions of GPL.

**Comment by dhil** [comment]
cc @jamescheney @slindley

**Comment by dhil** [comment]
During a video call Sam suggested that we should maybe upgrade the license to GPLv3.

**Comment by dhil** [comment]
Yesterday we agreed to upgrade to GPL-3-only.

**Comment by jamescheney** [comment]
Closed by #994?

**Comment by dhil** [comment]
Yes, thanks!
