### ISSUE TITLE
Clean up type pretty printing functions

### ISSUE THREAD

**Issue by SamuelNovak** [links-lang/links#995]
After the type system refactoring moved the representations of (Links) types of different kinds into a single (OCaml) type, namely `typ` (see `datatype = row = field_spec = ... = typ` in `types.ml`), there are now many redundant pretty printing methods `string_of_X` (again, in `types.ml`) that are now equivalent to `string_of_datatype` and could be removed. This will also require them to be changed to `string_of_datatype` in their call sites outside `types.ml`.

Note that they are different in that each calls a different function to prepare tyvar names (`free_bound_X`), but most of these are themselves aliases of the one used for datatype.

**Comment by dhil** [comment]
Closing as I resolved this as part of my changes to #982. I was hoping to dispense of all of those that operate over aliases of `typ`. Alas, that is not possible with the current setup, because each `string_of_X` provides a bit of crucial context information.
